### ISSUE TITLE
Getting Error response while running using seleniumwire 

### ISSUE THREAD

**Issue by sluthra-globallogic** [wkeeling/selenium-wire#10]
HI I am getting "Error response " while running the code snippet below .-

Code ; 
from seleniumwire import webdriver  # Import from seleniumwire
driver = webdriver.Chrome()
driver.get('https://www.google.com')
for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
            request.response.headers['Content-Type']
        )

Exact error faced : 

Error response
Error code: 502

Message: Bad Gateway.

Error code explanation: 502 - Invalid responses from another server/proxy.

Any help will be appreciated !!

**Comment by wkeeling** [comment]
Hi @sluthra-globallogic, many thanks for reporting this.

Can you run the same code but with debug logging enabled -

```
# Enable logging
import logging
logging.basicConfig(level=logging.DEBUG)

from seleniumwire import webdriver # Import from seleniumwire

driver = webdriver.Chrome()
driver.get('https://www.google.com')
for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
            request.response.headers['Content-Type']
        )
```

Hopefully the logging should provide some clues to the issue.

**Comment by sluthra-globallogic** [comment]
Thanks I fixed this by Running the download script provided with the installer – /Applications/Python 3.6/Install Certificates.command.
