### ISSUE TITLE
Max length of URL which we can get using seleniumwiere?

### ISSUE THREAD

**Issue by kapil87** [wkeeling/selenium-wire#100]
@wkeeling
I tried url with length greater that 64 chrs and I see that request was not even going out?
Is it expected behavior ?
for eg: following url : 
https://subdomain-1.test-app-gcp-europe-west2-1585346341969.ymeventarean.com

I changed the url to have length 64 or less and request started going out?

Let me know.

**Comment by CircuitSacul** [comment]
It looks to me like it is working. Could you share your code with me?

**Comment by wkeeling** [comment]
@kapil87 Is this still causing you an issue?
