### ISSUE TITLE
How to modify the request data?

### ISSUE THREAD

**Issue by Sdator** [wkeeling/selenium-wire#101]
My project has a requirement to capture ajax requests and modify the data (Form Data) it sends, so I tried the following. Although the modification was successful, the desired result was not obtained according to the response result.

```python
# I first thought of the method, but this property doesn't seem to be assignable.
for request in driver.requests:
    request.body = “”

# So I tried another method. Although the debug window showed that the body was successfully modified, based on the feedback from the response, I knew that this method was not available.
def custom(req, req_body, res, res_body):
    path = urlparse(req.path).path
    if path == "/open/get":
         req_body = b""

opt = {"connection_timeout": None, "ignore_http_methods": [],
           'custom_response_handler': custom}
```

**Comment by idxn** [comment]
@Sdator Your custom function need to return the response so the custom fx should be like this.
`def custom(req, req_body, res, res_body):
    path = urlparse(req.path).path
    if path == "/open/get":
         return = b""`

**Comment by idxn** [comment]
Currently, selenium-wire supports modifying the response data only. @wkeeling please correct me if i'm wrong.

**Comment by Sdator** [comment]
> Currently, selenium-wire supports modifying the response data only. @wkeeling please correct me if i'm wrong.

Hey friends thank you for answering the first time, if selenium-wire does not support it, do you have any recommended solution?

**Comment by idxn** [comment]
Emm I don't have any suggestion :( @wkeeling do you have one?

**Comment by wkeeling** [comment]
@Sdator thanks for your original question.

I'm afraid, as @idxn mentions, Selenium Wire does not support modification of a request body.

An alternative may be to use an intermediate proxy such as [mitm proxy](https://mitmproxy.org/) which could be configured to modify certain requests. You could then tell Selenium Wire about such a proxy in the [options](https://github.com/wkeeling/selenium-wire#proxies) you pass when you create the webdriver.

Sorry I'm not able to provide a better solution!

**Comment by Sdator** [comment]
> @Sdator thanks for your original question.
> 
> I'm afraid, as @idxn mentions, Selenium Wire does not support modification of a request body.
> 
> An alternative may be to use an intermediate proxy such as [mitm proxy](https://mitmproxy.org/) which could be configured to modify the body of certain requests. You could then tell Selenium Wire about such a proxy in the [options](https://github.com/wkeeling/selenium-wire#proxies) you pass when you create the webdriver.
> 
> Sorry I'm not able to provide a better solution!

Thanks for your answers, I will try an intermediate agent，I also hope that selenium-wire will add this feature in the future。
