### ISSUE TITLE
Getting noticed when requests list gets updated

### ISSUE THREAD

**Issue by seyedian** [wkeeling/selenium-wire#103]
Hello 
Please do not consider this an issue. It would be appreciated if help me with this.
Could you please let me know if there is an option to be able to figure out when the requests list gets populated?
What I need is as soon as a new request received in the requests list do some action. 

Best,

**Comment by CircuitSacul** [comment]
Do you mean without checking to see if `driver.requests` isn't empty?

**Comment by seyedian** [comment]
exactly,
Something like a notice. being noticed when a new record comes to the driver.request

**Comment by CircuitSacul** [comment]
`driver.requests` only get's "populated" when you request a page (with `driver.get`). The only way I see to do this is somewhere in your main program it checks to see if `driver.requests` has something in it or not. Do you have something specific you're trying to do? I'm just not exactly sure what it is your trying to get.

**Comment by wkeeling** [comment]
Selenium Wire already gives you the ability to [wait for a request](https://github.com/wkeeling/selenium-wire#waiting-for-a-request) that you are interested in:

```
request = driver.wait_for_request('/api/products/12345/')
```
However that mechanism is synchronous and will block until the request happens, or it times out.

It sounds as though you may be wanting some asynchronous notification mechanism, for example:

```
def notify_callback(request):
    # Do something with the request

# Register the callback
driver.on_request('/api/products/12345/', notify_callback)

# Perform other test actions. 
# The notify_callback() will be called automatically when the request is seen.
```

**Comment by seyedian** [comment]
thank you @wkeeling  for your explanation.

@CircuitSacul, I need to explore through the selenium-wire browser, every time I click on a link or any other interaction, I need to get notified if something new comes up into the requests.
In particular, I am looking for all Google Analytics payloads, as an example in the user clicks on a product we send information payload to Google Analytics for this action. I need to what are these payloads and on which product.

**Comment by CircuitSacul** [comment]
Sorry for my slow response.

I think I know what you want and this is an example of how you can do this:

```python
from seleniumwire import webdriver
from time import sleep
import selenium

print("Launching request logger. To exit, simply use Control+c. The program will also save the requests to a file for future reference.")
input("Press enter to continue")

driver = webdriver.Chrome()

request_log = []

def main():
    last_url = None
    while True:
        try:
            current_url = driver.current_url
            if current_url != last_url:
                request_log.append(f'\n\n#####\nURL Change:\nOriginal: {last_url}\nCurrent: {current_url}\n####\n')
                print(f"URL Changed to {current_url}")
                last_url = current_url

            if len(driver.requests) > 0:
                for request in driver.requests:
                    request_log.append(f"\nRequest Made: {request.path}")
                    print(f"Request made to {request.path}")
                del driver.requests
            sleep(1)
        except selenium.common.exceptions.UnexpectedAlertPresentException:
            print("Ignoring selenium.common.exceptions.UnexpectedAlertPresentException error")


try:
    main()
except KeyboardInterrupt:
    pass
finally:
    driver.quit()
    print("Program exited.")
    y_or_n = input("Would you like to save the request log to a file?\n>")
    if y_or_n.lower() in ['yes', 'ye', 'y', 'ys']:
        file_path = input("Please enter a filename (without extension) to save request log to\n>") + '.txt'
        with open(file_path, 'w+') as f:
            string = ''
            for item in request_log:
                string = string + item
            f.write(string)
        print(f"Request log saved to {file_path}")
```

Another option is simply using the built-in inspector tool. You can go to the Network tab to see all requests that were made.

**Comment by seyedian** [comment]
Hi @CircuitSacul

I really appreciate for getting back to me.

**Comment by CircuitSacul** [comment]
@seyedian 

No problem, glad I could help.
