### ISSUE TITLE
Selenium-wire closes browser automatically in django project

### ISSUE THREAD

**Issue by seyedehsan** [wkeeling/selenium-wire#105]
I am working on a very small django project. I am using Selenium-wire in my project because I need to collect the network request. Everything works as expected and when I head over to 127.0.0.1:8000 selenium-wire opens up a new chrome browser to start exploring and collecting the network data. so far so good. unfortunately, after around 30 seconds the window (Chrom browser) that was opened by Seleniumwire gets closed without any error. Can you please help me with this matter?

Here is my code in python:
`def home(request):
    # Download and install Chrome web driver
    driver = webdriver.Chrome(ChromeDriverManager().install())
    driver.get('https://www.google.com')
    context = {
        'posts': Post.objects.all
    }
    return render(request, 'blog/home.html', context)`

here is the log:
`System check identified no issues (0 silenced).
April 16, 2020 - 00:31:46
Django version 3.0.4, using settings 'quarter.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[16/Apr/2020 00:31:49] "GET / HTTP/1.1" 200 3772
[16/Apr/2020 00:31:50] "GET /static/js/live_qa.js HTTP/1.1" 304 0

Looking for [chromedriver 80.0.3987.106 win32] driver in cache
File found in cache by path [C:\Users\eee\.wdm\drivers\chromedriver\80.0.3987.106\win32\chromedriver.exe]

DevTools listening on ws://127.0.0.1:62836/devtools/browser/12578c74-68ba-4dfd-bb33-f8807a84878b
[16/Apr/2020 00:32:12] "POST / HTTP/1.1" 200 21`

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in responding.

I must admit I have not tried running Selenium from a Django view. Have you tried running the same code outside of the view - e.g. from a regular unit test, to see if Selenium Wire works in that situation? That could then help narrow down the issue.
