### ISSUE TITLE
Protocol Switching not hapenning

### ISSUE THREAD

**Issue by RapidEU** [wkeeling/selenium-wire#107]
Hiya, I'm trying to use selenium-wire and during the login process into a website I could notice protocol-switching is not hapenning, therefore the login phase of my application is not logging in. (Works just fine in normal selenium)
Any idea what could possibly be the reason for that? (I get 101 for protocol switching normally, but here nop)

**Comment by wkeeling** [comment]
It's possible that Selenium Wire's embedded proxy server isn't handling the switching correctly. Is the website using switching to upgrade to a websocket? Do you have an example public URL that exhibits the issue?

**Comment by RapidEU** [comment]
Yeah, any discord channel. 
Go to discord.gg and open a random server from the web client, check F12 network using selenium-wire and once using a normal browser.

Sorry for late response.

**Comment by wkeeling** [comment]
Thanks - managed to reproduce.

It looks as though I need to do some investigation into how best to support the websocket upgrade requests in Selenium Wire's embedded proxy server.

**Comment by wkeeling** [comment]
Fixed in version 1.1.0. Protocol switching is now supported and websocket connections are proxied.
