### ISSUE TITLE
Har generation support

### ISSUE THREAD

**Issue by jrgp** [wkeeling/selenium-wire#108]
This project looks like a nice pure-python alternative to using browsermob-proxy, which has for a while been the defacto way of tracking requests used with selenium.

Are there any plans to have seleniumwire generate the list of requests in the standard HAR format, a la browsermob and the "export/"import" functionality in the network tab in web browser dev tools?

See:

http://www.softwareishard.com/blog/har-12-spec/
https://en.wikipedia.org/wiki/HAR_(file_format)

**Comment by wkeeling** [comment]
This is certainly something that Selenium Wire could support, as virtually all of the information specified by the HAR format is available at the point where Selenium Wire captures a request. I'll have a look at what might be involved in terms of modifications to support it. I do agree that using a standardised format (and one that contains a lot more detailed information) could be more useful to people.

Many thanks for the idea!

**Comment by nrllh** [comment]
@jrgp did you check https://github.com/browserup/browserup-proxy ? but their Python wrapper seems to be outdated.

@wkeeling can we actually get the time of each request? I couldn't see any anything about that in docs.

**Comment by wkeeling** [comment]
@nrllh there's a `request.date` and `response.date` that will give you the date/time, although these aren't mentioned in the docs currently.

**Comment by jrgp** [comment]
@nrllh yep, I previously used browsermob-proxy, of which browserup-proxy is a modernized fork. I ended up writing my own har-generating MITM proxy using libcurl though to get around mysterious network problems caused by browsermob and its fork. 

I personally don't need this functionality within selenium-wire as I'm not using it, so I'd be fine if you closed this issue, but maybe you'd want to leave it open in case someone else needs it.

**Comment by wkeeling** [comment]
HAR generation has been added in v4.2.0

**Comment by nrllh** [comment]
Great job!

I get some errors while generating HAR file:

> 
> 
> KeyError: 'br'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 70, in decode
>     decoded = codecs.decode(encoded, encoding, errors)  # type: ignore
> LookupError: unknown encoding: br
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\handler.py", line 126, in response
>     self.proxy.storage.save_har_entry(flow.request.id, har.create_har_entry(flow))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\har.py", line 70, in create_har_entry
>     response_body_decoded_size = len(flow.response.content) if flow.response.content else 0
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 134, in get_content
>     content = encoding.decode(self.raw_content, ce)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 77, in decode
>     raise ValueError("{} when decoding {} with {}: {}".format(
> ValueError: LookupError when decoding b'Sd_\x12Q with 'br': LookupError('unknown encoding: br')
> 
> Error handling request
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 68, in decode
>     decoded = custom_decode[encoding](encoded)
> KeyError: 'br'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 70, in decode
>     decoded = codecs.decode(encoded, encoding, errors)  # type: ignore
> LookupError: unknown encoding: br
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\handler.py", line 126, in response
>     self.proxy.storage.save_har_entry(flow.request.id, har.create_har_entry(flow))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\har.py", line 70, in create_har_entry
>     response_body_decoded_size = len(flow.response.content) if flow.response.content else 0
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 134, in get_content
>     content = encoding.decode(self.raw_content, ce)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 77, in decode
>     raise ValueError("{} when decoding {} with {}: {}".format(
> ValueError: LookupError when decoding b'\x13\x1c with 'br': LookupError('unknown encoding: br')

It still generates the file, but I'm not sure if the error causes any negative effect on the generated file.

**Comment by wkeeling** [comment]
Thanks for testing @nrllh That error happens because one or more pages are compressed using the [Brotli](https://en.wikipedia.org/wiki/Brotli) encoding format and Selenium Wire doesn't currently support it. Those responses won't get recorded in the HAR file as a result.

One workaround is to ask the server to not compress the response by using the `disable_encoding` option:

```
options = {
    'disable_encoding': True  # Ask the server not to compress the response
}
driver = webdriver.Chrome(seleniumwire_options=options)
```
We should probably look at supporting Brotli encoding at some point.

**Comment by nrllh** [comment]
> **Those responses** won't get recorded in the HAR file as a result.

@wkeeling you mean only the response body?

**Comment by wkeeling** [comment]
Unfortunately the whole response - so none of the response fields will be stored for those affected responses.

**Comment by mwaiwanjiku** [comment]
Error handling request
Traceback (most recent call last):
  File "C:\Users\mwaiw\anaconda3\lib\site-packages\seleniumwire\handler.py", line 121, in response
    self.proxy.storage.save_har_entry(flow.request.id, har.create_har_entry(flow))
  File "C:\Users\mwaiw\anaconda3\lib\site-packages\seleniumwire\har.py", line 85, in create_har_entry
    "cookies": _format_response_cookies(flow.response.cookies.fields),
  File "C:\Users\mwaiw\anaconda3\lib\site-packages\seleniumwire\har.py", line 154, in _format_response_cookies
    return _format_cookies((c[0], c[1][0], c[1][1]) for c in fields)
  File "C:\Users\mwaiw\anaconda3\lib\site-packages\seleniumwire\har.py", line 142, in _format_cookies
    cookie_har["expires"] = datetime.fromtimestamp(expire_ts, timezone.utc).isoformat()
OSError: [Errno 22] Invalid argument

**Comment by mwaiwanjiku** [comment]
i am getting this errors and i dont know where am going wrong

**Comment by wkeeling** [comment]
@mwaiwanjiku can you share the URL you're using when you see this issue?

**Comment by mwaiwanjiku** [comment]
https://odibets.com/league

**Comment by mwaiwanjiku** [comment]
https://odibets.com/league
