### ISSUE TITLE
High CPU usage on a request thread

### ISSUE THREAD

**Issue by Zeevs78** [wkeeling/selenium-wire#115]
Hi. I've been using selenium-wire for some months mostly without problem. 

Some days ago I updated from 1.0.x to the latest version 1.1.1 and I noticed that the entire script I run was noticeably slow and the python process would be using maximum cpu usage (about 6-9% on a 16 thread cpu). 

After some digging I found that a request thread was the problem. To make sure it was a request thread I named them "REQUEST".

> threading.enumerate()
![image](https://user-images.githubusercontent.com/65993008/82973749-39b87980-9fa6-11ea-88fc-fd829b799fe9.png)
> Python.exe seen on Process Explorer
![image](https://user-images.githubusercontent.com/65993008/82973774-4b9a1c80-9fa6-11ea-9cda-edc0d0d55cab.png)

I had set connection_timeout: None on the options (which I forgot to change for months), but changing it to some number didn't make the request go away after the timeout.

I use chromedriver, set the requests with driver.scopes and all of those requests are XHR/FETCH with JSON responses; checking the network tab on DevTools doesn't show any failed request or weird stuff happening. Since the only thing I changed from the selenium-wire code is the request thread name I don't even know what starts the problem and other than that I have no reproduction steps.

For now, the problem is not present when using version 1.0.10. I might look into it some more if someone has the same problem.

**Comment by wkeeling** [comment]
Many thanks for reporting this and also for all your investigation work!

I've dug into it some more, and discovered that a request thread can spin after a websocket connection gets closed, because a flag that should have been set was not being set. Websocket connection handling is a relatively new addition to the library.

I've fixed the issue in the latest version 1.1.2. Would you be able to update and see if that fixes the issue for you?

**Comment by Zeevs78** [comment]
I'm trying the new version 1.1.2 and I can confirm that the problem is not present, at least on my end.

I was losing my mind prior to finding out what the issue was! Thank you for the quick response and fix.

**Comment by wkeeling** [comment]
No problem, thanks for confirming.
