### ISSUE TITLE
Change upstream proxy on fly

### ISSUE THREAD

**Issue by eanon** [wkeeling/selenium-wire#118]
Hi, Until now, I'm used to use Selenium alone against Gecko driver and through HTTP proxies that I'm changing on fly executing Javascript code from Python. But these days I encounter the new need to be able to handle proxy with basic authentication. So, I listed some possibilities and Selenium Wire appears to be a nice, light and efficient one. It works like a charm passing infos about proxy to webdriver constructor/init, but I don't see any out-of-the-box method to change the proxy on the fly. My previous way was to change it at Firefox level, but as I understand, Selenium Wire introduces its own proxy on 127.0.0.1 and my proxy becomes an upstream one... Thus, chained proxy change has to take place in Selenium Wire only. 
­
**Is it possible to add the possibility to update upstream proxy info in Selenium Wire or did I missed a point since it's already possible?**
­
However, thanks for Selenium Wire; even if no proxy change for now, I think I'll use it just because of the possibility to reach the HTTP status code (big lack in Selenium and BMP appears to be a little heavy for me). Bravo!

--
Windows 7 + Linux CentOS 7
Python 3.7
Selenium 3.141.0
Selenium Wire 1.1.2

**Comment by woswos** [comment]
I am not the maintainer, but I have a follow-up question. How do you envision changing the proxy on the fly? Would you chance a value in a configuration file? Would you send an HTTP request to Selenium Wire's proxy? I just thought about how it could be implemented, and I couldn't settle on a feasible solution. @eanon Did you have a solution in your mind already? If you had something, sharing it (I believe) would be useful for someone to implement it.

**Comment by eanon** [comment]
@woswos As I said, talking about a way to change proxy on the fly, I have already a working solution dealing with  Firefox from JavaScript (see code at bottom), but it doesn't handle the proxy authentication... So, from this point, what I could have in mind could be things like those (unsorted): 

- Manually prepare Firefox profile with right signons info, then re-use this profile.
- Deal with the Firefox's login manager to store any useful logins info against used proxies.
- Learn how and where Firefox's signons info is stored in profile, then produce them directly.
- Load a browser extension that does the job.
...

But all these possibilities are about Selenium alone, without Selenium Wire (nor any intermediate local proxy like BrowserMob Proxy). Going with Selenium Wire, honestly, I don't know yet. I just installed it yesterday and played a little with it, but I don't know its flow and structure just now. It's the reason why of my question here: **How to change upstream proxy settings (including credentials) in Selenium Wrire without launching a new underlying Selenium instance and without breaking anything else in the overall Selenium Wire working?** 

--
Well, outside of Selenium Wire, but here is how I currently change proxy (w/o authentication) on a fly against Firefox (knowing it's on deprecated Firefox API, so not guaranteed to work in the future):

```
def set_proxy_on_fly(gecko_driver, ip_port):
    ip, port = ip_port.split(':')
    script_template = """
    let prefs = Components.classes["@mozilla.org/preferences-service;1"]
    .getService(Components.interfaces.nsIPrefBranch);
    prefs.setIntPref("network.proxy.type", 1);
    prefs.setCharPref("network.proxy.http", "{0}");
    prefs.setIntPref("network.proxy.http_port", "{1}");
    prefs.setCharPref("network.proxy.ssl", "{0}");
    prefs.setIntPref("network.proxy.ssl_port", "{1}");
    """
    gecko_driver.get("about:config")
    gecko_driver.execute_script(script_template.format(ip, port))
```

**Comment by eanon** [comment]
OK, digged a little and it seems changing driver._client._proxy.proxy_config is working. I didn't pushed the investigation (a little in urge since I need something -- whatever -- working for yesterday:) and it could maybe raise some side effects, but from my quick test below, this short hack seems to work with the sample of proxies I have under my hand just now (one only with authentication and some without). 

Please, could you test it on you part ? And @wkeeling, could you tell me if I'm breaking something around in Selenium Wire this way? 

TIA

```
# Change upstream proxy on fly in Selenium Wire
import os, sys
from collections import namedtuple
from seleniumwire import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from html2text import html2text

# Needed Configuration:
PROXIES = [<HERE_A_LIST_OF_PROXIES_INCLUDING_ONES_WITH_AUTHENTICATION>]
IP_CHECKER = "<HERE_A_WEBSITE_TO_TEST_OUR_PUBLIC_IP>"

print("TESTING ON FLY PROXY CHANGE in SELENIUM WIRE -- eanon 2020-06-01")
ff = FirefoxBinary("C:/Program Files/Mozilla Firefox/firefox.exe")
gecko = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), "geckodriver.exe")
opts = webdriver.FirefoxOptions()
opts.add_argument("--headless")
sw_opts = {'proxy': {'http': 'http://0.0.0.0:0:00', 'https': 'https://0.0.0.0:0:00'}}
ProxyConf = namedtuple('ProxyConf', 'scheme username password hostport')
with webdriver.Firefox(firefox_binary=ff, executable_path=gecko, options=opts, seleniumwire_options=sw_opts) as driver:
    print("Selenium Wire initiated with fake proxy")
    for idx, proxy in enumerate(PROXIES):
        print("--- %d ---\nSet proxy %s..." % (idx+1, proxy))
        auth, ip_port = proxy.split('@') if '@' in proxy else (None, proxy)
        user, pwd = auth.split(':') if auth else ('', '')
        driver._client._proxy.proxy_config = {
            'no_proxy': 'localhost,127.0.0.1',
            'http': ProxyConf(scheme='http', username='%s' % user, password='%s' % pwd, hostport='%s' % ip_port),
            'https': ProxyConf(scheme='https', username='%s' % user, password='%s' % pwd, hostport='%s' % ip_port)
        }
        print("Selenium Wire settings after on fly change: %s" % driver._client._proxy.proxy_config)
        driver.get(IP_CHECKER)
        resp = driver.last_request.response
        if resp:
            status = resp.status_code
            content = html2text(driver.page_source).strip()
            print("=> Checked public IP: %s" % content if status == 200 else "=> HTTP Error %d" % status)
            continue
        print("=> No response")
```

**Comment by michhri** [comment]
Hello,
I am trying to change proxies on the fly in the aforementioned way but neither the `Chrome` nor the `Firefox` webdriver objects have a `_client` attribute. There also seems to be no mention of such an attribute in the codebase of `selenium-wire` or `selenium` itself.
What am I missing?
Thank you.

**Comment by eanon** [comment]
@michhri Hi, I don't work anymore in the code of the project that used selenium-wire with the hack I expressed above... My code was using Selenium 1.2.3 and I see that the current release is the 4.2.3. So, maybe the Selenium-Wire code has changed since this date. 

Here is the state of the Firefox class from Selenium-Wire 1.2.3's seleniumwire/webdriver/browser.py:
```python
class Firefox(InspectRequestsMixin, _Firefox):
    """Extends the Firefox webdriver to provide additional methods for inspecting requests."""

    def __init__(self, *args, seleniumwire_options=None, **kwargs):
        """Initialise a new Firefox WebDriver instance.

        Args:
            seleniumwire_options: The seleniumwire options dictionary.
        """
        if seleniumwire_options is None:
            seleniumwire_options = {}

        self._client = AdminClient()
        addr, port = self._client.create_proxy(
            port=seleniumwire_options.pop('port', 0),
            proxy_config=seleniumwire_options.pop('proxy', None),
            options=seleniumwire_options
        )

        if 'port' not in seleniumwire_options:  # Auto config mode
            try:
                capabilities = kwargs.pop('desired_capabilities')
            except KeyError:
                capabilities = DesiredCapabilities.FIREFOX.copy()

            capabilities['proxy'] = {
                'proxyType': 'manual',
                'httpProxy': '{}:{}'.format(addr, port),
                'sslProxy': '{}:{}'.format(addr, port),
                'noProxy': [],
            }
            capabilities['acceptInsecureCerts'] = True

            kwargs['capabilities'] = capabilities

        super().__init__(*args, **kwargs)
```
And looking [there](https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/webdriver.py), it doesn't seem to exist anymore (so, maybe another way, but you have to dig in the code by yourself). For me, if I had to re-work in my code, it would be a reason to not update Selenium-Wire... 

Of course, the easiest would be to expose a public method to change proxy on fly :)

**Comment by wkeeling** [comment]
@michhri the code has changed somewhat since this ticket was opened, but it is still possible to change the proxy settings on the fly albeit with a different internal API, as follows:
```
driver.proxy._master.options.update(
    mode='upstream:https://new_proxy_host:new_port'
)
```
We'll perhaps look at providing a more friendly public API to do this in future, since we've had other people asking for the same thing (see #257 ).

**Comment by michhri** [comment]
@wkeeling @eanon Thank you for your responses.
I tried your suggestion updating the `mode` of `driver.proxy._master.options` and it seems to work.

Thank you

**Comment by r-hou** [comment]
seems the code is updated. For your interest,
new_proxy = {
        'https': f'http://{username}:{pwd}@{host}:{port}',
        'http': f'http://{username}:{pwd}@{host}:{port}',
    }
driver.proxy = new_proxy
