### ISSUE TITLE
index_path in storage not having query params

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#12]
I want to search urls using query params.

**Comment by appunni-dishq** [comment]
OPTION requests must not be put into indexed_requests

**Comment by wkeeling** [comment]
@appunni-dishq Thanks - I thought `wait_for_request` would allow searching by query params so I will investigate and fix.

Regarding, the indexing of OPTION requests, I will raise this as a separate issue.

**Comment by appunni-dishq** [comment]
@wkeeling I think I does. Except I was getting empty response because it was an OPTION request

**Comment by wkeeling** [comment]
@appunni-dishq Ok thanks - that makes sense then. I have opened #13 to address the capturing of OPTION
