### ISSUE TITLE
" Not Secure " while browsing with selenium-wire

### ISSUE THREAD

**Issue by hobocow** [wkeeling/selenium-wire#120]
On some websites, requests cannot be made through the browser because the connection is not considered as a secure connection.

I tried installing the certificate on my computer (mac) and tried to start selenium wire with a local chrome profile too, still not working.

Same on firefox.

Any workaround ?

**Comment by wkeeling** [comment]
Thanks for raising this. What does the browser say on websites that it can't connect to - do you get a specific error message?

**Comment by hobocow** [comment]
Hi,

It's not so much about the browser itself, i can browse any websites as I would on a regular browser / selenium. But for example if I try to login on some websites, the request wouldn't get through.

An example would be this : 
https://www.nike.com/login

Working fine on regular browser/seleniuim but in selenium wire it's just an unknown error systematically.

I think its because in selenium wire there is always the " not secure " message at the top left corner of the browser ? In regular selenium i dont have that 👍

**Comment by wkeeling** [comment]
Ok thanks. The "not secure" indicator in the browser address bar indicates the browser doesn't trust Selenium Wire's root certificate, but this wouldn't normally stop you from accessing or logging into a site. 

I'll see if I can reproduce with nike.com.

**Comment by hobocow** [comment]
Thank you, that is what i thought too. 

In the mean time is there any way to make the browser trust selenium wire's certificate ?

**Comment by wkeeling** [comment]
Have you manually installed the `ca.crt` into Chrome? If you do that, Chrome should then trust the certificate and the "not secure" indicator will be replaced with a padlock icon.

**Comment by hobocow** [comment]
Yes I have tried installing it on both mac and windows, however, im not sure what you mean by install it into chrome ? 

I only installed the certificate in both system : in the key chain access app on mac os and just double clicking on windows, that should do the job ? I couldnt find anyway to install a certificate directly in chrome

**Comment by wkeeling** [comment]
Great, glad to hear it's working!

**Comment by P-Leo10** [comment]
@hobocow @wkeeling  Hi bros, I have the same problem to access https://www.nike.com.br. Could you tell me how to install ca.crt for windows? I do not even know where to begin with

**Comment by wkeeling** [comment]
@P-Leo10 The root certificate is here: https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt

Copy all the text (including the BEGIN and END lines) and save it in a new file called `ca.crt`. Then go to Chrome's settings, then to "Certificates" (you can search the settings for "Certificates"). From there locate the "Certificate Authorities" section and use the "Import" function to import the `ca.crt` file you just created.

**Comment by P-Leo10** [comment]
@wkeeling thank you very much for the help, it worked. The only problems that have not yet come out are:
-this error, `client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101`
-this error in the browser, runned with selenium-wire `ERR_PROXY_CONNECTION_FAILED` after the script execution

**Comment by wkeeling** [comment]
@P-Leo10 could you post the code that you're using to create the webdriver and the full error traceback you're seeing?

**Comment by P-Leo10** [comment]
@wkeeling 
I'm working with a larger and more complex code but I did a test with this simple code and even in this script it informs me this error in the terminal

code:

`import requests
from seleniumwire import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options

driver = webdriver.Chrome('./chromedriver')
driver.get('https://www.nike.com.br/')`

error:

`[86924:97464:0721/051946.790:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.851:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.855:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.856:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.899:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.901:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.917:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.961:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.963:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051946.977:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101
[86924:97464:0721/051947.023:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -101`

moreover, thanks to your Selenium-wire, I am trying to create a way to overcome recaptcha v3, if you can give me a means to communicate with you in a non-public way, it would be great.

**Comment by wkeeling** [comment]
It might be worth [switching the backend](https://github.com/wkeeling/selenium-wire#backends) to see if that makes a difference. Try that first, but happy to continue the conversation non-publicly if no joy.

**Comment by P-Leo10** [comment]
@wkeeling i try with
```
options  = {
     'backend' : 'mitmproxy'
}
```
but when i used this, comes back the problem with 'Not secure'.
I expressed myself wrong, I wanted to speak to you in private so as not to publish my idea publicly, I'm using the google translator so I don't know if I'm writing 100% right hahaha

**Comment by wkeeling** [comment]
Happy to chat in private: will at zifferent dot com

With switching the backend to mitmproxy, you will need to ensure that you install the mitmproxy root certificate (it is different to the `ca.crt` that you already installed). Once installed, that should make the "Not secure" message go away. You can find instructions on installing the mitmproxy certificate here: https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually

**Comment by shanebenlolo** [comment]
> @P-Leo10 The root certificate is here: https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt
> 
> Copy all the text (including the BEGIN and END lines) and save it in a new file called `ca.crt`. Then go to Chrome's settings, then to "Certificates" (you can search the settings for "Certificates"). From there locate the "Certificate Authorities" section and use the "Import" function to import the `ca.crt` file you just created.

Hey wkeeling, I tried to follow this link, as I am having the same problem as the original poster and am trying to work the issue out by adding the root certificate to chrome, but the link now appears to be dead. Do you have a working link to this file anymore? Thanks so much

**Comment by wkeeling** [comment]
@shanebenlolo Thanks for the message. The certificate has moved since that comment containing the link was posted. You should be able to download it here: https://github.com/wkeeling/selenium-wire/raw/master/seleniumwire/ca.crt (also accessible from the [Certificates section](https://github.com/wkeeling/selenium-wire#certificates) in the doc).

You can also get the certificate by running the following command:

```
python -m seleniumwire extractcert
```

**Comment by KarateKugler** [comment]
It's important to import the certificate in the "Trusted Certificates" Tab.

**Comment by Esaanjum** [comment]
> On some websites, requests cannot be made through the browser because the connection is not considered as a secure connection.
> 
> I tried installing the certificate on my computer (mac) and tried to start selenium wire with a local chrome profile too, still not working.
> 
> Same on firefox.
> 
> Any workaround ?

This is the only solution I know of:
use selenium webdriver
instead of seleniumwire webdriver

**Comment by wkeeling** [comment]
If you're using a Linux based system the certificate can also be installed from the terminal using the following command:
```bash
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "Selenium Wire" -i /path/to/ca.crt
```
Change `/path/to/ca.crt` appropriately.

If you get a "command not found" then `certutil` can be installed with:
```bash
apt install libnss3-tools
```

**Comment by reeemsalah** [comment]
> It's important to import the certificate in the "Trusted Certificates" Tab.

@KarateKugler I can't find that tab inside google chrome settings, I can only find "Trusted People" and "Trusted Publishers". I have tried importing the certificate to both tabs but still, when I try to open any website using selenium-wire, it fails to find a certificate for it.

**Comment by wkeeling** [comment]
@reeemsalah there should be a tab that looks like the following:
![image](https://user-images.githubusercontent.com/1295116/188864535-1119ccd6-a530-4d93-b340-7faeff5f1b20.png)
If you don't have that, it's possible it may have been disabled by your organisation - e.g. by a company wide security policy.

**Comment by reeemsalah** [comment]
@wkeeling Thank you so much, it worked 💯

**Comment by yeyuchen198** [comment]
seleniumwire和undetected_chromedriver，证书不安全警告问题！

解决办法，新开一个CMD窗口，输入命令：
python -m seleniumwire extractcert
就会在同级文件夹生成一个ca.crt证书文件，然后在Chrome浏览器 > 设置里面搜索证书，管理证书，在【受信任的根证书颁发机构】那一栏，导入ca.crt这个证书！这样就没有证书不安全的警告了！！

**Comment by cheezypotatoes** [comment]
@wkeeling 
![image](https://github.com/wkeeling/selenium-wire/assets/132412990/9e41091d-a458-4e1f-9cc1-4c96815329e7)
should I continue?

**Comment by cheezypotatoes** [comment]
nvm, I realize you own this package

**Comment by omid-adibfar** [comment]
> @P-Leo10 The root certificate is here: https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt
> 
> Copy all the text (including the BEGIN and END lines) and save it in a new file called `ca.crt`. Then go to Chrome's settings, then to "Certificates" (you can search the settings for "Certificates"). From there locate the "Certificate Authorities" section and use the "Import" function to import the `ca.crt` file you just created.

As an update, the link is deprecated, you can download `ca.crt` here: [https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt)

**Comment by A4Abhiraj** [comment]
Try this: 
This should extract the certificate in the dir you run this command from.
```python -m seleniumwire extractcert``` 

Open your chrome, go to `settings > privacy & security > security > manage device certificates > authorities > click import`
select the ca.crt that the previous command had generated.

**Comment by Act0r1** [comment]
> @P-Leo10 The root certificate is here: https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt
> 
> Copy all the text (including the BEGIN and END lines) and save it in a new file called `ca.crt`. Then go to Chrome's settings, then to "Certificates" (you can search the settings for "Certificates"). From there locate the "Certificate Authorities" section and use the "Import" function to import the `ca.crt` file you just created.

when i try to add it, i get  error: The Private Key for this Client Certificate is missing or invalid

**Comment by ravigadila** [comment]
@Act0r1  same issue
Got "The Private Key for this Client Certificate is missing or invalid"
when trying to import ca.crt
![Screenshot from 2023-11-15 18-54-58](https://github.com/wkeeling/selenium-wire/assets/8197942/a5b8c2d2-6e7f-40e8-84c7-712cfff2ac7c)

**Comment by Ghost6446** [comment]
Doesnt work -> Client certificate is missing or invalid

**Comment by unchaineddev** [comment]
Are you adding it in the “Trusted Root Certification Authority" section? @Ghost6446 [Try this](https://stackoverflow.com/questions/55947983/how-to-fix-certificate-import-error-the-private-key-for-this-client-certificat)

**Comment by Act0r1** [comment]
> @Act0r1  same issue
> 
> Got "The Private Key for this Client Certificate is missing or invalid"
> 
> when trying to import ca.crt
> 
> ![Screenshot from 2023-11-15 18-54-58](https://github.com/wkeeling/selenium-wire/assets/8197942/a5b8c2d2-6e7f-40e8-84c7-712cfff2ac7c)
> 
> 

First, generate the certificate - python -m seleniumwire extractcert
then install it - certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "Selenium Wire" -i /path/to/ca.crt

Maybe it will help someone
And I highly recommend just use playwrig, there no error like this

**Comment by milahu** [comment]
summary:

- the `ca.crt` file must be imported as an \*authority\* certificate:  
chrome > settings > security > manage device certificates > authorities > import
- the certificate is stored in `$HOME/.pki/nssdb/cert9.db` and `$HOME/.pki/nssdb/key4.db`.  
it is not stored in chromium's `user-data-dir`
- adding the certificate can be automated with `certutil` from [nss-tools](https://packages.debian.org/bookworm/libnss3-tools):  
`certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "Selenium Wire" -i /path/to/ca.crt`

**Comment by premrakh-vision** [comment]
the ca.crt file must be imported as an *authority* certificate:
chrome > settings > security > manage device certificates > authorities > import
-------------------------------------------------------------------------------
when I follow above step to handle Not Secure  protocol its work but these setting do manually 
I want to fix this issue via coding if possible so please answer it

**Comment by milahu** [comment]
> adding the certificate can be automated with `certutil`
