### ISSUE TITLE
Support for websockets

### ISSUE THREAD

**Issue by kostberg** [wkeeling/selenium-wire#121]
Is it possible to capture WebSocket requests with this?

**Comment by wkeeling** [comment]
The websocket handshake is captured, as in the request to upgrade the connection and then the `101 Web Socket Protocol Handshake` response. Once the upgrade has taken place, data that runs across the open websocket connection is not captured. This data would be application specific carried in websocket frames (wouldn't be broken into HTTP request/respones).
