### ISSUE TITLE
google recaptcha  v3 failure 

### ISSUE THREAD

**Issue by wuly12345** [wkeeling/selenium-wire#122]
When use seleniumwire 1.12 to access https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php,   Seleniumwire  could not get the score of v3, but the seleniumwire 1.11 was OK

**Comment by wkeeling** [comment]
This works ok for me on the latest version of Selenium Wire (v.1.2.3). I found it was necessary to put a `time.sleep()` in after the `driver.get()` to ensure that the response was received before the test finished.

```
import time
from seleniumwire import webdriver

driver = webdriver.Firefox()
driver.get('https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php')

time.sleep(10)

driver.quit()
```

Are you able to try version 1.2.3?
