### ISSUE TITLE
webdriver from seleniumwire doesnt work correctly

### ISSUE THREAD

**Issue by F1M3NRD** [wkeeling/selenium-wire#124]
Good day! 

I came here with a problem and perhaps you could give me any suggestions how to solve it in case if it's not a bug. 

So, i have a very simple test that was created by using katalon recorder (just to show what kind of issue i have): 

from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Tests(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_s(self):
        driver = self.driver
        driver.get("https://www.freemake.com/br/free_video_converter/")
        driver.find_element_by_xpath("//div[3]/div[4]/div/div/ul/li[2]").click()
        driver.find_element_by_xpath("//div[3]/div[4]/div/div/ul/li").click()
        time.sleep(10)

etc...

So, the problem is that driver can not execute a click action on this page between these two tabs:
![Screenshot_2](https://user-images.githubusercontent.com/53397237/84774042-ee621b80-afe5-11ea-86b7-a9097910947a.png)

You could say that a problem could be in elements or website or smth else but it works fine if i use webdriver from just selenium (from selenium import webdriver). 

However, i can execute click action on green button.

Another example: 

from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Tests(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_s(self):
        driver = self.driver
        driver.get("https://www.freemake.com/it/free_video_downloader/")
        driver.find_element_by_id("linkInput").send_keys("https://www.youtube.com/watch?v=pOELUuozp64")
        time.sleep(15)

If you visit this page and paste url in a relevant field it should parse video and give you some information about it or you can get an error message:
![Screenshot_6](https://user-images.githubusercontent.com/53397237/84774696-e191f780-afe6-11ea-99ba-7834d35e252d.png)

The point is that you should get some kind of reaction from this web service. Again, with common webdriver from just selenium it works fine but with webdriver from seleniumwire it doesnt work.
I tried to use a huge time.sleeps for execution (in case if it needs to load all requests) but it didnt help. 

Environment: Win 10x64, Chrome version (tried a couple 81, 83), selenium version 3.141.0, seleniumwire 1.2.2. Tried to run this code in PyCharm and CLI as well. 

Sincerely

**Comment by wkeeling** [comment]
Thanks for raising this - and for the detailed info. I suspect that a background request that comes from the click action on these pages isn't making it through Selenium Wire's embedded proxy for some reason. I'll see if I can reproduce.

**Comment by wkeeling** [comment]
@F1M3NRD after digging a little, it seems that this problem is being caused by some Javascript assets that are not being loaded. That then prevents certain functionality from working.

It seems to be related to connection keep-alive. If you switch this off in the Selenium Wire options, then the page seems to work.

```
def setUp(self):
    self.driver = webdriver.Chrome()
    options = {
         'connection_keep_alive': False,
    }
    self.driver = webdriver.Chrome(seleniumwire_options=options)
```

Connection keep-alive seems to be causing other people problems too (e.g. #113) so I'm wondering whether it would be better switched off by default. It was originally enabled by default to improve page load performance.

Let me know if you still see problems.

**Comment by F1M3NRD** [comment]
@wkeeling Thank you for your quick answer. Your tip helped me to solve the problem. Good luck with further development, your module is really helpful!
