### ISSUE TITLE
Running my Selenium Wire python script invokes 100% CPU in Atom Helper 

### ISSUE THREAD

**Issue by newscloud** [wkeeling/selenium-wire#126]
See [Atom Issue](https://github.com/atom/atom/issues/20979). 

This is 100% reproducible. As soon as I run my python3 selenium wire script, Atom Helper shoots to 100% on Activity Monitor and my machine heats up and fans run big.

Quitting Atom first and leaving it closed ... the process runs fine.

Weird.

Curious what you think it might be.

At first, I worried it might be transmitting data - but Activity Monitor is not showing data transmission from Atom. Just CPU.

**Comment by wkeeling** [comment]
Thanks for raising this. Out of curiosity do you get the same thing if you visit a http site (i.e. unencrypted)? Selenium Wire has to do extra work when decrypting https traffic, and I wonder whether it's this that is causing the CPU to shoot up.

**Comment by newscloud** [comment]
I don't have homebrew installed so all my selenium wire traffic is http.

Today, I did see Atomhelper shoot to 100% without running Selenium Wire ... so this is not 100% a Selenium Wire issue.

It does repro always when I run my selenium script.

**Comment by newscloud** [comment]
Disabling the github package appears to have resolved this.
![disable-package-github](https://user-images.githubusercontent.com/40822/88612365-e8794480-d03f-11ea-9767-a20667af2c93.gif)
