### ISSUE TITLE
wait_for_request() randomly raising TimeoutException after being resolved

### ISSUE THREAD

**Issue by esandoval99** [wkeeling/selenium-wire#127]
I'm running a script to automate the checkout on Shopify but `wait_for_request()` seems to randomly raise a `TimeoutException` in the same script during different runs.

`driver.wait_for_request("add.js", timeout=ADD_CART_WAIT)` is what I'm calling to wait for the `add.js` request to complete and is how I know that the item has been added to cart after clicking the "add to cart" button. What's strange is that this exception is raised even after `wait_for_request()` has completed successfully. It waits for `add.js`, sees the response, and the script continues to run, but midway this function raises a `TimeoutException`.

Not sure what is happening here and it's hard to reproduce since it shows up randomly but I can update this post with more info if needed.

**Comment by wkeeling** [comment]
Thanks for this. Are you able to post the traceback that you see when the `TimeoutException` occurs after the response has come back?

**Comment by esandoval99** [comment]
I should've saved the traceback but I didn't. Sorry about that, this is the first time I've opened an issue. I haven't encountered the bug since then though so maybe a selenium or chromedriver update fixed it.

**Comment by wkeeling** [comment]
OK thanks. I'll close this for now. If the issue comes back, let me know.
