### ISSUE TITLE
OPTION requests must not be indexed

### ISSUE THREAD

**Issue by wkeeling** [wkeeling/selenium-wire#13]
OPTION requests must not be put into indexed_requests or we should provide a way to filter by HTTP method on `wait_for_request()`

**Comment by appunni-dishq** [comment]
This seems like a short-term fix, for this issue. Let me know if you want me to get involved in the filter by Request method. I can pick it up.

**Comment by wkeeling** [comment]
@appunni-dishq this issue has been fixed in 3.9.0. OPTIONS requests are now filtered out by default, and additional HTTP method filtering can be configured in selenium wire's config. More info [here](https://github.com/wkeeling/selenium-wire#misc-options).

Thank you for raising the issue!

**Comment by appunni-dishq** [comment]
@wkeeling Thank you for resolving it so fast
