### ISSUE TITLE
Can't use selenium-wire inside AWS lambda

### ISSUE THREAD

**Issue by vigneshrams** [wkeeling/selenium-wire#131]
Trying to use Selenium-wire inside AWS lambda. But it fails with the following error.

> OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'

Hope selenium-wire try to write some file to disk while calling,
`driver = webdriver.Chrome(executable_path="/var/task/driver/chromedriver",chrome_options=chrome_options)`

Help me with this issue

**Comment by wkeeling** [comment]
Try specifying a different location for selenium wire's [temporary storage directory](https://github.com/wkeeling/selenium-wire#other-options).

```
options = {
    'request_storage_base_dir': '/tmp'  # Use /tmp to store captured data
}

driver = webdriver.Chrome(
    executable_path="/var/task/driver/chromedriver",
    chrome_options=chrome_options,
    seleniumwire_options=options
)
```

**Comment by vigneshrams** [comment]
Thanks to @wkeeling. It worked. I was using Selenium with headless chrome in Python.

How do you return status code for URL visited using Headless-Chrome?  Do you make an inbuild requests call or some other method?

./Thanks

**Comment by wkeeling** [comment]
You can obtain the status code using the `status_code` attribute on the `response`. It should make no difference whether you are using headless Chrome or not:

```
for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
        )
```

**Comment by Pheels** [comment]
Apologies to dig up an old issue but I am struggling to get selenium-wire working in a lambda function myself.

The common wisdom dictates that chromedriver v2.37 & v2.41 are the most stable for usage alongside headless-chrome and selenium ([source](https://stackoverflow.com/a/66594707)), however selenium-wire does not support these versions ([source](https://github.com/wkeeling/selenium-wire/issues/271#issuecomment-823543757))

Any advice on how to proceed is greatly appreciated, I have tried many different versions to no avail.

**Comment by wkeeling** [comment]
@Pheels the issue with the older chromedriver (v2.41) is that the API for specifying capabilities (specifically the `noProxy` option that gets passed behind the scenes) is slightly different to later versions and that causes the compatibility problem with Selenium Wire. You may be able to work around it by explicitly passing a string for the `exclude_hosts` option though - e.g.

```python
options = {
    'exclude_hosts': ''
}

webdriver = ChromeDriver(
    seleniumwire_options=options
)
```
I've created #342 to address this issue properly.

**Comment by Pheels** [comment]
Thanks @wkeeling, explicitly passing the string has indeed fixed the issue.

I will raise a PR for #342 if you do not plan to already.

**Comment by karthiksml** [comment]
> Try specifying a different location for selenium wire's [temporary storage directory](https://github.com/wkeeling/selenium-wire#all-options).
> 
> ```
> options = {
>     'request_storage_base_dir': '/tmp'  # Use /tmp to store captured data
> }
> 
> driver = webdriver.Chrome(
>     executable_path="/var/task/driver/chromedriver",
>     chrome_options=chrome_options,
>     seleniumwire_options=options
> )
> ```

I get this issue even after adding the options = {'request_storage_base_dir' : '/tmp'}. I'm using Python3.7. can you help me here.
{
  "errorMessage": "[Errno 30] Read-only file system: '/home/sbx_user1051'",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 12, in lambda_handler\n    driver= webdriver.Chrome(executable_path=\"/opt/chromedriver\", chrome_options=chrome_options, seleniumwire_options=options)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py\", line 69, in __init__\n    options=seleniumwire_options\n",
    "  File \"/opt/python/lib/python3.7/site-packages/seleniumwire/proxy/client.py\", line 54, in create_proxy\n    proxy_config=proxy_config, options=options)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/seleniumwire/proxy/server.py\", line 15, in __init__\n    self.storage = RequestStorage()\n",
    "  File \"/opt/python/lib/python3.7/site-packages/seleniumwire/proxy/storage.py\", line 37, in __init__\n    os.makedirs(self._storage_dir)\n",
    "  File \"/var/lang/lib/python3.7/os.py\", line 213, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n",
    "  File \"/var/lang/lib/python3.7/os.py\", line 213, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n",
    "  File \"/var/lang/lib/python3.7/os.py\", line 223, in makedirs\n    mkdir(name, mode)\n"
  ]
}

**Comment by wkeeling** [comment]
@karthiksml it seems as though the config hasn't taken effect, since the error is still pointing at /home/sbx_user1051. 

Can you check that you have definitely spelt the request_storage_base_dir correctly and also check that you are definitely using the updated code in your lambda function.

**Comment by abdu997** [comment]
@karthiksml I added the `request_storage_base_dir'` option, but the issue still persists for me

```
hrome_options = Options()
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--start-maximized')
    chrome_options.add_argument('--start-fullscreen')
    chrome_options.add_argument('--single-process')
    chrome_options.add_argument('--disable-dev-shm-usage')

    return webdriver.Chrome(
        options=chrome_options, 
        service=Service(ChromeDriverManager().install()),
        seleniumwire_options={'request_storage_base_dir': '/tmp'}
    )
   ```

And I'm still getting the same exact error you're getting, did you figure out how to solve it?

**Comment by Pheels** [comment]
The following works for me, inside a lambda function:
```
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--no-cache')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--window-size=1024x768')
chrome_options.add_argument('--user-data-dir=/tmp/user-data')
chrome_options.add_argument('--hide-scrollbars')
chrome_options.add_argument('--enable-logging')
chrome_options.add_argument('--log-level=0')
chrome_options.add_argument('--v=99')
chrome_options.add_argument('--single-process')
chrome_options.add_argument('--data-path=/tmp/data-path')
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--homedir=/tmp')
chrome_options.add_argument('--disk-cache-dir=/tmp/cache-dir')
chrome_options.add_argument('user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36')
chrome_options.headless = True
selenium_options = {
    'request_storage_base_dir': '/tmp', # Use /tmp to store captured data
     'exclude_hosts': ''
}
chrome_options.binary_location = '/opt/headless-chromium'
driver = webdriver.Chrome('/opt/chromedriver', chrome_options=chrome_options, seleniumwire_options=selenium_options)

```

**Comment by ksayet** [comment]
> The following works for me, inside a lambda function:
> 
> ```
> chrome_options = webdriver.ChromeOptions()
> chrome_options.add_argument('--headless')
> chrome_options.add_argument('--disable-dev-shm-usage')
> chrome_options.add_argument('--disable-extensions')
> chrome_options.add_argument('--no-sandbox')
> chrome_options.add_argument('--no-cache')
> chrome_options.add_argument('--disable-gpu')
> chrome_options.add_argument('--window-size=1024x768')
> chrome_options.add_argument('--user-data-dir=/tmp/user-data')
> chrome_options.add_argument('--hide-scrollbars')
> chrome_options.add_argument('--enable-logging')
> chrome_options.add_argument('--log-level=0')
> chrome_options.add_argument('--v=99')
> chrome_options.add_argument('--single-process')
> chrome_options.add_argument('--data-path=/tmp/data-path')
> chrome_options.add_argument('--ignore-certificate-errors')
> chrome_options.add_argument('--homedir=/tmp')
> chrome_options.add_argument('--disk-cache-dir=/tmp/cache-dir')
> chrome_options.add_argument('user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36')
> chrome_options.headless = True
> selenium_options = {
>     'request_storage_base_dir': '/tmp', # Use /tmp to store captured data
>      'exclude_hosts': ''
> }
> chrome_options.binary_location = '/opt/headless-chromium'
> driver = webdriver.Chrome('/opt/chromedriver', chrome_options=chrome_options, seleniumwire_options=selenium_options)
> ```

Thanks for this. This was the only way I was able to get it to work in a lambda function however it seems that the `single-process` option is causing some websites to detect seleniumwire as robot activity. Without that option included, seleniumwire does not run in lambda. Do you have any suggestions on how I can get seleniumwire to run in Lambda without single-process?

@wkeeling @Pheels  Thank you SO much for your help thus far!
