### ISSUE TITLE
Error in WebSocket when running mitmproxy backend

### ISSUE THREAD

**Issue by trhgnhat** [wkeeling/selenium-wire#139]
Hi all, i am trying to use new backend mitmproxy  and keep getting this error.
```
Error in WebSocket connection to mpsnare.iesnare.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None,)
Error in WebSocket connection to mpsnare.iesnare.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None,)
Error in WebSocket connection to mpsnare.iesnare.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None,)
Error in WebSocket connection to mpsnare.iesnare.com:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None,)
Error starting proxy server: OSError(98, 'Address already in use')
```
Is there any way to handle this gracefully? (or even a way to catch it and renew driver session somehow?) 
Thank you.

**Comment by wkeeling** [comment]
It looks as though the port number is already in use. Can you try using a different port:

```
options = {
    'port': 9999  # Tell the backend to listen on port 9999
}
driver = webdriver.Firefox(seleniumwire_options=options)  # can also use Chrome
```

**Comment by trhgnhat** [comment]
@wkeeling thank you for your support. However, it didn't work well neither. So, i came back with the old backend and is stuck with this error:
```
File "/home/nhat.truong/thnhat/CrawlingProj/env/lib64/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/nhat.truong/thnhat/CrawlingProj/env/lib64/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```
It randomly appear and crash my app. Is there any idea to solve this? I tried to catch this error also but seem like i put the wrong location for the try-catch.
Here is my selenium_wire options
```
swire_ops = {
    'connection_timeout': 120,
    'connection_keep_alive': False
}
```

**Comment by wkeeling** [comment]
You could perhaps try `connection_timeout: None` in your swire_opts which will tell selenium Wire go never timeout. 

Switching the backend to mitmproxy may be the best solution as it handles this situation better in my experience (slow upstream servers). Did you not manage to resolve the issue with the "Address already in use"? That looked like a simple port number issue.

**Comment by wkeeling** [comment]
@trhgnhat are you running in a multithreaded environment with the mitmproxy backend? The error `Address already in use` will happen if multiple threads try and create a new webdriver instance because each instance will use the same port.

**Comment by trhgnhat** [comment]
Yes, i am running multithreads. However, i couldn't solve that problem so i came back with the old backend and my app is currently running.

**Comment by wkeeling** [comment]
Ok, thanks. So you managed to solve `socket.timeout: timed out`?

**Comment by trhgnhat** [comment]
It still appear sometimes. But i skipped it by a lot of try-catch and kill session (which is waiting for too long).
