### ISSUE TITLE
How to handle redirects with selenium-wire?

### ISSUE THREAD

**Issue by vigneshrams** [wkeeling/selenium-wire#141]
When I try to scrape [http://github.com/](url) with python request the redirect is handled automatically. Whereas with chrome and selenium-wire it gets timeout error. Any idea on how to handle it?

./Thanks

**Comment by wkeeling** [comment]
The browser handles the redirect, rather than Selenium Wire itself. I suspect the timeout is happening due to a problem with the subsequent https request. As you using an upstream proxy server?

**Comment by vigneshrams** [comment]
Yes, I am using a proxy for my request. Do you think that might be causing the timeout?

**Comment by wkeeling** [comment]
It could be. Can you try [switching the backend](https://github.com/wkeeling/selenium-wire#backends) to mitmproxy and see whether you still see the issue. That would help us rule out the proxy server.

**Comment by wkeeling** [comment]
@vigneshrams did you get any further with this?
