### ISSUE TITLE
How to get POST data and not parameters?

### ISSUE THREAD

**Issue by Bool13** [wkeeling/selenium-wire#144]
requests = driver.requests
Returns all the data needed. Url, parameters but does not return data that is transmitted by the post.

**Comment by wkeeling** [comment]
Once you have located the relevant request in `driver.requests` you should be able to retrieve the post data from `request.body`. Have you tried this?

**Comment by Bool13** [comment]
Contains no data. A link to a request that, when requested, tries to receive data but in response to an exception. Connection is not established, because destination computer rejected the connection request

**Comment by wkeeling** [comment]
In that case I would expect the `request.response` to be `None`, but the `request.body` should still have been captured. Is the particular  URL publicly available? Be good to reproduce in order to see where it's going wrong. If not, I should be able to simulate something easily enough.

**Comment by Bool13** [comment]
During operation, the request is sent normally. I ran it through a local server. But it is in debugging requests that the body is not data. I think he cannot receive data after contacting because of the same error as with people. When any browser action is reset and there is no connection. body already contains an exception.

**Comment by Bool13** [comment]
All requests contain an error in the body.

**Comment by Bool13** [comment]
I tried on any other address and got the same error in the body.

**Comment by wkeeling** [comment]
Can you post the code you're using, including any options and I'll try and reproduce.

**Comment by Bool13** [comment]
from seleniumwire import webdriver
proxy = ('https://127.0.0.1:8080')
options = {
    'proxy': {
        'http': proxy[0],
        'https': proxy[0],
        'no_proxy': 'localhost,127.0.0.1'
    },
    'verify_ssl': False  
}

chrome = webdriver.Chrome(seleniumwire_options=options)
chrome.get("https://nominatim.openstreetmap.org/")
requests = chrome.requests
chrome.quit()
for request in requests:
    if 'POST' == request.method:
        print(request.body)

**Comment by wkeeling** [comment]
I think I see the issue. The problem happens because you call `chrome.quit()` before you access `request.body`. The request body is retrieved lazily for performance reasons. This means that Selenium Wire needs to be running at the point you access `request.body`. However the `chrome.quit()` call will shutdown Selenium Wire. 

Try moving the call to `chrome.quit()` to the end:


```
chrome = webdriver.Chrome(seleniumwire_options=options)
chrome.get("https://nominatim.openstreetmap.org/")
requests = chrome.requests
for request in requests:
    if 'POST' == request.method:
        print(request.body)
chrome.quit()
```

**Comment by Bool13** [comment]
Everything worked out. Thank.

**Comment by Bool13** [comment]
Re-downloading the request to POST with what headers?

**Comment by wkeeling** [comment]
@Bool13 I'm not sure I understand. Can you explain the question?

**Comment by Bool13** [comment]
When I receive all requests from the browser, it re-accesses the addresses and receives the content. What connection parameters does it use? Or are all requests stored locally?

**Comment by wkeeling** [comment]
When you ask for the requests using `driver.requests`, Selenium Wire makes a HTTP request to the underlying proxy server to retrieve the captured requests from disk. The HTTP request is in the form `http://seleniumwire/requests`. The proxy server sees the  `seleniumwire` hostname and handles the request as an admin request, and does not proxy it. 

See [the request mappings](https://github.com/wkeeling/selenium-wire/blob/ac647375fa175f34db493f1ed86fa2a6bc98f9a1/seleniumwire/proxy/handler.py#L32) for how the different types of admin requests are handled.
