### ISSUE TITLE
gevent monkey error greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by Bool13** [wkeeling/selenium-wire#145]
Please add these lines to your _socket3.py.
from gevent import monkey as curious_george
curious_george.patch_all (thread = False, select = False)
The problem I am having is that you are calling gevent not patched. And I call him after you. There is a problem with threads. You need to patch it.

**Comment by wkeeling** [comment]
The core of Selenium Wire has been significantly reworked since this issue was reported. Threads are still used, but request handling now makes use of asyncio. Closing this issue, but will re-open if necessary.
