### ISSUE TITLE
socket.timeout: _ssl.c:1059: The handshake operation timed out

### ISSUE THREAD

**Issue by Imran109** [wkeeling/selenium-wire#147]
**Whenever I open any website using get, the next moment I am getting this error and its so annoying because the browser just stops loading!**
Traceback (most recent call last):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
    super().connect()
  File "/Users/opt/anaconda3/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/Users/opt/anaconda3/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Users/opt/anaconda3/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Users/opt/anaconda3/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1059: The handshake operation timed out

**Comment by wkeeling** [comment]
Thanks for the issue. Could you post your code including any options you're passing to the webdriver instance. Also, what version of Selenium Wire are you using?

**Comment by Imran109** [comment]
@wkeeling 
Name: selenium-wire
Version: 2.1.0
Summary: Extends Selenium to give you the ability to inspect requests made by the browser.
Home-page: https://github.com/wkeeling/selenium-wire
Author: Will Keeling
Author-email: will@zifferent.com
License: MIT
```
from selenium.webdriver.chrome.options import Options  
chrome_options = Options()
chrome_options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
driver = webdriver.Chrome(executable_path = os.path.abspath("drivers/chromedriver"), chrome_options = chrome_options)
```
I was using the same arguments only all these days. Today only I am facing with this issue

**Comment by Imran109** [comment]
@wkeeling When this issue will be resolved. Because we are trying to use this in production level and it causes failure!

**Comment by wkeeling** [comment]
If this had previously been working and has stopped working, and nothing has changed in your environment, then I can only assume there is some issue with the remote site you are connecting to? The error seems to be an SSL handshake timing out. Can you access the same URL if you just use Selenium itself?

**Comment by wkeeling** [comment]
@Imran109 one other thing to try - try increasing the timeout:

```
from selenium.webdriver.chrome.options import Options  
chrome_options = Options()
chrome_options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

sw_options = {
    'connection_timeout': 60
}

driver = webdriver.Chrome(
    executable_path=os.path.abspath("drivers/chromedriver"), 
    chrome_options=chrome_options,
    seleniumwire_options=sw_options
)
```

**Comment by Imran109** [comment]
@wkeeling Tried this. If I set the connection timeout the page simply keeps loading and times out eventually.

**Comment by wkeeling** [comment]
Do you see timeouts if you [switch the backend](https://github.com/wkeeling/selenium-wire#backends) to mitmproxy?

**Comment by Imran109** [comment]
@wkeeling I tried with normal selenium. It's working as expected without any errors. I was doing the same task only for the past one week, suddenly I face this issue these two days.

**Comment by wkeeling** [comment]
@Imran109 is the site publicly accessible? If I can reproduce I can try to debug.

Switching the mitmproxy backend is a workaround which may get you past the problem.

**Comment by Imran109** [comment]
@wkeeling Yes, its just Instagram. Try to login into the page using selenium wire

**Comment by wkeeling** [comment]
Ok thanks will try and reproduce.

**Comment by Imran109** [comment]
@wkeeling Or, could you help me how I can achieve the same using mitmproxy. What I want to do is, get a particular request header, get the response of it and store it in a json or any format while inside selenium.

**Comment by wkeeling** [comment]
Yes you can do that with the mitmproxy backend. 

To switch the backend, first install mitmproxy: 

```
pip install mitmproxy
```

Then specify the backend in the options you pass to the webdriver:

```
from selenium.webdriver.chrome.options import Options  
chrome_options = Options()
chrome_options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

sw_options = {
    'backend': 'mitmproxy'
}

driver = webdriver.Chrome(
    executable_path=os.path.abspath("drivers/chromedriver"), 
    chrome_options=chrome_options,
    seleniumwire_options=sw_options
)
```

You can then load the page:

```
driver.get(...)
```

Retrieve the request you are interested in, e.g the last request captured:

```
request = driver.last_request
```
(Or perhaps locate the request with `request = driver.wait_for_request('http://myserver.com/some/path?foo=bar')`.)

Store the header you require together with the response:

```
header, response =  request.headers['Some-Header'], request.response
```

**Comment by Imran109** [comment]
@wkeeling Worked like a charm and errors gone! You da best!!

**Comment by wkeeling** [comment]
Can you post the traceback you see when using mitmproxy.

**Comment by wkeeling** [comment]
Some further investigation on this indicates that the timeouts may be down to OpenSSL which `ssl.py` uses under the covers. Can you post the version of OpenSSL you are using:

```
openssl version
```

I am using version `OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.1  11 Sep 2018)`. I have not experienced any timeout issues with this version.

**Comment by JasonCrowe** [comment]
I am getting some socket.timeout issues with LibreSSL 2.8.3. I don't know if it's connected, but I thought it can't hurt to share the info.

**Comment by JasonCrowe** [comment]
I have the same script running on another computer with the same ssl version and no issues.

**Comment by regisfrais** [comment]
I have the same problem, many times I get this message, sometimes the application stops, I tried to catch the exception of the request but without success, I believe it is a problem with SSL, the version I'm running here is _LibreSSL 2.2.7_

**Comment by wkeeling** [comment]
@JasonCrowe @regisfrais thanks for the info. I'll see if I can reproduce using LibreSSL. What OS are you using?

**Comment by regisfrais** [comment]
For development and testing I use macOS High Sierra 10.13.6, but I get the same error message on a Windows Server 2012 machine installed with all the latest updates available through the datacenter.

**Comment by JasonCrowe** [comment]
MacOS python 3.6 - No issues
MacOS python 3.8 - Doesn't work

**Comment by JasonCrowe** [comment]
Is there any other information I can provide?

**Comment by wkeeling** [comment]
@JasonCrowe apologies for the delay on this - I'm a little stumped. It might be useful to know whether you get the same issue if you switch to the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends) on the machine that has the problem. That might yield some further clues.

To switch, first install mitmproxy:
```
pip install mitmproxy
```
and then specify the backend in the options you pass to the webdriver:

```
options = {
    'backend': 'mitmproxy'
}
driver = webdriver.Firefox(seleniumwire_options=options)  # Or Chrome
```

**Comment by JasonCrowe** [comment]
When I switch to mitmproxy, I no longer have the issue.

Also, when I use the default, it appears to work. The browser goes through the steps it's supposed to without any visible browser issues. BUT... My logfile is a bloodbath of red.

I'll use mitmproxy as a workaround. Thanks for the suggestion.

**Comment by wkeeling** [comment]
The core of Selenium Wire has recently been reworked to improve connection handling with upstream proxies. If you are using an older version of Selenium Wire and are still experiencing issues, try upgrading to the latest version.
