### ISSUE TITLE
SOCKS5 auth w/ only USERNAME, pw is blank | ERR_EMPTY_RESPONSE/Network unreachable 

### ISSUE THREAD

**Issue by regisfrais** [wkeeling/selenium-wire#149]
I am getting some error messages when I try to authenticate my proxy using SOCKS5, the authentication of my proxy is done using only USERNAME with the BLANK PASSWORD, when I run GET on any website it returns the error page "ERR_EMPTY_RESPONSE", I will leave my example of use for reproduction together with the execution log of my application.

I believe that he is not doing the correct authentication, sitting my user with a BLANK PASSWORD, or apparently he is not setting the settings directly in the browser.

```
import logging
from seleniumwire import webdriver

logging.basicConfig(level=logging.DEBUG)

options = {
    'proxy': {
        'http': 'socks5://myauthuser:@23.19.227.39:9800',
        'https': 'socks5://myauthuser:@23.19.227.39:9800',
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Chrome(seleniumwire_options=options)
driver.get("https://www.check2ip.com/")
```

> DEBUG:seleniumwire.proxy.handler:http://seleniumwire/initialise 200
> INFO:seleniumwire.proxy.client:Created proxy listening on 127.0.0.1:58651
> DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58653/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:58651", "sslProxy": "127.0.0.1:58651", "noProxy": ""}, "acceptInsecureCerts": true}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:58651", "sslProxy": "127.0.0.1:58651", "noProxy": ""}, "acceptInsecureCerts": true}}
> DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:58653
> DEBUG:urllib3.connectionpool:http://127.0.0.1:58653 "POST /session HTTP/1.1" 200 818
> DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
> DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58653/session/a4d8000b05b566784fa600796b8283fa/url {"url": "https://www.check2ip.com/"}
> DEBUG:seleniumwire.proxy.handler:www.check2ip.com:443 200
> DEBUG:seleniumwire.proxy.handler:www.check2ip.com:443 200
> DEBUG:seleniumwire.proxy.handler:accounts.google.com:443 200
> INFO:seleniumwire.proxy.handler:Capturing request: https://www.check2ip.com/
> DEBUG:seleniumwire.proxy.handler:www.gstatic.com:443 200
> INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
> ERROR:seleniumwire.proxy.handler:Error making request
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 816, in connect
>     negotiate(self, dest_addr, dest_port)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 450, in _negotiate_SOCKS5
>     self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 540, in _SOCKS5_request
>     raise SOCKS5Error("{:#04x}: {}".format(status, error))
> seleniumwire.proxy.socks.SOCKS5Error: 0x03: Network unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
>     conn.request(self.command, path, req_body, dict(req.headers))
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
>     self.connect()
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/proxy2.py", line 360, in connect
>     self.sock = _socks_connection(
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/proxy2.py", line 409, in _socks_connection
>     return socks.create_connection(
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 213, in create_connection
>     raise err
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 203, in create_connection
>     sock.connect((remote_host, remote_port))
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 46, in wrapper
>     return function(*args, **kwargs)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seleniumwire/proxy/socks.py", line 821, in connect
>     raise GeneralProxyError("Socket error", error)
> seleniumwire.proxy.socks.GeneralProxyError: Socket error: 0x03: Network unreachable
> INFO:seleniumwire.proxy.handler:Capturing request: https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin
> DEBUG:urllib3.connectionpool:http://127.0.0.1:58653 "POST /session/a4d8000b05b566784fa600796b8283fa/url HTTP/1.1" 200 14
> DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by wkeeling** [comment]
An empty password - when just a username and colon are specified - was preventing the auth credentials from being passed upstream. This has now been fixed and will be available in the next release.
