### ISSUE TITLE
Multiple users running Selenium-wire at the same time leads to permission collision

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#15]
Since selenium-wire stores all request data at /tmp/selenium-wire by default. Multiple users running selenium-wire runs into permission issues.
OS: Ubunutu 16.04
Selenium-wire verions: 0.7.0

**Comment by wkeeling** [comment]
@appunni-dishq - thanks for flagging this.

It sounds like it would make more sense for selenium-wire to store its requests on a per-user basis in each user's home folder - e.g. `/home/<user>/.selenium-wire`. This would then prevent permissions issues such as this.

I'll look into resolving this one asap.

**Comment by wkeeling** [comment]
@appunni-dishq This issue has been fixed in 0.9.0. Selenium wire now uses the current user's home folder for its temporary storage.

Many thanks for reporting this.
