### ISSUE TITLE
doesn't override headers with webdriver.remote, only works with local webdriver like chrome or firefox.

### ISSUE THREAD

**Issue by memm44** [wkeeling/selenium-wire#151]
Hello folks, I'm needing to selenium-wire to overrides header but it doesn't work in selenium hub, only works at local webdriver, can you help me to find an alternative solution? 
```
driver.header_overrides = {
    'New-Header1': 'Some Value',
    'New-Header2': 'Some Value'
}
```
that code only works at local but I need to work using Chrome and firefox webdriver but not Chrome in docker in this case webdriver.Remote, show no errors but not do X-forwarded for I need in this case for set another ip different country. behave i spect, checking like another country, running as local its ok, it check webpage like I would be in mexico. but using webdriver.remote doesn't. 
```
self.browser = webdriver.Remote("http://172.12.0.5:4444/wd/hub", options=options,
                                                desired_capabilities=self.cap)
self.browser.header_overrides = [(
                    '.*mydomain.com.*', {
                        'x-forwarded-for': "someothercountryip"
                    }
                )]
```
that have no effect and still with my local ip, but like I said before, as local work like a charm, the check run like I be in mexico for instance if I configure an ip belong to it.
Thanks.

**Comment by wkeeling** [comment]
I'm afraid Selenium Wire doesn't work with Selenium's remote webdriver at the present time. That is something we're looking into providing support for in the future.
