### ISSUE TITLE
[Feature Request] modify response's body 

### ISSUE THREAD

**Issue by vikingliu** [wkeeling/selenium-wire#156]
def modify_response_handler(response):
       # modify response body
        
driver.reponse_overrides = [(url_pattern, modify_response_handler)]

**Comment by vikingliu** [comment]
I want to modify the response's body before the browser use it.
I find there is no way to do this.  
can you provide this feature. thanks.

**Comment by wkeeling** [comment]
Thanks for raising this. It actually is possible to modify a response body, but it's not very clear in the documentation. You can modify a response body using the `custom_response_handler` option:

```
def custom(req, req_body, res, res_body):
    res_body = b'Hello World!'  # Be sure to use bytes for the modified body
    return res_body  # Always return the modified body

options = {
    'custom_response_handler': custom  # Set the handler
}
drv = webdriver.Firefox(seleniumwire_options=options)
drv.get('https://www.python.org')
```

The `custom_response_handler` gives you a lot of control. The example above will change the response body for all responses, but you can conditionally modify a response body by checking the attributes of the `req` (e.g. only modify a body for certain request paths). When you modify a body, you just need to make sure that the modified body is bytes and that you return the body from the custom response handler function, as shown above.

**Comment by linxuhong** [comment]
hi , which verion has this option  i use    selenium-wire        5.1.0 ,bu not found this option
 'custom_response_handler':
