### ISSUE TITLE
How block a request before forwarding to the destination server?

### ISSUE THREAD

**Issue by spinlud** [wkeeling/selenium-wire#159]
Hi, thanks for the great package!

Once a request is captured by the selenium-wire proxy, is it possible to block it before forwarding to the destination server?

**Comment by wkeeling** [comment]
Thanks for the raising this. Unfortunately, there's no way currently to block outbound requests before sending them on. Selenium Wire does give you the ability to block requests by method (GET, POST) and also rewrite URLs - which could be used to send requests into a black hole, but not the ability to send them on after blocking

This is perhaps something we could look at adding, since we already have a [custom response handler](https://github.com/wkeeling/selenium-wire#all-options). Adding a custom request handler would make sense and would enable you to perform blocking/request inspection/forwarding etc.

**Comment by spinlud** [comment]
Yes, it would be useful! 
One common pattern is to block requests for css, images and other media not needed during scraping

**Comment by wkeeling** [comment]
If you want to block media not needed you could potentially rewrite those URLs to a non-existent host - e.g. to block outbound css requests:

```
driver.rewrite_rules = [
    (r'.*\.css$', 'https://localhost:9876/'),
]
```
(Assuming that nothing is listening on port 9876.)

**Comment by dfurmanov** [comment]
Just want to give this issue a bump up. I'd love to have an ability to block outbound requests.

Also, the method described above i.e redirecting requests to a non-existent host produces a lot of errors

**Comment by wkeeling** [comment]
@dfurmanov thanks for the comment. In terms of the requests you'd like to block, are you looking to block certain media types - e.g. .css, .js etc, or are you looking to block by requests to particular domains? Be good to get as much info as possible. It sounds like this could be a useful feature.

**Comment by dfurmanov** [comment]
@wkeeling I'd like to be able to block any kind of outbound requests, if possible. 
Potentially this could be done via request interception, similar to [Puppeteer](https://theheadless.dev/posts/request-interception/).

Pseudocode:
```
def interception(req):
   if req.url.endswith('.jpg'):
      req.abort()
   else:
      req.continue()

driver.setRequestInterceptor(interception)
```

**Comment by wkeeling** [comment]
@spinlud @dfurmanov There's a new version of Selenium Wire available (v3.0.0) which introduces [request interceptors](https://github.com/wkeeling/selenium-wire#intercepting-requests-and-responses) and a new method `request.abort()`. Blocking images can now be achieved with:

```
def interceptor(request):
    # Block PNG, JPEG and GIF images
    if request.path.endswith(('.png', '.jpg', '.gif')):
        request.abort()

driver.request_interceptor = interceptor

# Requests for PNG, JPEG and GIF images will result in a 403 Forbidden
```
If you have a chance to give it a try, it'd be great to have some feedback (good and bad). I'll close this issue for the time being, but feel free to post any comments.

**Comment by dfurmanov** [comment]
@wkeeling Thanks a lot for introducing request interceptors! 
I am wondering if an outbound request ever hits the remote server when aborted? In my use case I am utilizing a third party proxy provider (rotating IPs) and I am trying to limit outbound requests, abort loading images/videos/etc as I am being charged per request and I only care about textual information on the page.

**Comment by wkeeling** [comment]
@dfurmanov the requests are effectively prevented from travelling any further when they are aborted and Selenium Wire sends back an immediate response to the browser (a 403 by default). So the requests won't make it as far as the third party proxy server. The only thing to be aware of is how you identify images/videos etc. It may be that you can rely on the file extension, like in the example above, but in other cases where the file extension isn't exposed, you may have to identify such requests by the URL path.
