### ISSUE TITLE
How to disable request and response file capture option?

### ISSUE THREAD

**Issue by indiejohnny** [wkeeling/selenium-wire#160]
Hi there. 

Are there any option to disable the request storage?

For example:
`
options = {
    'save_request_response': True/False 
}
`

**Comment by wkeeling** [comment]
Hi,
There's no single option to disable the request storage at the present time, but you can prevent requests from being captured (and thus stored) by [scoping requests](https://github.com/wkeeling/selenium-wire#scoping-request-capture) or alternatively by using the [ignore_http_methods option](https://github.com/wkeeling/selenium-wire#all-options). But even if requests aren't being saved to disk, Selenium Wire will still need to use the request storage area for generating SSL certificates.

Do you have some kind of restriction where you need to disable writing to disk?

**Comment by indiejohnny** [comment]
I don't have any restrictions but I have disk capacity issues. Some time later, "/.seleniumwire" folder uses too much space since it holds every request and response. I wonder are you going to add any feature that it deletes the created folders automatically.

**Comment by wkeeling** [comment]
The seleniumwire folder should be cleared out when Selenium Wire shuts down (at the end of the test or program execution). Are you finding that's not happening?

**Comment by indiejohnny** [comment]
I'm using Selenium Wire inside a docker container. Maybe my usage is different but it is not clearing the seleniumwire folder when I stop the container.

**Comment by wkeeling** [comment]
Before you stop the container, does your code call `driver.quit()`? This call will ensure that the storage is cleaned up. You'll need to ensure that the call completely finishes before the container is stopped.

**Comment by indiejohnny** [comment]
Actually after every request, I call `driver.quit()`. Apparently it doesn't deletes the folders.

**Comment by indiejohnny** [comment]
I checked my code, I'm calling `driver.quit()` yet it is not deleting the folder. So I use `del driver.requests` to delete files in the folder. It's a workaround but it is working.

**Comment by wkeeling** [comment]
Version 4.2.0 includes a new option `disable_capture`. When this is set, traffic will be passed straight through without being decrypted and captured.

**Comment by Bool13** [comment]
How can I change this option online?

**Comment by wkeeling** [comment]
@Bool13 Can you clarify, not sure what you mean by online?

Selenium Wire also supports [in-memory storage](https://github.com/wkeeling/selenium-wire/in-memory-storage) which won't persist requests and responses on disk. You can also limit the number of requests it will store.

**Comment by Bool13** [comment]
After initializing the driver and opening the page, turn off storage. After a while, turn it on without restarting the browser.

**Comment by wkeeling** [comment]
You should be able to use `driver.scopes = ['$^']`. For example:

```
driver.get(...)  # open a page

driver.scopes = ['$^']  # turn off storage

# do some stuff

driver.scopes = []  # turn on storage

# do some more stuff
```

Setting driver.scopes to  `['$^']` simply stops requests from being captured.
