### ISSUE TITLE
OpenSSL  doesn't work correctly

### ISSUE THREAD

**Issue by andronpl9** [wkeeling/selenium-wire#165]
Hi
I have a problem, webdrivers return "unsecured connection".
With any settings, with or without a proxy. Returns no errors.
At the same time selenium works correctly

**Comment by wkeeling** [comment]
Have you tried [installing Selenium Wire's root certificate](https://github.com/wkeeling/selenium-wire#certificates) in your browser?

**Comment by wkeeling** [comment]
@andronpl9 is this still causing a problem for you?
