### ISSUE TITLE
Is there a way to extract the times of the requests made?

### ISSUE THREAD

**Issue by alex4200** [wkeeling/selenium-wire#176]
I am using `selenium-wire` 2.1.2 to record all requests made by a browser when a user opens some URL in the browser. 

I get the list of requests made, but is there a way to extract also the timing information of these requests, i.e. at which time each request has been made?

**Comment by wkeeling** [comment]
Currently the time each request is made is not captured, although this would be relatively straightforward to add. We could perhaps capture the time the request was made and also the time when the response returned. I'll look at adding in the next release. 

Thanks for raising.

**Comment by alex4200** [comment]
Added PR https://github.com/wkeeling/selenium-wire/pull/181

**Comment by wkeeling** [comment]
Request and response objects now include a `date` attribute which holds the date/time they were made. Available in v3.0.0

**Comment by alex4200** [comment]
Thanks a lot!
