### ISSUE TITLE
'Remote' not implmented in browser.py

### ISSUE THREAD

**Issue by acidbotmaker** [wkeeling/selenium-wire#177]
With current version we can't use webdriver.Remote with `seleniumwire_options`.

When trying to use webdriver.Remote(command_executor="http://localhost:4444/wd/hub", seleniumwire_options=options)
we get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'seleniumwire_options'
```

**Comment by ErrorInPersona** [comment]
From the readme.md: 

> Selenium Wire will currently work with tests that run on the same machine as the browser. A distributed setup using Selenium Grid is not yet supported.

You will have to create an own remote driver and fit it to your requirements.

**Comment by wkeeling** [comment]
There is support for the [remote webdriver client](https://github.com/wkeeling/selenium-wire/tree/redesign_request_modification#creating-the-webdriver) in Selenium Wire v3.0.0

**Comment by erm3nda** [comment]
It may happend that him tried to apply this driver on his code but didn't comment out properly the original `from selenium import webdriver`.
