### ISSUE TITLE
Question - webdriver.remote availability

### ISSUE THREAD

**Issue by o1da** [wkeeling/selenium-wire#18]
Is the remote version of webdriver available? I can't see it in the documentation.

I normally use selenium like:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Remote("http://selenium:4444/wd/hub", DesiredCapabilities.CHROME)
```
But I need to manipulate request headers and it isn't available in plain `selenium.webdriver`

**Comment by wkeeling** [comment]
@o1da  - thanks for your query. Unfortunately Selenium Wire doesn't yet support the remote webdriver. It works only with the regular webdriver for local testing. I'm hoping to implement support for the remote version in the (hopefully near) future when I have a little more time.

**Comment by o1da** [comment]
@wkeeling - thank you for the response, I understand. Do you have a tip for any workaround?

**Comment by o1da** [comment]
@wkeeling It is very helpful from you - Thanks.

**Comment by pariola** [comment]
Please is there any update on this?

**Comment by wkeeling** [comment]
@pariola there's currently no support for Selenium's remote webdriver. Selenium Wire has to run on the local machine.
