### ISSUE TITLE
Requests with base64 are not listed

### ISSUE THREAD

**Issue by ViktorRubenko** [wkeeling/selenium-wire#183]
I try to catch requests with base64 encoded content, but they are not being listed.

eg. https://composites-cis.com/ has 5 requests "data:application/font-woff2;base64"
I can intercept it with puppeter, but not with seleniumwire :(

**Comment by wkeeling** [comment]
Thanks for raising this. Are you able to give an example of some of the request URLs in question? I have tried looking at the requests being made to https://composites-cis.com/ using the browser's network tab, but I'm not sure exactly which requests we're talking about.

**Comment by ViktorRubenko** [comment]
![ex](https://user-images.githubusercontent.com/16288991/102996710-a09a1300-4534-11eb-856a-83db4a9f9785.png)

**Comment by wkeeling** [comment]
The `data:` URLs listed in the network tab are not requests as such. They contain embedded base64 encoded content and do not leave the browser - so there's currently no way for Selenium Wire to intercept them (Selenium Wire captures requests as they flow through it's internal proxy server to the target site). Puppeteer uses the DevTools protocol which provides lower level control over Chrome/Chromium browsers and likely allows access to data URLs.
