### ISSUE TITLE
seleniumwire does not represent correct requests made from a browser!

### ISSUE THREAD

**Issue by alex4200** [wkeeling/selenium-wire#184]
When I open the URL 

`https://www.google.com/search?q=42`

with `selenium-wire`, I get a list of 47 requests. 

When I load the same page in a normal chrome browser, I see 63 requests in the network tab!

Why do I have this discrepancy? I thought `selenium-wire` monitors each request?

**Comment by wkeeling** [comment]
Thanks for this. When I run the test with:

```
url = 'https://www.google.com/search?q=42'
driver = webdriver.Chrome()
driver.get(url)

print(len(driver.requests))
```
The above code prints `43`.

When I load the URL in Chrome, the network tabs says 41.

Are you sure the network tab is completely empty before you load the URL? Perhaps Chrome is making some requests before you hit enter to load the URL - e.g. requests for auto-complete suggestions?

**Comment by wkeeling** [comment]
Should just note that the browser makes a number of 'hidden' requests to various Google endpoints (or Mozilla endpoints if using Firefox) which Selenium Wire is able to capture. This means that you would typically see more requests printed by Selenium Wire than shown in the browser's network tab - as illustrated by the example above. 

@alex4200 do you have any examples of requests which you can see in the network tab but which have not been captured by Selenium Wire?

**Comment by alex4200** [comment]
I did repeat the test with the following code:

```
import time
from seleniumwire import webdriver  

url = 'https://www.google.com/search?q=42'
driver = webdriver.Chrome()
driver.get(url)
time.sleep(10) # some wait to make sure the page is loaded...

print(len(driver.requests))

driver.close()
```

With that code repeated some times I get 42 requests, then 46, then 47 and 47 again.  With an empty private chrome browser tab I get 50 requests. 

Now, a few requests more or less is not the big problem. The actual worrying part is that I need to get all requests a browser is doing when I access a non-public webpage in development. Here I see a extreme discrepancy. With `selenium-wire` I get **184** requests, while in reality (private chrome network developer tab) there are **326** requests!!

That webpage first loads a skeleton html page, a css file and javascript. The javascript gets executed, makes a query to a search engine, returning a list of >100 images the javascript is loading to the browser content. This all seems to be entirely missing from the `selenium-wire` output, although I waited for 60 seconds for the page to be loaded!

Any ideas what could go on? 

I will try to find a public-available example where I can see the same behavior in the meantime.

**Comment by alex4200** [comment]
Maybe I know what is going on! It seems like the network developer tab does count more than http requests (like options and blobs). So the number of **entries** does not correspond to the number of **requests**. 

I guess ticket can be closed.

**Comment by wkeeling** [comment]
Ah yes good catch - I'd forgotten that Selenium Wire filters out OPTIONS requests by default. See the `ignore_http_methods` [option](https://github.com/wkeeling/selenium-wire#all-options) for more info. Thanks for investigating it!
