### ISSUE TITLE
Proxy doesn't seem to be working

### ISSUE THREAD

**Issue by zactham** [wkeeling/selenium-wire#185]
Firefox doesn't seem to be using my proxy instead goes to local host. 

[Thread 4617416192] [INFO] [seleniumwire.proxy.client] Created proxy listening on 127.0.0.1:51090

options = {
    'proxy': {
        'http': 'http://192.168.10.100:8888',
        'https': 'https://192.168.10.100:8889',
        'no_proxy': 'localhost,127.0.0.1'
    }
}
driver = webdriver.Firefox(seleniumwire_options=options)

**Comment by wkeeling** [comment]
Selenium Wire captures requests by redirecting browser traffic to it's own internal proxy server running on localhost. Traffic is then sent on to any upstream proxy that's been configured. So you would expect to see "localhost" in Firefox's proxy settings.

Are you facing a particular issue with it?

**Comment by zactham** [comment]
I configured my own upstream proxy using the format above, but Selenium Wire doesn't seem to use it and resorts directly to local host.  I feel as though I must be missing something.

**Comment by wkeeling** [comment]
From the log message we can see that Selenium Wire has started up its own internal proxy `Created proxy listening on 127.0.0.1:51090`. So Firefox will use that, and then all requests from Firefox will go through that proxy into Selenium Wire, and from there Selenium Wire will forward the requests onwards to your upstream proxy at 192.168.10.100. 

Do you not see any requests reaching your upstream server?

**Comment by zactham** [comment]
I don't think the proxy is being accessed at all, it just sits on the local host IP.  When I check my ip on a site like whatismyip, it is my computer's default ip.  When I run the proxy through chrome with a different package I have no trouble and the IP changes.  

It is almost like the proxy is skipped entirely and it just runs off of the local host the entire time.
