### ISSUE TITLE
cannot import name 'ADMIN_PATH' from 'seleniumwire.proxy.handler'

### ISSUE THREAD

**Issue by P-Leo10** [wkeeling/selenium-wire#195]
![image](https://user-images.githubusercontent.com/68583445/105083903-598c3880-5a74-11eb-8522-a7b8dec6b775.png)

**Comment by wkeeling** [comment]
Thanks. I had noticed that ADMIN_PATH was still being referenced by `client.py`, although that module has been superseded by `backend.py` from version 4 onwards and so technically `client.py` isn't in use (and will be removed in a subsequent release). So it shouldn't cause any issues unless something is using `client.py` directly. 

Are you able to share the traceback as text, as the screenshot is a little unclear.

**Comment by wkeeling** [comment]
Resolved in v4.
