### ISSUE TITLE
Secure Connection Failed with proxy in Firefox

### ISSUE THREAD

**Issue by tsoernes** [wkeeling/selenium-wire#198]
```
    from seleniumwire import webdriver
    options = {
        'proxy': {
            'http': f'https://{user}:{passw}@{host}:{port}',
            'https': f'https://{user}:{passw}@{host}:{port}',
            'no_proxy': 'localhost,127.0.0.1' # excludes
        }
    }
    browser = webdriver.Firefox(seleniumwire_options=options)
```
Yields me `Secure Connection Failed` attempting to load Youtube.com.

with 
- Mozilla Firefox 84.0.2
- selenium-wire                      3.0.5

I have attempted to do `python -m seleniumwire extractcert` and then import it into Authorities in Firefox's Certificate Manager but to no luck.

**Comment by wkeeling** [comment]
Does it work if you go direct to youtube.com without using the `proxy` option?

**Comment by wkeeling** [comment]
Does it may any difference if you use the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends)? This connects to the upstream proxy using a different underlying mechanism. Some people have reported that this mechanism is more reliable with upstream proxies. Maybe worth a try.

You need to install the mitmproxy backend with:

```
pip install mitmproxy
```

And then specify that in the options:
```
options = {
    'proxy': {
        'backend', 'mitmproxy',
        'http': f'https://{user}:{passw}@{host}:{port}',
        'https': f'https://{user}:{passw}@{host}:{port}',
        'no_proxy': 'localhost,127.0.0.1' # excludes
    }
}
browser = webdriver.Firefox(seleniumwire_options=options)
```

I'm currently looking at improving the upstream proxy connection logic, so this workaround I hope will be temporary.

**Comment by tsoernes** [comment]
@wkeeling With `mitmproxy`, loading any page yields `The connection was reset`. No error is printed in the RPEL.

**Comment by tsoernes** [comment]
`mitmproxy` does not seem to have a working DNS. I get `Hmm. We’re having trouble finding that site.` for any page.

**Comment by wkeeling** [comment]
Sorry, yes good catch on the `backend`.

Have you tried plugging the proxy values directly into Firefox - as in adding them here:

![image](https://user-images.githubusercontent.com/1295116/105645280-8d12fc80-5e92-11eb-8507-92f4136c5514.png)

And then once added, open a new tab and navigate to youtube.com?

**Comment by tsoernes** [comment]
Yes, I have the same problem then.

**Comment by wkeeling** [comment]
OK thanks. It sounds like the issue is with the proxy you're using if the problem still happens when you configure Firefox directly. I would suggest contacting the proxy provider directly to understand what the issue is.
