### ISSUE TITLE
Certificates not valid on Chrome when running standalone proxy

### ISSUE THREAD

**Issue by wkeeling** [wkeeling/selenium-wire#2]
This does not affect selenium tests and is only an issue when running Selenium Wire in standalone mode with:

`python -m seleniumwire standaloneproxy port=12345`

When using Chrome with the standalone proxy it reports that the server's certificate is not valid. This is because the certificate is created without a Subject Alternative Name. This is not a problem on older versions of Chrome, but is on newer versions as Chrome has tightened up its security.

The solution is to ensure that OpenSSL sets the Subject Alternative Name when generating certificates. There is a command line option for this in newer versions of OpenSSL but not in older versions.

**Comment by runabh** [comment]
We are facing the same issue where the certificate is not considered valid.
We've tried modifying the .conf file for openssl but it did not change the behavior. 
Did anyone find a solution to this?

**Comment by wkeeling** [comment]
@runabh Are you seeing this when running Selenium Wire in a test, or when running in standalone mode with `standaloneproxy`?

**Comment by runabh** [comment]
We are running Selenium wire in a test. Please have a look at the code.

from seleniumwire import webdriver
from seleniumwire.webdriver import ChromeOptions
import time
options = {
    'https': 'proxy detail',
        'disable_encoding': True
}
browser = webdriver.Chrome(seleniumwire_options = options)
browser.header_overrides = { 'Cookie': 'cookie string' }

browser.get('url')

**Comment by wkeeling** [comment]
@runabh up to now this issue had only been seen in standalone mode. Since you're seeing it in a test, I have raised a separate ticket - #31

**Comment by wkeeling** [comment]
The root certificate was using an out of date hashing algorithm which seemed to be causing this. The certificate has been updated and now works correctly in Chrome.
