### ISSUE TITLE
Seleniumwire not executing javascript code in html page

### ISSUE THREAD

**Issue by daeeros** [wkeeling/selenium-wire#202]
I have thets code, but when i getting some-url, site making check my browser with javascript, and after compleate redirecting me to the page, now when i try to get page source after 10 sec, i get browser check code with js + html, it not executed, why? when i change sleneiumwire to selenium it currently worked.

```
from seleniumwire import webdriver

import os
import time
import json

#===================================================================#
chrome_options = webdriver.ChromeOptions()
chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--window-size=1920x1080")
#===================================================================#

br = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), options=chrome_options)

def interceptor(request):
    del request.headers['Cookie']
    del request.headers['Host']
    del request.headers['User-Agent']

    request.headers['Cookie'] = '_lr_uf_-xnoogq=fa845c27-e6da-43eb-a3dd-b2d02ac950d6'
    request.headers['Host'] = 'some-site.ru'
    request.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'

br.request_interceptor = interceptor

magic_product = [1025627, 6308]

while True:
    for product in magic_product:
        br.get(f"https://some-site/buy/{product}")
        time.sleep(10)

        html = br.page_source
        time.sleep(2)
        try:
            print(json.loads(str(html.split("<body>")[1].split("</body>")[0])) + f" #ID{product}")
        except json.decoder.JSONDecodeError:
            print(html)

    time.sleep(18000)
```

**Comment by wkeeling** [comment]
This may be happening because you're switching the `Host` header in the interceptor. That will break the SSL handshake which will prevent the page from loading. Does it work if you comment out the lines:

```
del request.headers['Host']
...
request.headers['Host'] = 'some-site.ru'
```

**Comment by daeeros** [comment]
> Это может происходить из-за того, что вы переключаете `Host`заголовок в перехватчике. Это нарушит квитирование SSL, что предотвратит загрузку страницы. Это работает, если закомментировать строки:
> 
> ```
> #del request.headers['Host']
> ...
> #request.headers['Host'] = 'some-site.ru'
> ```

I commented this lines, but again when i try to get page source  i get this:

```
<html lang="ru">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,initial-scale=1.0">
      <title>Игровой магазин</title>
      <style>@import url("https://fonts.googleapis.com/css?family=Roboto&display=swap"); body{background: #0b0c0e; color: #b9bdc6; font-family: "Roboto", sans-serif; font-size: 16px}a{color: #69f; text-decoration: none}.verification{position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center}.verification__title{margin-bottom: .25rem; font-size: 2rem}.verification__text{font-size: 1.25rem}.copyright{position: absolute; bottom: 0; left: 0; padding: .5rem .75rem; border-top-right-radius: .25rem; background: #111215}</style>
   </head>
   <body>
      <div class="verification">
         <div class="verification__title">Пожалуйста, подождите.</div>
         <div class="verification__text">Идет проверка вашего браузера</div>
      </div>
      <div class="copyright">Сайт создан в системе <a href="//my.moscow.ovh" target="_blank" rel="noreferrer noopener">Moscow.OVH</a></div>
      <script type="text/javascript" src="/aes.js"></script>
      <script>
         function toNumbers(d) {
             var e = [];
             d.replace(/(..)/g, function (d) {
                 e.push(parseInt(d, 16));
             });
             return e;
         }
         function toHex() {
             for (var d = [], d = 1 == arguments.length && arguments[0].constructor == Array ? arguments[0] : arguments, e = "", f = 0; f < d.length; f++) e += (16 > d[f] ? "0" : "") + d[f].toString(16);
             return e.toLowerCase();
         }
         function iudh2912983() {
             location.href = "https://shop.magic-rust.ru/api/index.php?modules=items&action=purchaseItem&id=6308&type=4&try=3";
         }
         var a = toNumbers("cd36b76f96b103402924bd5f76d3c111"),
             b = toNumbers("680eb6a492f48ea1b342aea7b79e1c63"),
             c = toNumbers("4a848f1106a540e423f5c2bed8fa366a");
         document.cookie = "stmcn=" + toHex(slowAES.decrypt(c, 2, a, b)) + "; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
         setTimeout(iudh2912983, 3000);

      </script>
   </body>
</html>
```

**Comment by daeeros** [comment]
I try to full remove interceptor, and oh magic, its worked, why interceptor breaking code execute i dont understand, i remove all headers and just left cookie header, and its again not executing js code.

**Comment by wkeeling** [comment]
hmm.. interesting. What happens if you set an empty interceptor - e.g.

```
def interceptor(request):
    pass

br.request_interceptor = interceptor
```

**Comment by wkeeling** [comment]
OK so it seems as though the `Cookie` header is causing the problem. Are you sure the value of the cookie is correct? As a simple test, perhaps try setting the original value of the cookie back again:

```
def interceptor(request):
    cookie = request.headers['Cookie']
    if cookie:
        print(cookie)
        del request.headers['Cookie']
        request.headers['Cookie'] = cookie

br.request_interceptor = interceptor
```
What does this prove? If it works it would prove there is nothing wrong with the mechanism of deleting/setting a cookie, and would suggest that the real problem is with the value of the cookie that you're trying to use.

**Comment by daeeros** [comment]
> OK so it seems as though the `Cookie` header is causing the problem. Are you sure the value of the cookie is correct? As a simple test, perhaps try setting the original value of the cookie back again:
> 
> ```
> def interceptor(request):
>     cookie = request.headers['Cookie']
>     if cookie:
>         print(cookie)
>         del request.headers['Cookie']
>         request.headers['Cookie'] = cookie
> 
> br.request_interceptor = interceptor
> ```
> 
> What does this prove? If it works it would prove there is nothing wrong with the mechanism of deleting/setting a cookie, and would suggest that the real problem is with the value of the cookie that you're trying to use.

Yea, thats workded, but why i have bad cookie set, i getting it with there:

![image](https://user-images.githubusercontent.com/34482855/105881867-16067100-6016-11eb-8dbd-c3a00fbde7b9.png)


and just pusting in value

**Comment by wkeeling** [comment]
Ok I see the issue. The cookie header contains multiple cookies. You wish to replace one of those cookies, but your code will delete and overwrite _all of them_. 

We need to parse the existing cookies, replace just the cookie that you're interested in, and then set them back on the request. 

I'll see if I can get an example of how to do that. I should probably put it in the README too.

**Comment by daeeros** [comment]
> Ok I see the issue. The cookie header contains multiple cookies. You wish to replace one of those cookies, but your code will delete and overwrite _all of them_.
> 
> We need to parse the existing cookies, replace just the cookie that you're interested in, and then set them back on the request.
> 
> I'll see if I can get an example of how to do that. I should probably put it in the README too.


I'll look forward to

**Comment by wkeeling** [comment]
Are you able to copy the cookie value as text from the Developer Tools window and post it here? I'll then test the example with the real cookie text.

**Comment by daeeros** [comment]
> Are you able to copy the cookie value as text from the Developer Tools window and post it here? I'll then test the example with the real cookie text.

shure, this:

`_hash=91761be34e64415453b7716ca91095fb; _id=951738; _store=758; PHPSESSID=i9q7ib8le1bprrs6hhe16mrpk5; stmcn=c3810bcb5a690b2daf04ec837ae15904; _ym_uid=1606315156305587559; _ym_d=1611683003; lastItemEdit=1611602372; _ym_isad=2; _lr_uf_-xnoogq=3fc25b3c-a4d8-4fd9-b9ac-3eb601a17c01; _lr_tabs_-xnoogq%2Fplayrust={%22sessionID%22:0%2C%22recordingID%22:%224-704c4042-f201-48d7-833e-32ced8c6cde7%22%2C%22lastActivity%22:1611686896944}; _lr_hb_-xnoogq%2Fplayrust={%22heartbeat%22:1611686896945}; _ym_visorc_57380197=w`

**Comment by wkeeling** [comment]
Try this:

```
from http import cookies


def intercept(request):
    cookie = cookies.SimpleCookie()
    cookie.load(request.headers['Cookie'] or '')
    cookie['_lr_uf_-xnoogq'] = 'fa845c27-e6da-43eb-a3dd-b2d02ac950d6'

    del request.headers['Cookie']
    request.headers['Cookie'] = '; '.join(f'{k}={v.value}' for k, v in cookie.items())
```

The above code will add the `_lr_uf_-xnoogq` cookie to _every_ request. If the cookie already exists in the request, it will be updated with the new value (other existing cookies will not be overwritten). If the cookie does not exist in the request, it will be added to the request.

**Comment by daeeros** [comment]
> Попробуй это:
> 
> ```
> from http import cookies
> 
> 
> def intercept(request):
>     cookie = cookies.SimpleCookie()
>     cookie.load(request.headers['Cookie'] or '')
>     cookie['_lr_uf_-xnoogq'] = 'fa845c27-e6da-43eb-a3dd-b2d02ac950d6'
> 
>     del request.headers['Cookie']
>     request.headers['Cookie'] = '; '.join(f'{k}={v.value}' for k, v in cookie.items())
> ```
> 
> Приведенный выше код будет добавлять `_lr_uf_-xnoogq`cookie к _каждому_ запросу. Если файл cookie уже существует в запросе, он будет обновлен с новым значением (другие существующие файлы cookie не будут перезаписаны). Если cookie не существует в запросе, он будет добавлен в запрос.

thats currently worked, ty so much :3
