### ISSUE TITLE
Can't use chrome driver without specifying port

### ISSUE THREAD

**Issue by Ekillz** [wkeeling/selenium-wire#205]
I am on Mac OS

So i was trying to add a proxy for chromedriver but i kept getting an error, so i just passed the chrome path, and i still get this error message:

driver = webdriver.Chrome('/tmp/chromedriver')
  File "/seleniumwire/webdriver.py", line 83, in __init__
    addr, port = self.proxy.address()
ValueError: too many values to unpack (expected 2)

It only works if i pass the seleniumwire_options with a dict containing port.

**Comment by wkeeling** [comment]
Thanks for this. A fix for this bug actually went in today in v4.0.1. Can you upgrade and see if it fixes the issue?

```
pip install selenium-wire --upgrade
```

**Comment by Ekillz** [comment]
Thanks for the quick reply. I have this version actually, and still have the error.

This is what i am getting: 
<img width="493" alt="Capture d’écran 2021-02-01 à 18 47 34" src="https://user-images.githubusercontent.com/8539715/106497167-011a5980-64be-11eb-9fe5-b23d7b874b78.png">

**Comment by wkeeling** [comment]
Ok that's odd as that should be fixed. Would you be able to post the traceback - it's possible that a different area of code is also affected.

**Comment by Ekillz** [comment]
The traceback was the one i posted before:

Traceback (most recent call last):
  File "tutorial_screenshot.py", line 11, in <module>
    driver = webdriver.Chrome('/tmp/chromedriver')
  File "/venv/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 83, in __init__
    addr, port = self.proxy.address()
ValueError: too many values to unpack (expected 2)

**Comment by Ekillz** [comment]
I get this result in tcp.py:

<img width="652" alt="Capture d’écran 2021-02-01 à 19 33 14" src="https://user-images.githubusercontent.com/8539715/106502222-62452b80-64c4-11eb-8893-4cbd7aefdb93.png">

**Comment by wkeeling** [comment]
Thanks - new version 4.0.2 created which should resolve.

**Comment by Ekillz** [comment]
Thank you for the reactivity! It did fix the problem, i tried the same kind of fix, but my brain kept screaming, sacrilege!

**Comment by wkeeling** [comment]
Thanks for confirming!
