### ISSUE TITLE
Proxy Auth works in requests, but won't in selenium-wire?

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#206]
1. requests version
```python
import requests
proxies = { 'https' : 'https://access_token:1u539tejafpgnfvgd7plau5riitdfem8oc7ij5kg7b0364ns5nvg@ext-vu-exelite-us-lax-pr-v-9.northghost.com:443' } 
r = requests.get('https://api.myip.com/', proxies=proxies) 
print(r.text)
```

output: `{"ip":"149.248.16.136","country":"United States","cc":"US"}`

2. seleniumwire version
```python
from seleniumwire import webdriver
options = {
    'proxy': {
        'https': 'https://access_token:1u539tejafpgnfvgd7plau5riitdfem8oc7ij5kg7b0364ns5nvg@ext-vu-exelite-us-lax-pr-v-9.northghost.com:443',
    }
}
driver = webdriver.Chrome(seleniumwire_options=options)
driver.get("https://api.myip.com/")
```
output: `127.0.0.1:53048: request -> HTTP protocol error in client request: Server disconnected`

Can anyone help me fix this, or does anyone have an idea why it doesn't work?

**Comment by Avnsx** [comment]
This is what it orginally looks like in chrome network logs
```json
{"params":{"headers":["Host: api.myip.com","Proxy-Connection: keep-alive","Proxy-Authorization: Basic YWNjZXNzX3Rva2VuOjF1NTM5dGVqYWZwZ25mdmdkN3BsYXU1cmlpdGRmZW04b2M3aWo1a2c3YjAzNjRuczVudmc=","Upgrade-Insecure-Requests: 1","User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36","Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","Accept-Encoding: gzip, deflate","Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7"],"line":"GET http://api.myip.com/ HTTP/1.1\r\n"},

**Comment by wkeeling** [comment]
Yes there does seem to be an issue here. I'll see if I can figure out what's going on.

**Comment by wkeeling** [comment]
I've been looking into this, but I'm getting the same behaviour with a browser, the requests library and with Selenium Wire. The proxy host seems to immediately disconnect when the initial connection is attempted. Is the host and port definitely correct?

**Comment by Avnsx** [comment]
@wkeeling Yes the host, port and the credentials are definetly correct. In-fact if I execute the requests code I pasted above, it still responds with the US proxy server.

But you can try it with a diffrent password, as I know those will eventually expire. Just replace the one in requests with this new one `c7hp19opfqh2b5iecpe6fhmhhlrlp54f4l3li3j7acqkpggk8se`

**Comment by wkeeling** [comment]
I tried again with the new password above, but I get the same thing:

```
>>> import requests
>>> proxies = { 'https' : 'https://access_token:c7hp19opfqh2b5iecpe6fhmhhlrlp54f4l3li3j7acqkpggk8se@ext-vu-exelite-us-lax-pr-v-9.northghost.com:443' } 
>>> r = requests.get('https://api.myip.com/', proxies=proxies)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 818, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 294, in connect
    self._tunnel()
  File "/usr/lib/python3.6/http/client.py", line 930, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.myip.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
```
Maybe that new password has expired already?

**Comment by Avnsx** [comment]
No the password didn't expire, but you're right. I tried to run the exact requests code on a remote server, and it also immediately disconnects when the initial connection is attempted. I don't know too much about proxy servers, but what kind of whitelisting could be going on here, that allows that code to run on my physical device but not on an remote one? And on my home device I also changed IPs through a VPN and ran it, and it would still work... so can it even be an IP whitelist? I'm very confused.

**Comment by wkeeling** [comment]
I wonder whether it's doing some sort of deep packet inspection and is able to identify your local device, even when the traffic passes through a VPN. I assume Selenium Wire works ok if you run it on your local whitelisted device?

**Comment by Avnsx** [comment]
No, even on my home device I can only connect through the requests package.

**Comment by wkeeling** [comment]
Just a thought, but I wonder whether the whitelisting is being done on an IPv4 / IPv6 basis. I can see that Selenium Wire is connecting using IPv6 when I run locally. If the proxy is whitelisting using IPv4 only, then that may explain why hosts and programs that are using IPv6 can't connect. Would need to do some more investigation into that - just a thought currently.

**Comment by Avnsx** [comment]
@wkeeling So any updates on this?

**Comment by wkeeling** [comment]
I forgot to ask what version of Selenium Wire you're using? The core of the library has been reworked in version 4, so it may be worth seeing whether version 3.0.6 works. If it works it may give some clues as to what's going on. Are you able to try 3.0.6?

**Comment by Avnsx** [comment]
Just upgraded to the newest version of selenium wire, still the same outcome.

**Comment by wkeeling** [comment]
What happens if you try 3.0.6 or were you already on that version?

**Comment by Avnsx** [comment]
`127.0.0.1:1657: request
  -> HTTP protocol error in client request: Server disconnected
127.0.0.1:1664: request
  -> HTTP protocol error in client request: Server disconnected
127.0.0.1:1663: request
  -> HTTP protocol error in client request: Server disconnected
`

**Comment by wkeeling** [comment]
OK I can see the issue. I've managed to connect to the proxy server using your access_token above (the first one you supplied) and version 3.0.6 of Selenium Wire. The issue is that the proxy server accepts the proxy connection over http not https. So this means that you have to specify the http version in the Selenium Wire options - 

```
options = {
    'proxy': {
        'http': 'http://access_token:1u539tejafpgnfvgd7plau5riitdfem8oc7ij5kg7b0364ns5nvg@ext-vu-exelite-us-lax-pr-v-9.northghost.com:443',
    }
}
```
BUT this doesn't work with Selenium Wire > v4, since this version always tries to use https regardless. So try installing version 3.0.6 and changing the proxy config to http as above. 

Note that the output you posted in your last comment is from version 4 NOT 3.0.6 - so it's possible that you may have version 4 still installed in your environment. Try explicitly uninstalling it first with `pip uninstall selenium-wire` followed by `pip install selenium-wire==3.0.6` followed by `pip show selenium-wire` to prove that 3.0.6 is definitely installed.

In the meantime I'll investigate why v4 of Selenium Wire always chooses https regardless of whether http is specified in the proxy settings.

**Comment by Avnsx** [comment]
@wkeeling that last deleted response of yours made me laugh, thanks for that! 😄

**Comment by wkeeling** [comment]
Yes I did run some tests using the requests library with http vs https and I initially thought using http to connect to the proxy made a difference, but then realised I'd made a mistake in my testing, and in fact the behaviour was the same as https (connection closed) - hence me deleting the post.

So I'm afraid I'm running out of ideas on this one. The proxy is obviously doing access control at some level, but I currently have no idea what that could be.
