### ISSUE TITLE
Integration with undetected-chromedriver

### ISSUE THREAD

**Issue by Zozimo-Brasil** [wkeeling/selenium-wire#207]
Some sites are not loaded when using Selenium Wire, as they detect Bot, which Undetected Chromedriver can pass.
Is there a way to integrate the two and not get blocked when using the selenium wire?

**Comment by wkeeling** [comment]
Selenium Wire v4.1.1 now integrates with undetected-chromedriver if it finds it in your environment. More info in [the docs](https://github.com/wkeeling/selenium-wire#bot-detection). This is still experimental so if you find any problems or you want to suggest any improvements please raise an issue. Closing this issue for now.
