### ISSUE TITLE
Does selenium-wire support PhantomJS?

### ISSUE THREAD

**Issue by nrllh** [wkeeling/selenium-wire#208]
I try to run the following code for PhantomJS:

```
from seleniumwire import webdriver
param_driver_phantomjs='phantomjs/bin.exe'
driver = webdriver.PhantomJS(executable_path=param_driver_phantomjs)  
driver.get('https://google.com/'); 
print(driver.requests)
```

But I get:

> AttributeError: module 'seleniumwire.webdriver' has no attribute 'PhantomJS'

I know that PhantomJS is deprecated (also support by selenium, but it still works). Though it's still for me interesting to run it on selenium. Doesn't selenium-wire support PhantomJS?

**Comment by wkeeling** [comment]
There's no support for PhantomJS in Selenium Wire at the present time, but it's certainly something that we could investigate adding.

**Comment by nrllh** [comment]
I don't really need it just wanted to know and PhantomJS is deprecated. So maybe it's really not a good idea to investigate time in that.

**Comment by wkeeling** [comment]
Yes I noticed that PhantomJS development has been suspended. I'll close this ticket for the moment but we can always be re-open it if there is sudden demand for PhantomJS support.
