### ISSUE TITLE
RUN selenium-wire into kubernetes pod

### ISSUE THREAD

**Issue by stanlee321** [wkeeling/selenium-wire#212]
Hi, you have a wonderful project here.

I was using your project for download some page requests responses,  It works great into a Docker container, but there is a problem when I try to deploy this container into a Kubernetes cluster, inside the pods the selenium-wire was returning the "error before this commit 1f54d2002565fe5ee7fda29fe85cb975860f0737" . I installed manually this commit 1f54d2002565fe5ee7fda29fe85cb975860f0737 and the error is gone but the program start to show this message

base) ➜ o-python-scraper git:(master) ✗ kubectl logs scrapertest-5f589db965-ftk5g
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - There is no [linux64] chromedriver for browser 88.0.4324 in cache
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Trying to download new driver from https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96]
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache

I'm starting to learng Kubernetes and maybe there is some considerations that must to be taken for run selenium wiere inside a kuberentes cluster, as I mention, the selenium-wire works great inside a Docker container.

Thanks!!!!

**Comment by wkeeling** [comment]
Thanks for reporting this.

Yes the error you're seeing above is a known issue that sometimes occurs when you quit Selenium Wire when using the mitmproxy backend. It happens when Selenium Wire attempts to shutdown the backend before it has completely finished processing requests. Selenium Wire allows the backend a grace period to finish (up to 5 seconds), but if the backend hasn't finished in this time (e.g. there is a particularly slow request in play), then this will generate the above error when the backend goes down.

This error message won't happen in the default backend however. Have you tried the default backend with Kubernetes? It should just be a case of removing the `backend` option from the Selenium Wire options. There's also a new version of Selenium Wire (v4.0.4) which fixes the original error with the event loop you mention.

**Comment by stanlee321** [comment]
Hi, thank your for you fast reply.

Yes, I deactivate the `backend` parameter. 

Using the Chrome driver  it just shows the message from above until crash, with Firefox using Gecodriver it shows only  "broken pipe" 

base) ➜  -scraper git:(master) ✗ kubectl logs scrapertest-6f8b499cdf-b5v86
[WDM] - ====== WebDriver manager ======
[WDM] - There is no [linux64] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/geckodriver/linux64/v0.29.0]
127.0.0.1:48162: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:48164: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:48178: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:48184: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:48186: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
[WDM] - ====== WebDriver manager ======
[WDM] - Driver [/root/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache
127.0.0.1:54760: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:54758: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:54786: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
[WDM] - ====== WebDriver manager ======
[WDM] - Driver [/root/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Driver [/root/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Driver [/root/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache
127.0.0.1:34442: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')
127.0.0.1:34444: Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')




The way on which i'm starting the driver is this.

#from selenium.webdriver.firefox.options import Options
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
#from webdriver_manager.chrome import ChromeDriverManager


options_b = Options()
options_b.add_argument("--no-sandbox")


options_b.add_argument('--disable-dev-shm-usage')
options_b.add_argument("--headless")
options_b.add_argument("--disable-setuid-sandbox")
options_b.set_capability("acceptInsecureCerts", True)

options = {
    'connection_timeout': None,
    'connection_keep_alive': False,
    # 'backend': 'mitmproxy',
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}


# driver = webdriver.Firefox(
#     executable_path=GeckoDriverManager().install(), 
#     seleniumwire_options=options, 
#     options=options_b
# )

driver = webdriver.Chrome(

    executable_path=ChromeDriverManager().install(), 
    seleniumwire_options=options, 
    chrome_options=options_b
)


As I mention, it works great inside a docker container, but it shows this behavior when this image is deployed to kubernetes.

Thank you.

**Comment by stanlee321** [comment]
After a some time the script with the Chrome driver  passes the logs from the first example from above, but it started crash with the following results

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache

---------------INPUT----------------: 
{'do5-11 '}


HTTPConnectionPool(host='127.0.0.1', port=52253): Max retries exceeded with url: /session/845dd061c35d19bb3552e9223a9690ba/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85505c2650>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 341}
---------------INPUT----------------: 
{'doc24 '}


HTTPConnectionPool(host='127.0.0.1', port=40669): Max retries exceeded with url: /session/bed69eb7512ccfc17a86d6c81bf03aee/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f855041b910>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 342}
---------------INPUT----------------: 
{'doc4-30 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 343}
BAD CALL TO API
---------------INPUT----------------: 
{'docu2-26 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 344}
---------------INPUT----------------: 
{'doc-04 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 345}
---------------INPUT----------------: 
{'d8 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 346}
---------------INPUT----------------: 
{'doc8 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 347}
---------------INPUT----------------: 
{'do0 '}


HTTPConnectionPool(host='127.0.0.1', port=39659): Max retries exceeded with url: /session/f2f1403c9646b478ebcc4f929910ff55/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f855025cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 348}
---------------INPUT----------------: 
{'docum-11 '}


HTTPConnectionPool(host='127.0.0.1', port=40665): Max retries exceeded with url: /session/721f53ef3e28828e5c44d7aff367bf50/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8550212c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 349}
---------------INPUT----------------: 
{'docu-03-24 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 350}
---------------INPUT----------------: 
{'docu4-30 '}


HTTPConnectionPool(host='127.0.0.1', port=55411): Max retries exceeded with url: /session/abca480af2e166bf274d406aa4abb4e7/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8550506a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 351}
---------------INPUT----------------: 
{'documen09-18 '}


HTTPConnectionPool(host='127.0.0.1', port=35655): Max retries exceeded with url: /session/3300a044558464587f4d34dda374e9d4/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85500eb090>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 352}
BAD CALL TO API
---------------INPUT----------------: 
{'docume4-04 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 353}
---------------INPUT----------------: 
{'docum07-28 '}


HTTPConnectionPool(host='127.0.0.1', port=35405): Max retries exceeded with url: /session/2bdabc67b90477423d3c400861cc59b6/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85501b9f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 354}
---------------INPUT----------------: 
{'doc7-28 '}


HTTPConnectionPool(host='127.0.0.1', port=43909): Max retries exceeded with url: /session/0ae0196f3c2337b5c97fa29ae69d6760/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f855042a5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 355}
---------------INPUT----------------: 
{'doc5-20 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 356}
---------------INPUT----------------: 
{'docu5-11 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 357}
---------------INPUT----------------: 
{'docum03-24 '}


Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="valDoc"]"}
  (Session info: headless chrome=88.0.4324.150)

{"job_id": 358}
---------------INPUT----------------: 
{'docum5-04-30 '}


HTTPConnectionPool(host='127.0.0.1', port=54707): Max retries exceeded with url: /session/d1506fd954ac5496111b6dc353224fb5/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f854068c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 359}
---------------INPUT----------------: 
{'docum18 '}


HTTPConnectionPool(host='127.0.0.1', port=42833): Max retries exceeded with url: /session/297dfbecc1bd5810201eb001af436111/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f854063efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 360}
---------------INPUT----------------: 
{'doc11-13 '}


HTTPConnectionPool(host='127.0.0.1', port=54483): Max retries exceeded with url: /session/41e5bae67669a64a5bf5d4c155a8f402/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85501b03d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 361}
BAD CALL TO API
---------------INPUT----------------: 
{'docu79-07-28 '}


HTTPConnectionPool(host='127.0.0.1', port=34483): Max retries exceeded with url: /session/2f0ce5519f9e1234ab8a716361d2b0fe/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8550049250>: Failed to establish a new connection: [Errno 111] Connection refused'))
{"job_id": 362}
---------------INPUT----------------: 
{'docum-07-28 '}


[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache





As I mention, the simple Docker image works great, but only when I try to deploy it in kubernetes fails with this logs.

Thank you for your patience.

**Comment by wkeeling** [comment]
OK thanks. It's possible that we're missing some information. Can you try increasing the log level by adding the following to the top:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```
It may also be worth changing the directory that Selenium Wire uses to store requests to rule out any permissions issue. You can do that with the `request_storage_base_dir` option:

```
options = {
    'request_storage_base_dir': '/tmp',  # Change the storage directory
    'connection_timeout': None,
    'connection_keep_alive': False,
    # 'backend': 'mitmproxy',
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}
```
Also can you confirm which version of Selenium Wire you're running with now?

**Comment by wkeeling** [comment]
@stanlee321 did you get any further with this?

**Comment by stanlee321** [comment]
Hi.
I was still trying this approach until the past week but does not work for me. I opted by another scraping option.  By the moment I want to close this issue. Anyway, thank you so much for your help, you are the best in this!.

**Comment by adirzoari** [comment]
@stanlee321 did you find any solution?
