### ISSUE TITLE
Clear requests

### ISSUE THREAD

**Issue by syrius13** [wkeeling/selenium-wire#216]
When I open a new browser with `driver = webdriver.Firefox() ` and then inspect the requests, I see that the browser already requests some stuff, before I even navigate to a site. It e.g contacts the OSCP Server from digicert and other similar services.
This is not an issue and it makes sense that this is recorded. However as these requests are not of interest to me, I tried to clean them, before I start my session. When I try to clear these requests by running `driver.requests.clear()` it does however not clear them. 

I then started to navigate to other pages and tried to clear the requests list again. But it also does not work for them. 
How can I clear the list with the requests?

**Comment by wkeeling** [comment]
Thanks for this. It's mentioned in the doc in the [Accessing Requests section](https://github.com/wkeeling/selenium-wire#accessing-requests), but it's easy to miss. You clear requests with:
```
del driver.requests
```
The requests are indexed in memory and persisted to disk, so the `del` mechanism performs a number of actions under the covers to clear the requests. `requests.clear()` is not enough on it's own.

Hope that helps!
