### ISSUE TITLE
Tab crashes issue

### ISSUE THREAD

**Issue by atdevyesh** [wkeeling/selenium-wire#226]
Hi,

I have my backend running on a docker container in AWS. I have a cron job that uses selenium wire to get some data.
Every 2 days, i see this error
`session not created from tab crashed (Session info: headless chrome=87.0.4280.66)`
Then i see bunch of core* dumps from chrome crashing(i assume). 

Any idea why this is happening ? I feel like i am not catching some error case. I use multiprocessing as well.

These are all the Chrome options that i have
```
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument("--headless")
    chrome_options.add_argument('--disable-infobars')
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument('--crash-dumps-dir="/dev/null"')
```
Thanks for the help

**Comment by wkeeling** [comment]
Thanks for raising this. How long does the cron job typically take to run? At the end of the job, do you call `driver.quit()` before the process ends?

**Comment by atdevyesh** [comment]
it runs for maybe 20 seconds at the most. yes, i do call driver.quit(). 

My current suspicion  is there is some exception that i am not catching that that is causing the crash. Right now i am handling InvalidSessionIdException, WebDriverException, NoSuchWindowException. Is there any specific exception that can help me with handling tab crashes?

**Comment by wkeeling** [comment]
I'm not aware of any specific exception, but it may be worth catching `Exception` itself to see if that picks up anything else.
One other thing to try - you could try starting each Chrome instance with a unique `--user-data-dir` path (profile directory). That will ensure that the instances start with a clean profile and don't interfere with each other when they execute.

**Comment by atdevyesh** [comment]
ok, i will try this. Thanks @wkeeling for the help

**Comment by wkeeling** [comment]
Any improvement on this @atdevyesh ?
