### ISSUE TITLE
127.0.0.1:51460: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)

### ISSUE THREAD

**Issue by samellis003** [wkeeling/selenium-wire#230]
i get this multiple times during webscraping. Does this mean its broken the proxy connection and started another?

**Comment by wkeeling** [comment]
My understanding is that message is caused by the upstream server (proxy if you are using one). I would hope the browser would attempt to re-establish the connection when the error happens. Do you notice any problems with page loading when you see the error?

**Comment by samellis003** [comment]
nothing at all on the browser changes however i have a text file full of proxies and everytime it says the error as it says it multiple times it has a different port number. Do you know why this is?

**Comment by samellis003** [comment]
its almost as if its using one proxy and then moving onto another proxy in the txt list after is abandons the connection

**Comment by wkeeling** [comment]
I'm not sure what's going on there exactly. Is there a traceback you can share? (You may need to set `suppress_connection_errors` to `False` first in the Selenium Wire options.)

**Comment by samellis003** [comment]
the only thing that is visibly wrong is the message i get in terminal i dont actually get a traceback

**Comment by samellis003** [comment]
do you think its an issue with my proxy
as ive used the same proxies in many other applications that require proxies
i appreciate the prompt reply

**Comment by wkeeling** [comment]
It may be that the proxy is causing it and Selenium Wire is able to show you the message, whereas other applications may hide the message. Perhaps you could post a snippet of the log that includes the message (with some before and after messages)? I may be able to hunt down whereabouts in the code the message is originating based on that.

**Comment by samellis003** [comment]
![image](https://user-images.githubusercontent.com/79975859/109836233-dc8bdb80-7c3b-11eb-9741-e061214bd8b1.png)
this is the image of the log is there any where else i can contact you to fill you in in more detail

**Comment by wkeeling** [comment]
Feel free to email me directly at will@zifferent.com

**Comment by wkeeling** [comment]
@samellis003 v4.2.1 attempts to quieten these warning messages by downgrading them to debug level.
