### ISSUE TITLE
how to disabled logging

### ISSUE THREAD

**Issue by jakkapong1129** [wkeeling/selenium-wire#236]

**Comment by wkeeling** [comment]
Selenium Wire will use whatever log level is set for the application or script (it just uses Python's standard logging mechanism). If the application is set to log at DEBUG level, then Selenium Wire will also log at this level. If you want to turn down just Selenium Wire's logging, you should be able to do something like this at the top of your script/program:

```
import logging
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('seleniumwire').level = logging.ERROR
```
Are there any messages in particular that you wish to silence?
