### ISSUE TITLE
Error Response : Error code : 502  

### ISSUE THREAD

**Issue by sluthra-globallogic** [wkeeling/selenium-wire#24]
Error Response : 

Error Code : 502 

Message: Bad Gateway 

This error message is displayed for few URL when the URL is opened via selenium-wire ( SAFARI ) but if I opened the URL manually in chrome once and after that, I try to run the script the home page of the URL is displayed. Need your help on this

**Comment by wkeeling** [comment]
@sluthra-globallogic is the error reproducible with a specific URL? Can you share that URL?

Also, do you have logging enabled for `seleniumwire` in your logging configuration? This should hopefully give some clues?

**Comment by appunni-dishq** [comment]
This is in  selenium-wire version 0.10.0, 
DEBUG code 502, message Bad Gateway
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 179, in do_GET
    res = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
DEBUG https://www.dishq.com/ 502

**Comment by appunni-dishq** [comment]
I tried on several links, this link also seems to have the problem

**Comment by wkeeling** [comment]
@appunni-dishq  the _Cannot save response as request xxxxx-xxx-xxxxx-xxxxx-xxxxx is no longer stored_ message can happen when Selenium Wire is shutting down. 

As Selenium Wire shuts down, it removes its temporary request storage - basically all of the request and response data that was captured during the testing session. Whilst this is happening, responses may return from previously transmitted requests. These responses however cannot be saved, because their associated request data has now been removed, and hence the message is seen.

The message is harmless and perhaps ought to be suppressed.

**Comment by wkeeling** [comment]
@appunni-dishq The second part of your comment - the traceback - is related to something else. An HTTP 502 indicates a possible issue with an upstream proxy. Have you configured Selenium Wire with an upstream proxy? Is the 502 seen during the test session, or at the end when the test shuts down?

**Comment by appunni-dishq** [comment]
@wkeeling I checked it with proxy and as well as without proxy. But I had openvpn running in both cases I got 502. When I shut openvpn down it was working fine.

**Comment by sluthra-globallogic** [comment]
@appunni-dishq 

Please donot forget to run install certificate command and update shell command under Applications>Python3.7

**Comment by appunni-dishq** [comment]
@sluthra-globallogic I am using Ubuntu and using python 3.6

**Comment by appunni-dishq** [comment]
@wkeeling Finally found out the reason for this behavior. When the response sent by the server is empty but HTTP status is 200 this kind of error occurs. It's a very niche problem to start with.

**Comment by wkeeling** [comment]
@appunni-dishq thanks for that - that's good information. I'll look at whether Selenium Wire can handle that scenario better, although it seems like an edge case as you indicated. 

I think empty response bodies would normally be sent with status codes of 201 (created) or 204 (no content), so a 200 response with an empty body seems more like an invalid response from the upstream server. That said, Selenium Wire probably shouldn't respond with a 502.

Thanks again for the update.

**Comment by appunni-dishq** [comment]
@wkeeling I checked how request module responds to it, as well as chrome. Request module waits for a response until timeout and chrome say "Could not get any response".  It's not a standard HTTP response so no response code. In my opinion selenium wire should simply ignore it and let chrome handle it.

**Comment by wkeeling** [comment]
Ok thanks @appunni-dishq . So just to clarify, are you saying that the response is coming back with a `200` status code and empty body, or the response is coming back without _any_ status code?

Agreed that it would be best to pass it through and let the browser handle it.

**Comment by appunni-dishq** [comment]
Body Empty and  status code is 200

**Comment by wkeeling** [comment]
I have not been able to reproduce this. I created an end point which returned a 200 OK response with  an empty body. I then used Selenium Wire to hit this end point. Selenium Wire captured the response and had no problem handling the zero byte body.

I suspect there may be something specific to your environment which is causing you to see this particular problem. 

For information, my test setup looked like this:

    def test_status_200_empty_body(self):
        url = 'http://localhost:8000/empty'  # Returns a 200 OK with empty body
        driver = webdriver.Firefox()
        driver.get(url)

        request = driver.wait_for_request(url)

        self.assertEqual(request.response.status_code, 200)
        self.assertIsNone(request.response.body)

        driver.quit()

**Comment by satheeshkumarf** [comment]
we are also facing this issue of 502, even after setting chrome option to disable ssl. Is there any update eon this?

**Comment by wkeeling** [comment]
@satheeshkumarf can you try increasing your log level to `DEBUG` and also disable connection error suppression with:

```
options = {
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

that may then yield some extra information which will aid debugging this issue.

**Comment by wkeeling** [comment]
Thanks @Wooden-Robot 

So are you saying that the `'connection_timeout': 15` setting has resolved this for you?

**Comment by techfreakworm** [comment]
> I find that if the proxy is slow this kind of situation is more possible to happen.
> If you use a fake proxy it will be rehappened. For example:
> 
> ```
> from seleniumwire import webdriver
> 
> options = {
>     'proxy': {
>         'http': 'http://username:password@127.0.0.1',
>         'https': 'https://lusername:password@127.0.0.1',
>     }
> }
> 
> option = webdriver.ChromeOptions()
> option.add_argument('headless')
> 
> driver = webdriver.Chrome(chrome_options=option, seleniumwire_options=options)
> driver.get('https://httpbin.org/get')
> print(driver.page_source)
> driver.quit()
> ```
> 
> I may have found a solution.
> 
> ```
> from seleniumwire import webdriver
> 
> options = {
>     'connection_timeout': 15,
>     'proxy': {
>         'http': 'http://username:password@127.0.0.1',
>         'https': 'https://lusername:password@127.0.0.1',
>     }
> }
> 
> option = webdriver.ChromeOptions()
> option.add_argument('headless')
> 
> driver = webdriver.Chrome(chrome_options=option, seleniumwire_options=options)
> driver.get('https://httpbin.org/get')
> print(driver.page_source)
> driver.quit()
> ```

This didn't solve it for me. driver.get(<URL>) works perfectly fine on `selenium` (tried both and chromedriver and geckodriver) but gives 502 on `selenium-wire`. 

However, for an unknown reason, it all works fine on MacOS machine but gives 502 only on a linux server.

FYI: MacOs machine and Linux server both are in the same country. So there can be no country restrictions coming into play for website access.

**Comment by josifoski** [comment]
Few weeks ago worked fine on Linux Ubuntu 18.04 with selenium-wire, now it's giving 502 error code.

**Comment by teaglebuilt** [comment]
same

**Comment by tuxubaev17** [comment]
@teaglebuilt ++++

**Comment by IamYVJ** [comment]
Selenium-wire was working perfectly until yesterday. I'm getting 502 Bad Gateway Today.

**Comment by wkeeling** [comment]
@IamYVJ Do you have logging turned up to DEBUG level? That may give some clues to why you're seeing the error:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by teaglebuilt** [comment]
if this is an issue, its most likely dealing with a cocurrent process of this project running on your host machine. Also try running
```
pip install --upgrade certifi
```

**Comment by KeeonTabrizi** [comment]
It's very strange I get this exact error with seleniumwire v1.1.0+ (but works with earlier versions.)

```
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
```

However from v1.0.7-1.0.9 I don't have the issue.
Same code - only difference is the version of seleniumwire.

I am using a proxy server (`use_proxy=True`) which I add to my Chrome Webdriver through the `seleniumwire_options` argument and set it to a dictionary I created called `swire_options`. (Note for kicks I also set the same proxy through the Chrome Driver Options).

```python
    swire_options = {
        'suppress_connection_errors': False, 
        'verify_ssl': False,
        'connection_timeout': 20,
        'ignore_http_methods': [],
    }

    if use_proxy:
        swire_options['proxy'] = {
            http': proxy,
            'https': proxy,
        }
```

This is the error I see when using seleniumwire 1.1.0+: 
```
Error response
Error code: 502
Message: Bad Gateway.
Error code explanation: 502 - Invalid responses from another server/proxy.
```
![image](https://user-images.githubusercontent.com/3408390/84966909-900d6980-b0c7-11ea-8dd2-0d80d55448e4.png)

Here is some example code and the debug logging (this basically selects a proxy from my pool and tries to load an example url.

```python
import logging
from utils.proxy_util import get_proxies, validate_random_proxy
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
PROXY_LIST = get_proxies()
random_proxy = validate_random_proxy(PROXY_LIST)
driver = init_driver(headless=False, use_proxy=True, proxy=random_proxy)
driver.get('https://httpbin.org')
time.sleep(5)
driver.quit()
```

```
INFO:seleniumwire.proxy.client:Created proxy listening on 127.0.0.1:55318
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55319/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "acceptInsecureCerts": true, "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:55318", "sslProxy": "127.0.0.1:55318", "noProxy": ""}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--log-level=3", "--disable-blink-features", "--disable-blink-features=AutomationControlled", "--window-size=1920,1080", "--no-sandbox", "--disable-extensions", "--dns-prefetch-disable", "--disable-gpu", "--start-maximized", "--enable-automation", "--disable-infobars", "--disable-dev-shm-usage", "--disable-browser-side-navigation", "user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36", "--proxy-server=##REDACTED##"]}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "acceptSslCerts": true, "acceptInsecureCerts": true, "PageLoadStrategy": "normal", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:55318", "sslProxy": "127.0.0.1:55318", "noProxy": ""}, "goog:chromeOptions": {"excludeSwitches": ["enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--log-level=3", "--disable-blink-features", "--disable-blink-features=AutomationControlled", "--window-size=1920,1080", "--no-sandbox", "--disable-extensions", "--dns-prefetch-disable", "--disable-gpu", "--start-maximized", "--enable-automation", "--disable-infobars", "--disable-dev-shm-usage", "--disable-browser-side-navigation", "user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36", "--proxy-server=##REDACTED##"]}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:55319
DEBUG:seleniumwire.proxy.handler:accounts.google.com:443 200
DEBUG:urllib3.connectionpool:http://127.0.0.1:55319 "POST /session HTTP/1.1" 200 1066
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55319/session/9b9142354b08e759f6e59b8890ebb0bb/url {"url": "https://httpbin.org", "sessionId": "9b9142354b08e759f6e59b8890ebb0bb"}
DEBUG:seleniumwire.proxy.handler:httpbin.org:443 200
DEBUG:seleniumwire.proxy.handler:httpbin.org:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 502
INFO:seleniumwire.proxy.handler:Capturing request: https://httpbin.org/
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://httpbin.org/ 502
DEBUG:urllib3.connectionpool:http://127.0.0.1:55319 "POST /session/9b9142354b08e759f6e59b8890ebb0bb/url HTTP/1.1" 200 72
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
INFO:seleniumwire.proxy.handler:Capturing request: https://httpbin.org/favicon.ico
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://httpbin.org/favicon.ico 502
DEBUG:seleniumwire.proxy.handler:accounts.google.com:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 502
DEBUG:seleniumwire.proxy.handler:accounts.google.com:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 502
DEBUG:seleniumwire.proxy.handler:www.gstatic.com:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 101, in do_GET
    conn = self.create_connection(origin)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 166, in create_connection
    self.tls.conns[origin] = connection(proxy_config, netloc, **kwargs)
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 336, in __init__
    if self.use_proxy and proxy_config['https'].scheme.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
DEBUG:seleniumwire.proxy.handler:https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin 502
INFO:seleniumwire.proxy.client:Destroying proxy
DEBUG:seleniumwire.proxy.storage:Cleaning up /Users/keeon/.seleniumwire/storage-5ac44fb2-09ac-412f-8752-9fe12349a3cf
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://127.0.0.1:55319/session/9b9142354b08e759f6e59b8890ebb0bb {"sessionId": "9b9142354b08e759f6e59b8890ebb0bb"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55319 "DELETE /session/9b9142354b08e759f6e59b8890ebb0bb HTTP/1.1" 200 72
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```

Seems bizarre that a 200 to the intended URL is yielded and then a 502 after loading some rogue google resource?

```
...
DEBUG:seleniumwire.proxy.handler:httpbin.org:443 200
DEBUG:seleniumwire.proxy.handler:httpbin.org:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
```

I feel like I'm out of options and maybe should try doing this all through a gecko/firefox driver.

cc @wkeeling 🙏🏼

**Comment by wkeeling** [comment]
@KeeonTabrizi thanks. Looking at the traceback, the error is occurring because the proxy config being passed for the https proxy setting is not in a valid format. It's missing the scheme which is the "https" part of the URL. Before version 1.0.12 the code was more permissive, and would work if the scheme was missing.

The format needs to be:

        swire_options['proxy'] = {
            'http': 'http://server:port',
            'https': 'https://server:port',
        }

It would be worthwhile printing out the value of the `proxy` variable to see what format is coming through.

**Comment by KeeonTabrizi** [comment]
@wkeeling Thanks so much for the response. Tremendously appreciated.

>It would be worthwhile printing out the value of the proxy variable to see what format is coming through.

To note my `proxy` variable would return a string of this format `subdomain.domain.tld:port`.

Based on your diagnosis I modified the dictionary as follows:

```python
        swire_options['proxy'] = {
            'http': 'http://' + proxy,
            'https': 'https://' + proxy,
        }
```

This does indeed allow later versions of seleniumwire to work with my proxy configuration and I no longer receive the _502 Bad Gateway Error_ ✅ . Thank you for the diagnosis and insight for this fix.

**Interestingly** (and this may be worthy of a new issue) - with my proxy working I was able to run a series of tests (3x per selenium version) in a relatively controlled environment and am noticing serious performance degradation in i/o waiting for requests to return in v1.2.0+.

Here are the details of my experiment.

```
Python: 3.6.8
Selenium: 3.141.0
IDE: PyCharm Pro 2020.1
Fixed Proxy Resource

3 trials per seleniumwire version.
Test uses seleniumwire+selenium to fetch sequentially 2 urls, and extract similar background requests (stored in a temp object)
and then combine the results of 2 background requests from the 2 urls.

| swire_version  | run_time_min       | avg_run_time_min    |
| -------------- | ------------------ | ------------------- |
| 1.0.7          | [.63, .68, .61]    | .64                 |
| 1.0.8          | [.72, .68, .63]    | .68                 |
| 1.0.9          | [.66, .62, .65]    | .64                 |
| 1.0.10         | [.69, .59, .74]    | .67                 |
| 1.0.11         | [.73, .60, .65]    | .66                 |
| 1.0.12         | [.70, .67, .68]    | .68                 |
| 1.1.0          | [.61, .67, .73]    | .66                 |
| 1.1.1          | [.70, .61 ,.65]    | .65                 |
| 1.1.2          | [.63, .66, .68]    | .66                 |
| 1.2.0          | [2.66, 2.53, 2.56] | 2.58                |
| 1.2.1          | [2.50, 2.59, 2.57] | 2.45                |
| 1.2.2*         | [2.57, 2.60, 2.52] | 2.31                |
```

I'm seeing a clear pattern that at the v1.2.0+ release I'm getting a significant performance hit in requests/traffic flowing. I ran selenium in non-headless and could see it was just taking significantly longer for requests to complete, the pages to render, and assumingely the background request object to become available to extract. 

Visual of `avg_run_time_min`:
![image](https://user-images.githubusercontent.com/3408390/85076145-72e2a480-b174-11ea-988b-353b6ac03e61.png)

Note the `*` on v1.2.2 in the trial/table data is that a new unseen exception started popping up only on this version (which my code broadly retries when fetching the resource):
```
ERROR:seleniumwire.proxy.handler:Error making request
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    res = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by wkeeling** [comment]
@KeeonTabrizi glad to hear that the proxy configuration is now working.

Thank you for the excellent performance data. Performance degradation is something that other people have also reported, and I think it is down to a recent change to Selenium Wire to turn connection keep-alive on by default. The idea with connection keep-alive is to improve performance by reusing TCP connections. However, in some cases (and it seems yours) this appears to be having the exact opposite effect.

Turning off connection keep-alive seems to improve things considerably. You can do this with the `connection_keep_alive` option - e.g.

```
swire_options['connection_keep_alive'] = False
```

Or alternatively upgrade to the latest version of Selenium Wire (v1.2.3) which has connection keep-alive switched off by default.

With regard to the `Remote end closed connection without response` message, this could be due to a request timing out inside Selenium Wire. This may resolve once connection keep-alive has been switched off, but it may be worth increasing the connection timeout using the `connection_timeout` option - e.g.

```
swire_options['connection_timeout'] = 20
```

**Comment by KeeonTabrizi** [comment]
@wkeeling Thanks again.

`v1.2.3` had a normal run time. When I set `connection_keep_alive` back to `True` then the degradation occurred. Setting the parameter to `False` for `v1.2.2` also resulted in a normal run time.

Regarding the `Remote end closed connection without response` exception and your suggestion to add the `connection_timeout` parameter. For all those trials/tests that parameter had always been set to `20` in my `swire_options`, so I don't think that helped for that issue.

I'll be upgrading to `v1.2.3` now.
