### ISSUE TITLE
DEL SPECIFIC REQUEST IN DRIVER.REQUESTS

### ISSUE THREAD

**Issue by P-Leo10** [wkeeling/selenium-wire#246]
Hi!
I'm here again haha!

this time I would like to know how I can delete a specific request from the driver.requests list, without deleting all the others. I tried these ways, to no avail:

`del driver.requests[index]`

```
request = driver.wait_for_request('/BetsWebAPI/placebet', timeout=2)
driver.requests.remove(requests)
```

```
request = driver.wait_for_request('/BetsWebAPI/placebet', timeout=2)
driver.requests = driver.requests.remove(requests)
```

I'm using seleniumwire version 2.0.0 and I needed it to stay that way, because of mitmproxy.

**Comment by wkeeling** [comment]
Hi, unfortunately there's no way to remove a specific request from the stored requests at the present time. The only way round that would be to copy the requests into a separate list filtering out those you're not interested in. For example, if the index of the uninteresting request happened to be 3:

```
index = 3
requests = [r for i, r in enumerate(driver.requests) if i != index]
```
or by path:
```
path = '/BetsWebAPI/placebet'
requests = [r for r in driver.requests if path not in r.url]
```

**Comment by P-Leo10** [comment]
the problem is that the `wait_for_request` is in a loop, that is, if I don't delete the `driver.requests`, it will always be getting the same request that I would like to disregard

**Comment by wkeeling** [comment]
You could try deleting the requests out of the request storage index. It's an internal API but might get you what you want. You can access the index with:

```
driver.proxy.storage._index
```
