### ISSUE TITLE
other chrome options

### ISSUE THREAD

**Issue by siparker** [wkeeling/selenium-wire#25]
I am using selenium chrome for a couple of projects and was wondering what the correct format is to add some existing options into selenium wire instead of standard selenium.

currently, i have the following for example.

`options = webdriver.ChromeOptions()

    options.add_argument('--no-sandbox')

    options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36")

    options.add_argument("--disable-default-apps")

    options.add_argument("--lang=en,en-US")

    PROXY = "111.222.33.44:1234"

    options.add_argument('--proxy-server=%s' % PROXY)

    chrome_driver = "C:\\chromedriver_win32\\chromedriver.exe"

    options.add_argument("user-data-dir=C:\chromeprofiles\Profile 2")

`

I then start the webdriver using 

`driver = webdriver.Chrome(chrome_options=options, executable_path=chrome_driver)`

I changed the chrome_options to be seleniumwire_options and reformatted the proxy settings to follow your example 

I am wondering if you support the other arguments above and what the format is used as i am not entirely sure based on the docs.

and a huge thanks for solving my longest running problem!! getting access to the network requests :-)

**Comment by wkeeling** [comment]
@siparker you should be able to keep the `ChromeOptions` largely the same and just split out the proxy settings. The proxy settings have to be passed in separately via the `seleniumwire_options` argument. For example:

    from seleniumwire import webdriver

    options = webdriver.ChromeOptions()
    options.add_argument('--no-sandbox')
    options.add_argument(
            "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36")
    options.add_argument("--disable-default-apps")
    options.add_argument("--lang=en,en-US")
    options.add_argument("user-data-dir=C:\chromeprofiles\Profile 2")
    chrome_driver = "C:\\chromedriver_win32\\chromedriver.exe"

     # Proxy settings must be defined separately
    seleniumwire_options = {
        'proxy': {
            'http': 'http://111.222.33.44:1234',
            'https': 'https://111.222.33.44:1234',
        }
    }

    driver = webdriver.Chrome(
        chrome_options=options, 
        seleniumwire_options=seleniumwire_options, 
        executable_path=chrome_driver
    )

Let us know if you hit any issues with that.

**Comment by siparker** [comment]
Hi, that works a treat.

got some other issues with speed on loading but will raise another issue for that.
