### ISSUE TITLE
Unable to use a proxy

### ISSUE THREAD

**Issue by danny408** [wkeeling/selenium-wire#250]
I am trying to use a proxy with it (USER:PASS) via loaded extension and use seleniumwire to parse the network traffic and see the outgoing headers. It seems that they will not work together. I either will just have seleniumwire and my proxy doesnt work (whatismyip on the chromedriver instance shows my actual ip) or my proxy will work but seleniumwire will not pick up any request details.

**Comment by wkeeling** [comment]
Thanks for this and sorry for the delay in replying. Selenium Wire works by redirecting traffic through a local proxy server it spins up in the background. The extension you are using will be overwriting the local proxy settings meaning the browser will bypass Selenium Wire and so will not capture any requests.

To specify an upstream proxy you will need to use the [`proxy`](https://github.com/wkeeling/selenium-wire#proxies) option in the seleniumwire_options. From what you described you have done this but the proxy doesn't seem to be taking effect? Are you able to share some code?
