### ISSUE TITLE
How to stop seleniumwire from dissalowing sites to do requests?

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#251]
I literaly can't click any button that would launch a request to another site, when using selenium wire. It partially even dissalows the websites request to load, on this website the authorize apis button for example will always throw an error because it can't connect to it's backend https://developers.google.com/oauthplayground/

**Comment by wkeeling** [comment]
It seems OK when I visit https://developers.google.com/oauthplayground/, select some APIs and press the 'Authorize APIs' button.

Can you share the code you're using?

**Comment by Avnsx** [comment]
> It seems OK when I visit https://developers.google.com/oauthplayground/, select some APIs and press the 'Authorize APIs' button.
> 
> Can you share the code you're using?

I use it in combination with undetected chromedriver

**Comment by Avnsx** [comment]
@wkeeling 
```python
import undetected_chromedriver as uc
from seleniumwire import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.action_chains import ActionChains

chrome_options = webdriver.ChromeOptions()
chrome_options.headless = False
driver = uc.Chrome(options=chrome_options)

driver.get('https://developers.google.com/oauthplayground/')
WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, '#scopes'))).send_keys('https://www.googleapis.com/auth/cloud-platform')
WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#authorizeApisButton'))).click()
```

**Comment by wkeeling** [comment]
I managed to get the above code to work, but I needed to add an explicit `time.sleep()` after the request to set the scope. Without the sleep, it seems that the first `WebDriverWait()` call doesn't wait long enough for the Authorize APIs button to enable itself. 
So I did:

```python
WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, '#scopes'))).send_keys('https://www.googleapis.com/auth/cloud-platform')
time.sleep(3)
WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#authorizeApisButton'))).click()
```
I didn't see any other errors though, so perhaps there's something else happening in your environment.
