### ISSUE TITLE
How to install selenium-wire with conda?

### ISSUE THREAD

**Issue by nrllh** [wkeeling/selenium-wire#253]
I have to install selenium-wire with conda. The only thing I could find is here: [https://anaconda.org/ralexx/selenium-wire](https://anaconda.org/ralexx/selenium-wire). But it didn't work. Is there any way to deploy selenium-wire in conda?

(I use ubuntu desktop)

**Comment by masudr4n4** [comment]
make sure you have pip in your conda environments.Whats the error it showing?

**Comment by nrllh** [comment]
@masudr4n4 thanks
