### ISSUE TITLE
Delete requests/take current requests

### ISSUE THREAD

**Issue by voxvici** [wkeeling/selenium-wire#255]
Hi,
Thank you for an awesome module. Is there a way to take requests only from the current page the driver is on? or delete previous requests? even matching specific requests with regex and cutting the list down would be great because we have quite a bit of requests during extraction and looping through all of them all the time is a lot of unnecessary data. Is there a way to reduce it? thank you

**Comment by wkeeling** [comment]
Thanks for the issue. 

Yes you can delete previously captured requests with:

```
del driver.requests
```
That will clear out all requests captured up to that point. It's mentioned in the docs in the [Accessing Requests section](https://github.com/wkeeling/selenium-wire#accessing-requests) but admittedly not very obvious!

You can also restrict what requests are captured using [`driver.scopes`](https://github.com/wkeeling/selenium-wire#limiting-request-capture). That takes a list of regular expressions which match on specific request URLs - e.g.

```
# Only capture requests that match these regexes
driver.scopes = [
    '.*myserver.com.*',
    '.*otherserver.com/some/path.*'
    # ... etc ...
]

driver.get(...)  # Start making requests
```

**Comment by voxvici** [comment]
Thank you
