### ISSUE TITLE
Changing proxy settings on the fly

### ISSUE THREAD

**Issue by webassets** [wkeeling/selenium-wire#257]
How can I do it?

**Comment by wkeeling** [comment]
Yes it is possible to do this, but currently there is no public API so you will need to use an internal API to achieve it. You should be able to switch the proxy settings for an existing driver like this:

```
driver.proxy._master.options.update(
    mode='upstream:https://new_proxy_host:new_port'
)
```

Substitute `new_proxy_host` and `new _port` for your new values accordingly, but leave everything else the same.

Switching the proxy settings on the fly has been requested a few times so I wonder whether we should create a friendly API to do it. Lets leave this ticket open and I will investigate what we can do.

**Comment by wkeeling** [comment]
Implementation thoughts:
```python
driver.seleniumwire_options.proxy = {
    'https': 'https://server:port',
}
```

**Comment by joelluijmes** [comment]
Hi, quick follow up question. How would I use this when my proxy has authentication?

```python
proxy = f"http://{username}:{password}@{server}:{port}"
self.driver.proxy._master.options.update(
    mode=f"upstream:{proxy}"
)
```

Yields
```
 File "/Users/joell/joell.dev/Scraper/selenium-scraper/src/scrapers/galeria.py", line 78, in reset_driver
    self.driver.proxy._master.options.update(
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 223, in update
    u = self.update_known(**kwargs)
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 215, in update_known
    self.changed.send(self, updated=updated)
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/addonmanager.py", line 119, in _configure_all
    self.trigger("configure", updated)
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/addonmanager.py", line 256, in trigger
    self.invoke_addon(i, name, *args, **kwargs)
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/addonmanager.py", line 237, in invoke_addon
    func(*args, **kwargs)
  File "/Users/joell/joell.dev/Scraper/selenium-scraper/env/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/addons/core.py", line 61, in configure
    raise exceptions.OptionsError(str(e)) from e
seleniumwire.thirdparty.mitmproxy.exceptions.OptionsError: Invalid server specification:
```

**Comment by wkeeling** [comment]
Good point. The username and password have to be passed separately using the `upstream_auth` attribute when changing the proxy on the fly:

```python
self.driver.proxy._master.options.update(
    mode=f"upstream:http://{server}:{port}",
    upstream_auth=f"{username}:{password}"
)

**Comment by hp20202006** [comment]
Hi , thank you for the solution. I have problem that the ip do not change anymore after the first time it changed on the fly.
what's wrong in my code ? Thank you very much !
![image](https://user-images.githubusercontent.com/67665309/119542141-c6686400-bdc1-11eb-9ee7-4239de2b96b2.png)

**Comment by hp20202006** [comment]
Hi , thank you for the solution. I have a problem that the IP do not change anymore after the first time it changed on the fly.
what's wrong in my code ? Thank you very much !
![image](https://user-images.githubusercontent.com/67665309/119542514-370f8080-bdc2-11eb-857a-af199ac10171.png)

**Comment by hp20202006** [comment]
Hi @natalka-me .
Its my mistake. The ip actually changed each time the code run. I don't know why it stays the same in google search . You can check it in other website for ip checking.

**Comment by natalka-me** [comment]
@hp20202006 thank you for pointing that out. 
But I actually do use some ip servcie, not google, I tried to change url with get params for this service, I even tried and set up my own ip checking page. And ip remains the same after the first driver.proxy._master.options.update(...)
Could you tell which service did you use to check the ip. Is it cached in my case or what this can be...

**Comment by hp20202006** [comment]
Hi @natalka-me 
you can set a time.sleep and open a new tab to https://www.whatismyip.com/ manually . you will see you ip is changed there.

**Comment by natalka-me** [comment]
> Hi! I have the same issue, as @hp20202006 has in previous comment.
> The proxy changes only the first time, and then there remains the first proxy set.
> Please help, what could go wrong?

Thank you @hp20202006
Tried changing url with params, tried deleting driver.requests... but
Seems that IP changes in IP checker service only when I use each time **another** checking service :)
And for the same IP checker IP stays the same as first updated with driver.proxy._master.options.update.
Thank you for your help :)

**Comment by pschwien82** [comment]
Upvoting this.
Until it makes it into a working version, is there a way to set username and password in the meantime similarly to setting host and port?
```
driver.proxy._master.options.update(
    mode='upstream:https://new_proxy_host:new_port'
)
```

**Comment by HMaker** [comment]
> Good point. The username and password have to be passed separately using the `upstream_auth` attribute when changing the proxy on the fly:
> 
> ```python
> self.driver.proxy._master.options.update(
>     mode=f"upstream:http://{server}:{port}",
>     upstream_auth=f"{username}:{password}"
> )
> ```

Was it exposed to the public API? This is a usefull feature specially for scrapers.

**Comment by wkeeling** [comment]
It's on the way: https://github.com/wkeeling/selenium-wire/pull/371

**Comment by HMaker** [comment]
I added this method to chrome subclass
```python
from urllib.parse import urlparse, urlunparse

def update_proxy(self, url: str):
    parsed = urlparse(url)
    if parsed.username is not None:
        new_url = urlunparse(parsed._replace(
            netloc=f'{parsed.hostname}:{parsed.port}' if parsed.port is not None else parsed.hostname
        ))
        self.proxy.options.update(
            mode=f'upstream:{new_url}',
            upstream_auth=f'{parsed.username}:{parsed.password}'
        )
    else:
        self.proxy.options.update(mode=f'upstream:{url}', upstream_auth=None)
```

**Comment by wkeeling** [comment]
From v4.5.0 this can now be achieved with:

```python
driver.proxy = {
    'https': 'https://username:password@server:port',
}
```
[Link to docs](https://github.com/wkeeling/selenium-wire#switching-dynamically)
