### ISSUE TITLE
set_wakeup_fd only works in main thread on driver.quit()

### ISSUE THREAD

**Issue by wahost070** [wkeeling/selenium-wire#258]
Hi there, I am using the following code where I use seleniumwire to get the requests to the website, and then print out the array of urls that match the key term. However, I'm getting a strange error which I cannot understand `Exception in thread Selenium Wire Proxy Server, ValueError: set_wakeup_fd only works in main thread`

Here is my python code (stripped for confidentiality)
```python
from chromedriver_py import binary_path # this will get you the path variable
from selenium.webdriver.chrome.options import Options
from seleniumwire import webdriver as sw_webdriver  # Import from seleniumwire
import time

options = Options()
options.add_argument("--headless")
options.add_argument("--silent")
options.add_argument("--disable-gpu")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36")
options.add_experimental_option('excludeSwitches', ['enable-logging'])

driver = sw_webdriver.Chrome(options=options, executable_path=binary_path)
driver.delete_all_cookies()

driver.get('https://www.website.com/app/')
time.sleep(5)

try:
    # gets the jwt token from the website
    jwt = driver.execute_script("return window.localStorage.getItem('t');")
except Exception as e:
    print("Exception fetching jwt token")

# next step, make a request to the website (assuming the token has also been set for the session)
driver.get("https://www.website.com/confidential-url")
time.sleep(10)

requests_arr = []
request_data_structure = []

for request in driver.requests:
    if request.response and 'key_term_to_find' in request.url:
        requests_arr.append(request.url)
        
print(requests_arr)
driver.quit()

```

This is the error which gets displayed. It only shows when calling `driver.quit()`
```
Exception in thread Selenium Wire Proxy Server:
Traceback (most recent call last):
  File "C:\Users\pyuser\.pyenv\pyenv-win\versions\3.8.0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\pyuser\.pyenv\pyenv-win\versions\3.8.0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pyuser\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\seleniumwire\server.py", line 76, in serve_forever
    self._master.run_loop(self._event_loop)
  File "C:\Users\pyuser\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\seleniumwire\thirdparty\mitmproxy\master.py", line 90, in run_loop
    loop.close()
  File "C:\Users\pyuser\.pyenv\pyenv-win\versions\3.8.0\lib\asyncio\proactor_events.py", line 679, in close
    signal.set_wakeup_fd(-1)
ValueError: set_wakeup_fd only works in main thread
```

**Comment by wkeeling** [comment]
Thanks for raising this. I've not seen that particular error before. I'll investigate and see what could be causing it.

**Comment by wahost070** [comment]
Thank you @wkeeling for having a look. Please let me know if you require any more information from me.

In the meantime, if anyone is also having the same issue, here is my (not very clean) workaround until this issue has been solved:

Assuming you have your `driver = YourWebdriver()` code already. 

```python
import psutil
import os

# in place of driver.quit():

# get the process ID of your driver
p = psutil.Process(driver.service.process.pid)

# recursively get the process ID of the children
proc_children = p.children(recursive=True)


try:
    # send a term signal to the driver itself
    os.kill(driver.service.process.pid, signal.SIGTERM)

    # for each sub process, send a term signal
    for proc in proc_children:
        os.kill(proc.pid, signal.SIGTERM)
except Exception as e:
    pass
```

**Comment by wkeeling** [comment]
One side effect of not calling `driver.quit()` is that Selenium Wire won't clean out it's temporary request storage. You might want to do that manually as part of your workaround above, so that the storage doesn't keep growing in size. To manually clear the requests, you do:
```
del driver.requests
```

**Comment by wahost070** [comment]
Great, thanks for pointing that out! :)

**Comment by nium9** [comment]
is there any updates on this as i am having the same issues

**Comment by wkeeling** [comment]
@nium9 I haven't yet had a chance to investigate. I assume you're also seeing the issue when you call `driver.quit()`?

**Comment by nium9** [comment]
yep but mine just crashes before it hits driver.quit() but using what @wahost070 said and some forum post saying to upgrade python i upgraded to python 3.9.4 and it seems to be working fine with no crashes

**Comment by wkeeling** [comment]
Ok great. What version of Python were you previously using when you were seeing the issue?

**Comment by nium9** [comment]
3.8.2 i believe

**Comment by wahost070** [comment]
Thanks for the suggestion @nium9 I'll try updating my program to 3.9.4.

**Comment by wahost070** [comment]
Updating to a later version of Python has fixed this issue.
