### ISSUE TITLE
temp files eat up space

### ISSUE THREAD

**Issue by steathy** [wkeeling/selenium-wire#259]
I found sw temp files are stored in .seleniumwire folder. It quickly eats up my harddrive. Is there anyway to not save every request&response files or clean them up automatically?

Thanks

**Comment by wkeeling** [comment]
There are [various ways](https://github.com/wkeeling/selenium-wire#limiting-request-capture) to restrict the requests that Selenium Wire captures, including scoping capture with `driver.scopes`, excluding certain hosts, aborting requests and disabling capture entirely (if you were only interested in non-capture related functionality). 

In addition, the request storage folder is cleaned up when you call `driver.quit()`, but you can clear out requests before then by running:

```
del driver.requests
```
That will delete all requests captured up to that point.

Hope that helps.

**Comment by Davincible** [comment]
Hm yeah was just about to open a similar issue as I now have a 20gb seleniumwire folder. Not sure if its not cleaned up due to driver.quit not getting called during test crashed

**Comment by wkeeling** [comment]
It's probably a good idea to put `driver.quit()` in a `finally` block to ensure it gets called even in the event of a crash, e.g.

```
driver = webdriver.Chrome()

try:
    driver.get(...)
finally:
    driver.quit()
```

For a belt and braces approach, you can also call `del driver.requests` periodically in your code after you have finished processing the requests.

**Comment by steathy** [comment]
> It's probably a good idea to put `driver.quit()` in a `finally` block to ensure it gets called even in the event of a crash, e.g.
> 
> ```
> driver = webdriver.Chrome()
> 
> try:
>     driver.get(...)
> finally:
>     driver.quit()
> ```
> 
> For a belt and braces approach, you can also call `del driver.requests` periodically in your code after you have finished processing the requests.

Thank you!

I'll run the del command in every loop then.

Also is it possible to implement an option to completely turn off this auto-save/log feature? I guess most users would not need to save all the requests & responses.

**Comment by wkeeling** [comment]
You can completely turn off request capture with the `disable_capture` option:
```
options = {
    'disable_capture': True  # Pass all requests straight through
}
driver = webdriver.Chrome(seleniumwire_options=options)
```
If you just want to disable capture for certain requests, then you should use [driver.scopes](https://github.com/wkeeling/selenium-wire#limiting-request-capture).

**Comment by steathy** [comment]
> You can completely turn off request capture with the `disable_capture` option:
> 
> ```
> options = {
>     'disable_capture': True  # Pass all requests straight through
> }
> driver = webdriver.Chrome(seleniumwire_options=options)
> ```
> 
> If you just want to disable capture for certain requests, then you should use [driver.scopes](https://github.com/wkeeling/selenium-wire#limiting-request-capture).

Thank you! 

> You can completely turn off request capture with the `disable_capture` option:
> 
> ```
> options = {
>     'disable_capture': True  # Pass all requests straight through
> }
> driver = webdriver.Chrome(seleniumwire_options=options)
> ```
> 
> If you just want to disable capture for certain requests, then you should use [driver.scopes](https://github.com/wkeeling/selenium-wire#limiting-request-capture).
