### ISSUE TITLE
chrome doesn't store disk cache 

### ISSUE THREAD

**Issue by apollo17march** [wkeeling/selenium-wire#260]
chrome doesn't store disk cache when website opened from selenium-wire

**Comment by wkeeling** [comment]
Thanks for this. Can you share some example code that demonstrates the problem?

**Comment by apollo17march** [comment]
When {'disable_capture': True} is set chrome keeps disk cache normally, but then upstream authenticated proxy doesn't work. 
I want to use authenticated proxy (basic http auth) proxy without capturing request(with disk cache). But for me proxy and caching has become mutually exclusive right now.

**Comment by wkeeling** [comment]
Ok that's strange. I'll try and reproduce with my own upstream authenticated proxy. Are you seeing any specific error message?

**Comment by apollo17march** [comment]
@wkeeling no error messages found. Also , the proxy doesn't work means browser asks me to enter username and password for the proxy in the popup message. 
selenium-wire==4.2.3
selenium==3.141.0
docker selenium hub+node chrome == 3.141.59-zirconium
also the problem is same when standalone server is used on host system 
selenium-server-standalone-3.141.59.jar
chromedriver: 89.0.4389.23
chrome browser: 89.0.4389.114

**Comment by wkeeling** [comment]
> disk cache was checked by visiting network tab in developer tool. and in the disk cache location, when first page loads cache was being generated but it was deleted right then before sending another request.

OK I misunderstood. When you said "disk cache" I thought you were talking about Selenium Wire's request storage which is controlled by the `disable_capture` option. But it sounds as though you're actually talking about Chrome's own disk cache? Are you able to post a screenshot for where I can find this disk cache setting in Chrome's network tab? This should be unrelated to `disable_capture`.

**Comment by apollo17march** [comment]
![image](https://user-images.githubusercontent.com/1325453/114022037-11b9c800-9891-11eb-9ca5-b7638f34c4a0.png)
you can see resources loading from disk cache in size tab of the picture. 
In ubuntu, chrome stores that in ~/.cache/google-chrome/ location 
when using chromedriver we can specify this location like webdriver.ChromeOptions().add_argument('--disk-cache-dir=/tmp/cache')

**Comment by wkeeling** [comment]
The issue with proxy auth not working when `disable_capture` is `True` is fixed in 4.2.4. 
@apollo17march are you able to confirm?

**Comment by wkeeling** [comment]
I should mention that when `disable_capture` is `True`, Selenium Wire will not store requests (`driver.requests` will be empty). However, `disable_capture` is specific to Selenium Wire and it won't affect Chrome's own disk cache.

**Comment by nium9** [comment]
is this a way to stop it storing on the hard disk in the .seleniumwire folder and keep driver.requests
