### ISSUE TITLE
response._transferSize not available in har file.

### ISSUE THREAD

**Issue by apollo17march** [wkeeling/selenium-wire#263]
Normally har downloaded from browser consists **_transferSize** response field which accounts for total network data transfer. I didn't find this in har generated using selenium wire.

**Comment by wkeeling** [comment]
Thanks for raising this.

The `_transferSize` field looks to be Chrome specific, as possibly denoted by the leading underscore. Firefox doesn't seem to generate it. The [official spec](https://w3c.github.io/web-performance/specs/HAR/Overview.html) also doesn't seem to mention it, but then that spec has long been abandoned by the looks of it.

In any case, the total network data transfer can be calculated by adding the `headersSize` and `bodySize` values together - both of which are present in Selenium Wire's HAR output.
