### ISSUE TITLE
request interceptor loop

### ISSUE THREAD

**Issue by converge** [wkeeling/selenium-wire#265]
Hi,

is this a bug?

```python
from seleniumwire import webdriver
import time

driver = webdriver.Firefox()

def interceptor(request):
    print('ok')
    request.headers['HELLO'] = 'Some Value'

# remove this comment to activate the sleep(3), and it will print "ok" many times, header will be also duplicated many times
# time.sleep(3)
driver.request_interceptor = interceptor
driver.get("https://httpbin.org/headers")
time.sleep(3)
driver.get("https://httpbin.org/headers")
```

**Comment by wkeeling** [comment]
The above code doesn't seem to generate duplicate headers for me. The response from https://httpbin.org/headers shows a single header called "Hello" for both requests. I also see the "ok" printed twice in the console, once for each request.

**Comment by wkeeling** [comment]
@converge are you still having an issue with this?

**Comment by converge** [comment]
@wkeeling thanks for asking.

I spent some time trying to debug it, but couldn't find the reason. I was using a new virtual env/isolation to avoid external interference, but was still having having the issue.

I rolled back to a previous version that doesnt have the interceptors implementation, but uses another approach to update header to solve my issue.
