### ISSUE TITLE
Custom headers are not always present

### ISSUE THREAD

**Issue by kenygamer** [wkeeling/selenium-wire#266]
## Issue description
It strikes me that when I add custom headers to Chrome browser using wkeeling/selenium-wire, the headers sometimes apply and sometimes do not.

## Code to reproduce
```python
from seleniumwire import webdriver
custom_headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
}

driver = webdriver.Chrome()

def request_interceptor(request) : 
    request.headers = custom_headers; 

driver.request_interceptor = request_interceptor;
driver.get(url)
print(driver.page_source)
```

### Local test
https://bit.ly/3da3X1S
![](https://i.ibb.co/2Z7vCv9/13-FE1218-AF9-C-40-B2-A6-D9-B763-DDDCFDB9.png)
### Chrome automation test
https://bit.ly/3mIbS9H
![](https://i.ibb.co/NVrjM6P/9-A1-DBF44-84-E6-4-E01-B80-B-3-BC80854-AB5-C.png)

**Comment by kenygamer** [comment]
It is worth noting that using the undetected-chromedriver module, the browser name successfully updates (but not to the custom browser set).

![](https://i.ibb.co/j3B7Wx1/62-E03903-23-D3-4-A10-90-C8-21040-A80279-F.png)

Without also deviating from the central topic, what about these red indicators using the module? Will this affect tests in other bot-protected sites?

**Comment by wkeeling** [comment]
Thanks for raising this.

This is possibly happening because you're assigning a dictionary to `request.headers` and overwriting the dictionary-like object that holds the existing headers.

To replace an existing header such as the user-agent, you'll need to [remove it first and then add it](https://github.com/wkeeling/selenium-wire#example-replace-an-existing-request-header):

```python
def request_interceptor(request) : 
    del request.headers["User-Agent"]
    request.headers["User-Agent"] = custom_headers["User-Agent"]
```

**Comment by kenygamer** [comment]
Thank you.

![](https://i.ibb.co/j3B7Wx1/62-E03903-23-D3-4-A10-90-C8-21040-A80279-F.png)
