### ISSUE TITLE
SSL proxy terminates connection abruptly

### ISSUE THREAD

**Issue by eqMFqfFd** [wkeeling/selenium-wire#267]
## Issue description
I am having an issue when trying to use wkeeling/selenium-wire to connect to some particular sites using proxied connection.

For example, I can load my local server, or the Google page successfully with an SSL proxy, but I can't recreate the same success on some particular sites, such as https://bit.ly/3dW6oo2

As my previous experience with SSL sites suggests, this issue occurs in the SSL handshake, so disabling peer verification in other projects has allowed me to strike oil. 

## Code to reproduce
```python
from seleniumwire import webdriver
seleniumwire_options = {
    "backend": "mitmproxy",
    "disable_capture": False,
    "verify_ssl": False,
    "connection_keep_alive": False,
    "max_threads": 3,
    "connection_timeout": None,
    "proxy": {
        "https": "[redacted]"
     }
}
driver = webdriver.Chrome(seleniumwire_options = seleniumwire_options);
driver.get("https://bit.ly/3a5ySe1");
```

## Console logs
```python
File "selenium.py", line 104, in <module>
    driver.get(url)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: headless chrome=89.0.4389.90)
```

### Google test [passed]
https://www.google.com/?client=chrome
### Remote test [failed]
https://bit.ly/3a5ySe1

**Comment by wkeeling** [comment]
Thanks for raising this. I'm wondering whether the issue may be related to HTTP2, as I've recently experienced something similar when using a HTTPS upstream proxy when HTTP2 was in use. Could you try adding the following option to your `seleniumwire_options`:

```
'mitm_http2': False
```

Adding that option fixed the issue I was having, so I'd be interested to know whether it fixes yours.

**Comment by wkeeling** [comment]
@kenygamer wondering whether you might have had a chance to try setting `'mitm_http2': False`?

The funko.com site loads OK for me using my own SSL proxy, but as mentioned I've had issues with other sites which the `'mitm_http2': False` option seemed to fix.

**Comment by nvkie** [comment]
@wkeeling

**Comment by wkeeling** [comment]
@eqMFqfFd are you still having an issue with this?
