### ISSUE TITLE
Enabling selenium-wire gives me hcaptcha and 403 errors, normal selenium works fine

### ISSUE THREAD

**Issue by vanjavk** [wkeeling/selenium-wire#270]
I tried with only selenium site loads normally, but using selenium-wire, the site doesn't load.

This will work:
```
from selenium import webdriver  # THIS WILL LOAD SITE
driver = webdriver.Firefox()
driver.get("https://bitclout.com/log-in")
```

This won't work:

```
from seleniumwire import webdriver  # THIS WILL GIVE HCAPTCHA & 403
driver = webdriver.Firefox()
driver.get("https://bitclout.com/log-in")
```

I have tried installing cert (now shows padlock but still error), using mitm proxy but still same problem, tried undetected_chromedriver but nothing changed.

**Comment by wkeeling** [comment]
Thanks for this. The site renders ok for me when I point Selenium Wire at it - I don't see a hcaptcha or any error. Not entirely sure why you're getting the hcaptcha and I'm not. What version of Selenium Wire, Python and OS are you running?

**Comment by vanjavk** [comment]
> Thanks for this. The site renders ok for me when I point Selenium Wire at it - I don't see a hcaptcha or any error. Not entirely sure why you're getting the hcaptcha and I'm not. What version of Selenium Wire, Python and OS are you running? Also, are you using an upstream proxy?

Wow, this morning it's working fine for me as well, I didn't even restart the computer! I'm running on Windows, 4.2.4 wire, python v3.8.7:6503f05. I also have tried resetting my IP and trying the same setup on my laptop yesterday and I had exact same outcome, raw selenium worked, selenium-wire didn't.

It's something with the site, but also definitely something with selenium-wire because raw selenium didn't trigger it ever.

I'll close the issue for now and see if it repeats sometime in the future.

**Comment by vanjavk** [comment]
So after it working a little in the morning it stopped working a few hours later. I really feel like they're somehow fingerprinting my browser, but only selenium-wire. 

After it stopped working I tried it on my laptop, connected to neighbor wifi, used VPN, and still got the exact same message, this is why I think it's not IP related because there's no way they could have connected those 2 things.

Could you perhaps try now? You're probably asleep now though and magic might do its thing by morning, this is exactly how the site should look like if it works:

![firefox_FltmZmtqRA](https://user-images.githubusercontent.com/1491765/115130020-19454380-9fec-11eb-9b8a-c3a084c7fc8c.png)

In case textarea to input your seed is not loaded it's very likely that after 1 refresh (F5), it will display hcaptcha.

**Comment by wkeeling** [comment]
Tried again this morning. Initially, the site was loading on the first load, but pressing F5 to refresh would throw up the hcaptcha. But then after few minutes F5 was reloading the login page just fine without the hcaptcha. So the behaviour seems a little random, but I suspect you could be right on the fingerprinting hypothesis.

[This ticket](https://github.com/wkeeling/selenium-wire/issues/215) talks about a similar thing. It's possible that the target site may be doing some fingerprinting during the SSL handshake. Because Selenium Wire intercepts HTTPS traffic it means that Selenium Wire, not the browser, is performing the handshake with the site. The site may be able to detect that, although I have no hard evidence to back that up currently. It's going to need some further investigation I think.

**Comment by vanjavk** [comment]
Thanks for response!

So if I see correctly, there's no solution to this? Is there an alternative? Is it possible to capture requests through chrome addon somehow and send it to python or something? I just need to intercept them without changing anything, so just reading them, if u can think of any alternatives that could work I would be glad to hear.

**Comment by wkeeling** [comment]
There's no solution currently, although I'd like to investigate some more if I can at some point. Some people have mentioned this: https://stackoverflow.com/questions/55582136/how-to-set-proxy-with-authentication-in-selenium-chromedriver-python - so perhaps that could offer a solution for the time being. Sorry not being more help!

**Comment by wkeeling** [comment]
Related #215
