### ISSUE TITLE
wait_for_request timeout exception?

### ISSUE THREAD

**Issue by Chris230291** [wkeeling/selenium-wire#272]
Hello. Does anyone know how to do something if the wait times out?

`url= driver.wait_for_request('welcome', timeout=10).url`

Thanks,
Chris

**Comment by wkeeling** [comment]
If the request isn't seen in the timeout period, you'd need to catch the `TimeoutException`:
```python
from selenium.common.exceptions import TimeoutException

try:
    url= driver.wait_for_request('welcome', timeout=10).url
except TimeoutException:
    print("Request 'welcome' was not seen")
```
If the issue is that the request is slow you can increase the `timeout` value to something higher.

**Comment by Chris230291** [comment]
Thanks that's what I wanted.
