### ISSUE TITLE
Interceptors not working after attaching to existing browser session

### ISSUE THREAD

**Issue by serdnago** [wkeeling/selenium-wire#277]
First of all, thank you for an amazing framework!. 
We have some tests written in Pylenium, and we will like to use selenium-wire to mock some requests/responses. The tests follow some path driven by Pylenium and at some point, we attach the selenium-wire to the initial session. We know is working because at that point we can use selenium-wire to drive the remaining of the tests (clicking buttons and so on..) but the interceptors do not appear to work. Any ideas?

Thank you very much!

**Comment by wkeeling** [comment]
Thanks for raising this issue.

It sounds as though Selenium Wire may not have properly initialized. Are you able to share the code where Selenium Wire is used and how the interceptors are defined?

Thanks!

**Comment by serdnago** [comment]
# This is probably the simplest test:
# Before running test, start browser as follows:
# "C:\Program Files\Google\Chrome\Application\chrome.exe" -remote-debugging-port=9073 --user-data-dir="c:\my_data"


import time
from seleniumwire import webdriver

def interceptor_req(request):
    print(f'In Req interceptor {request}')

def interceptor(request, response):
    print(f'In response interceptor {request} ------------{response}')

def test_demo():
    webdriver.ChromeOptions.experimental_options = {"debuggerAddress": "127.0.0.1:9073"}

    driver = webdriver.Chrome()
    driver.response_interceptor = interceptor
    driver.request_interceptor = interceptor_req

    driver.get('https://news.yahoo.com/')

    time.sleep(10)

**Comment by wkeeling** [comment]
OK I can see the issue. Because you're controlling Chrome using the remote debugging port, it's necessary to manually tell Chrome about Selenium Wire so that it can send its requests to Selenium Wire for interception/capture.

To do that, you need to start Chrome with the `--proxy-server` option:

```
"C:\Program Files\Google\Chrome\Application\chrome.exe" -remote-debugging-port=9073 --proxy-server=localhost:12345 --user-data-dir="c:\my_data"
```

And then in your code, you need to start Selenium Wire using the same port number that you specified in the above command (`12345` in this case, but you can use any port number you like):

```python
import time
from seleniumwire import webdriver

def interceptor_req(request):
    print(f'In Req interceptor {request}')

def interceptor(request, response):
    print(f'In response interceptor {request} ------------{response}')

def test_demo():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option('debuggerAddress', '127.0.0.1:9073')

    sw_options = {
         'port': 12345  # This must match what you passed to Chrome
    }

    driver = webdriver.Chrome(
        chrome_options=chrome_options,
        seleniumwire_options=sw_options
    )

    driver.response_interceptor = interceptor
    driver.request_interceptor = interceptor_req

    driver.get('https://news.yahoo.com/')

    time.sleep(10)
```

**Comment by serdnago** [comment]
Thank you much for your answer, it works perfectly!!! :)
