### ISSUE TITLE
Unable to access site since using seleniumwire

### ISSUE THREAD

**Issue by penfly69** [wkeeling/selenium-wire#279]
Hello i started using seleniumwire few days ago to implement a proxy features and it worked a couple of time but i don't know why  now i can't access https://whatismyipaddress.com/fr/mon-ip or submit a captcha on https://raffle.bstn.com/ (captcha load for ever or work and failed after submission) i got this kind of error :  
![image](https://user-images.githubusercontent.com/70673492/116730050-48928200-a9e8-11eb-9bdf-51bec2ab5007.png) 
![image](https://user-images.githubusercontent.com/70673492/116730384-ba6acb80-a9e8-11eb-9827-4acf543c101f.png)
 
I tried several thing like adding manually the Selenium Wire certificate to google, using undetected_chromedriver, re initializing my google parameter, using new proxy address or my IP but none of this worked . (Edit i also tried to install python and selenium on my other computer and i face the same issues which is really weird ...)

Also my other program which only uses selenium no longer works since that ... 

i can't figure whats the problem or how to fix it so if you have any clue i would appriciate it a lot . Thanks for your time . 

(Ir is my test program but i don't think the problem is ir ) 

`
from seleniumwire import webdriver
import time
options = {
    'proxy': {
        'https': "https://user:pass@ip:port",
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Chrome(seleniumwire_options=options)

url = "https://whatismyipaddress.com/fr/mon-ip"
driver.get(url)

time.sleep(60)

driver.quit()
`

**Comment by wkeeling** [comment]
Thanks for raising this. I suspect you're probably suffering from [this issue](https://github.com/wkeeling/selenium-wire/issues/215). It seems that some sites are able to detect Selenium Wire, possibly from the SSL handshake (when you use Selenium Wire the browser does not make the SSL handshake with the target site - Selenium Wire makes it). Unfortunately I haven't made any progress on this issue yet, but I'll update here when I do.
