### ISSUE TITLE
Header Manipulation in IE not working

### ISSUE THREAD

**Issue by arunabhdas1** [wkeeling/selenium-wire#28]
Header Manipulation in Internet Explorer is not working.

**Comment by wkeeling** [comment]
@runabh - thanks for raising this. 

Selenium Wire doesn't officially support Internet Explorer (it's been tested on MS Edge), so there's no guarantee that features such as header filtering will work as expected.

If you're in a position to debug the issue I'd be happy to receive any further information and/or a pull request.

**Comment by runabh** [comment]
@wkeeling - Thank you for your response. We are trying our best to debug the issue and would definitely let you know if we see any success.

Meanwhile, could you please respond to our other issues.
