### ISSUE TITLE
undetected_chromedriver v2

### ISSUE THREAD

**Issue by rnyPlanet** [wkeeling/selenium-wire#285]
is there any way to select the version of undetected chromedriver? developer added v2. 

here, for example, the site https://monopoly-one.com/ does not pass Cloudflare on it (I assume that this is because of undetected_chromedriver v1 (I tested undetected_chromedriver v1 without selenium-wire - it also did not work, then I tested undetected_chromedriver v2 without selenium-wire - it passed Cloudflare)

**Comment by wkeeling** [comment]
There's a new version of Selenium Wire (v4.3.0) that [allows you to select](https://github.com/wkeeling/selenium-wire#bot-detection) the undetected_chromedriver version. You can choose the version of `Chrome` and `ChromeOptions` by switching the import statement - mirroring the way undetected_chromedriver itself works.

For undetected_chromedriver version 1:

```python
from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
```
For undetected_chromedriver version 2:
```python
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
```

**Comment by rnyPlanet** [comment]
@wkeeling Bro, I need your help, I beg you very much. I can't understand why undetected_chromedriver.v2 passes protection without problems, but with seleniumwire it returns a 503 error and that's it(  seleniumwire works fine with proxy

maybe a problem with ```with```? (https://github.com/ultrafunkamsterdam/undetected-chromedriver#the-version-2-way)
```
with driver:
    driver.get('https://coinfaucet.eu')
```
I also tested, and undetected_chromedriver.v2 also doesn't pass without  ```with```

here is the code i am testing
```
logging.basicConfig(level=logging.INFO)
logging.getLogger('undetected_chromedriver').level = logging.INFO
logging.getLogger('undetected_chromedriver.v2').level = logging.INFO
logging.getLogger('uc').level = logging.INFO

from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions

chrome_options = ChromeOptions()
# chrome_options.add_argument('--headless')

options = {
    'proxy': {
        'http': 'socks5://user:pass@ip:port',
        'https': 'socks5://user:pass@ip:port',
    }
}
driver = Chrome(options=chrome_options, seleniumwire_options=options)
# driver.execute_script("window.open('chrome://welcome');")
with driver:
    driver.get('https://httpbin.org/ip')
     # driver.get('https://monopoly-one.com/')
     # while (True):
     #     pass

# driver.get('https://monopoly-one.com/')
# driver.get('https://httpbin.org/ip')
# driver.get('https://distilnetworks.com')

print('Response:', driver.page_source)

# while (True):
#     pass

driver.quit()
```

I tested with and without ```with driver```

**Comment by wkeeling** [comment]
OK yes I'm also seeing a 503 from coinfaucet.eu:

```
INFO:seleniumwire.handler:Capturing request: https://coinfaucet.eu/
INFO:seleniumwire.handler:Capturing response: https://coinfaucet.eu/ 503 
```

undetected_chromedriver.v2 is definitely being used, but I'm wondering if Cloudflare is able to sniff the SSL handshake and "see" Selenium Wire. I think this could be related to [this](https://github.com/wkeeling/selenium-wire/issues/215). I need to do some further work on my side to see whether its possible to hide Selenium Wire's SSL fingerprint.

**Comment by rnyPlanet** [comment]
I will be grateful, and not only me) I would try to solve the problem and make a pull request, but my knowledge is not enough for this yet

**Comment by wkeeling** [comment]
Integration with undetected_chromedriver completed. The SSL handshake issue is being tracked by https://github.com/wkeeling/selenium-wire/issues/215
