### ISSUE TITLE
Cloudflare bypass doesn't work in seleniumwire

### ISSUE THREAD

**Issue by DenisTsukanov** [wkeeling/selenium-wire#286]
Bypass either not implemented or doesn't work properly, is it be because of **seleniumwire** works with **undetected chromedriver v.1**   ? (in v.1 it's no longer working, only in v.2 it works fine ) 

Here's following code 

import time
import undetected_chromedriver as uc
from seleniumwire import webdriver

sw_options = {
    'proxy': {
        'http': 'socks5://user:pass@45.***.**.***:8196',
        'https': 'socks5://user:pass@45.***.**.***:8196',
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Chrome( 
    seleniumwire_options=sw_options
)

driver.get('https://monopoly-one.com')
print('Response:', driver.page_source)
time.sleep(20)

driver.quit()

**Comment by wkeeling** [comment]
Thanks for raising this. Yes we need to update selenium wire to work with v2 of undetected chromedriver. I'll look at this ASAP.

**Comment by DenisTsukanov** [comment]
> Thanks for raising this. Yes we need to update selenium wire to work with v2 of undetected chromedriver. I'll look at this ASAP.

Thanks, appreciate it

**Comment by rnyPlanet** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/159/files#diff-b1415858986f3be41e64bac68e30d09ac7a9713f92af3a2177bbd193e8393bc2R53 @SunnyCapt 
I saw that you added a line for v1, can you add it for v2 to work with seleniumwire??

**Comment by SunnyCapt** [comment]
@rnyPlanet I'll try to do it soon
