### ISSUE TITLE
How to set an upstream proxy PAC url in selenium-wire?

### ISSUE THREAD

**Issue by hahampis** [wkeeling/selenium-wire#290]
Hello, 

our environment uses a proxy auto-configuration url. Is there a way to set this up when creating the webdriver instance with seleniumwire? The [documentation ](https://pypi.org/project/selenium-wire/#proxies) covers the address:port case but I couldn't find any info about PAC url.

Thank you!

**Comment by wkeeling** [comment]
Hi, thanks for raising this.

There currently isn't a mechanism to configure the proxy using a PAC url. It sounds like that could be a useful feature so lets leave this open and we'll look at implementing it.

**Comment by wkeeling** [comment]
PAC auto proxy configuration is currently out of scope due to effort/time constraints.
