### ISSUE TITLE
Capturing har files is not working

### ISSUE THREAD

**Issue by naveenmandepudi** [wkeeling/selenium-wire#292]
Hi,

I am trying to capture har files for each url/button hit on my web page but only first url hit is generating the har file and subsequent url/button hits are not creating har files. Please guide me if i am missing something here.

`from seleniumwire import webdriver 
import time
from seleniumwire import webdriver

options = {
    'enable_har': True  # Capture HAR data, retrieve with driver.har
    # 'disable_encoding': True
}
driver = webdriver.Chrome(seleniumwire_options=options)

driver.get('https://www.google.com')

f = open("google.har", "w")
f.write(driver.har)
f.close()

time.sleep(30)

driver.get('https://www.yahoo.com')

f = open("yahoo.har", "w")
f.write(driver.har)
f.close()
time.sleep(30)

driver.quit()`

**Comment by wkeeling** [comment]
Your code above seems to work OK for me.

HAR file capture is global (it's at the driver level). That means that the second har file `yahoo.har` contains all of the requests up to that point (all of the www.google.com as well as the www.yahoo.com requests).

If you clear out the requests between the `driver.get()` calls, then each HAR file will contain just those requests from the previous `driver.get()`. For example (line added highlighted in green):

```diff
from seleniumwire import webdriver
import time
from seleniumwire import webdriver

options = {
'enable_har': True # Capture HAR data, retrieve with driver.har
# 'disable_encoding': True
}
driver = webdriver.Chrome(seleniumwire_options=options)

driver.get('https://www.google.com')

f = open("google.har", "w")
f.write(driver.har)
f.close()

time.sleep(30)

+ del driver.requests  # Clear out the previous requests

driver.get('https://www.yahoo.com')

f = open("yahoo.har", "w")
f.write(driver.har)
f.close()
time.sleep(30)

driver.quit()
```

**Comment by naveenmandepudi** [comment]
Thanks @wkeeling for the reply. I added that extra step and now i see no entries in yahoo.har file.

**Comment by wkeeling** [comment]
OK thanks. It sounds as though no requests are being captured for the yahoo.com call.

Can you replace the code which writes the yahoo HAR file with some code that prints out captured requests. For example:

```diff
from seleniumwire import webdriver
import time
from seleniumwire import webdriver

options = {
'enable_har': True # Capture HAR data, retrieve with driver.har
# 'disable_encoding': True
}
driver = webdriver.Chrome(seleniumwire_options=options)

driver.get('https://www.google.com')

f = open("google.har", "w")
f.write(driver.har)
f.close()

time.sleep(30)

del driver.requests  # Clear out the previous requests

driver.get('https://www.yahoo.com')

+ for request in driver.requests:
+     print(f'Request: {request.url}')

time.sleep(30)

driver.quit()
```

**Comment by wkeeling** [comment]
Ok great. So it's working for you now?

**Comment by naveenmandepudi** [comment]
Yeah, but why only headless.. any thoughts!?

**Comment by naveenmandepudi** [comment]
That’s ok, but you @wkeeling, have done great job creating this package. Thanks a ton.

**Comment by wkeeling** [comment]
Thanks @naveenmandepudi 

I'm afraid I don't know why running the browser in headless mode seems to resolve the problem. If I have any insights though I'll update here.
