### ISSUE TITLE
Memory Leak when loading site protected by Cloudflare DDoS.

### ISSUE THREAD

**Issue by wahost070** [wkeeling/selenium-wire#294]
I'm connecting to a web page "https://www.dextools.io/" in order to get a JWT token. The page has Cloudflare protection that is stopping me from proceeding.
![image](https://user-images.githubusercontent.com/62430327/117854320-4bf7fa00-b281-11eb-88c7-d5c39025eb60.png)

The page does not get redirected after 5 seconds but instead the page keeps reloading. I have narrowed it down to something related to seleniumwire driver as I tried to use the regular selenium driver, and the undetected-chromedriver with no memory issues.

![image](https://user-images.githubusercontent.com/62430327/117854576-8792c400-b281-11eb-90f6-979c71ff9dea.png)

(Python 3.9.4, selenium-wire 4.3.0)

**Comment by wkeeling** [comment]
Thanks for raising this. We think that Cloudflare is able to detect Selenium Wire from it's SSL fingerprint. That seems to cause the repeated reload of the page.

This is also being [investigated separately](https://github.com/mitmproxy/mitmproxy/issues/4575) in mitmproxy that underpins Selenium Wire. 

We're tracking this in #215 so I'll close this one for now.

Also related #279 #285
