### ISSUE TITLE
KeyError issue when connecting to remote chrome session

### ISSUE THREAD

**Issue by wahost070** [wkeeling/selenium-wire#295]
Hi there.

I have a `undetected_chromedriver` which starts up a browser session, and then I am attempting to connect with seleniumwire, but a KeyError is thrown. If I substitute seleniumwire for selenium, this works fine.

```python

import undetected_chromedriver.v2 as uc_webdriver
from seleniumwire import webdriver as sw_webdriver  # Import from seleniumwire
from selenium import webdriver

try:
    driver = uc_webdriver.Chrome()
    
    executor_url = driver.command_executor._url
    
    print(executor_url)
    
    with driver:
        driver.get('https://youtube.com')
        
except Exception as e:
    print(f"Exception: {e}")
    
finally:
    
    new_driver = sw_webdriver.Remote(executor_url) # doesnt work if using seleniumwire
    out = new_driver.get("https://google.com")
```

Output:
```python
http://127.0.0.1:1068
Traceback (most recent call last):
  File "i:\Users\wahost070\Desktop\GitProjects\project\web.py", line 57, in <module>
    test()
  File "i:\Users\wahost070\Desktop\GitProjects\project\web.py", line 42, in test
    new_driver = sw_webdriver.Remote(executor_url)
  File "C:\Users\wahost070\.pyenv\pyenv-win\versions\3.9.4\lib\site-packages\project\webdriver.py", line 183, in __init__
    addr=seleniumwire_options.pop('addr'),
KeyError: 'addr'
```

(I understand this code is inefficient, it is just an example to demonstrate the issue).

**Comment by wkeeling** [comment]
Thanks for raising this. 

I think the issue is that you need to set the `addr` option in the seleniumwire_options:

```
options = {
    'addr': 'hostname_or_ip'  # Address of the machine running Selenium Wire
}

new_driver = sw_webdriver.Remote(
    executor_url,
    seleniumwire_options=options
) # doesnt work if using seleniumwire
    out = new_driver.get("https://google.com")
```

The `addr` needs to be set so that the remote webdriver can send traffic back to Selenium Wire for capture. There is a mention of it in the README, but admittedly it's not hugely obvious. 

If you're running the remote driver and Selenium Wire on the same machine then `addr` can be set to `localhost` (and we should probably be doing that by default - will make a note to fix).

**Comment by wahost070** [comment]
I appreciate the help @wkeeling. I had to import `DesiredCapabilities` as a finishing touch. Here is my fixed version based on the code above:

```python
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


options = {
    'addr': 'hostname_or_ip'  # Address of the machine running Selenium Wire
}

new_driver = sw_webdriver.Remote(
    executor_url,
    desired_capabilities=DesiredCapabilities.CHROME,
    seleniumwire_options=options
)
out = new_driver.get("https://google.com")
```

**Comment by wahost070** [comment]
@wkeeling I hope you don't mind me asking this on the same issue, but I'm trying to do the following:
- start a session with undetected-chromedriver
- connect to session with selenium-wire
- capture requests upon the next new_driver.get(), however I am getting back an empty array:

```python
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import undetected_chromedriver.v2 as uc_webdriver
from seleniumwire import webdriver as sw_webdriver  # Import from seleniumwire

# first
chrome_options = uc_webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
driver = uc_webdriver.Chrome(options=chrome_options)

with driver:
    executor_url = driver.command_executor._url
    driver.get('first-website')


# second
options = {
    'addr': '127.0.0.1'  # Address of the machine running Selenium Wire
}

new_driver = sw_webdriver.Remote(
    executor_url,
    options=chrome_options,
    desired_capabilities=DesiredCapabilities.CHROME,
    seleniumwire_options=options
)
# i would like to start capturing requests when I perform the selenium driver .get()
out = new_driver.get("second-website")
print(new_driver.requests) # returns empty array
```

**Comment by wkeeling** [comment]
It looks like the remote webdriver instance isn't sending its requests back to Selenium Wire for some reason. Can you try manually specifying the port number in the Selenium Wire options, and then the `--proxy-sever` option to the Chrome options - e.g.

```python
# second
options = {
    'port': 12345,  # Manually specify the port
    'addr': '127.0.0.1'  # Address of the machine running Selenium Wire
}

chrome_options.add_argument('--proxy-server=localhost:12345')  # Manually point Chrome at Selenium Wire

new_driver = sw_webdriver.Remote(
    executor_url,
    options=chrome_options,
    desired_capabilities=DesiredCapabilities.CHROME,
    seleniumwire_options=options
)
```

**Comment by wkeeling** [comment]
hmmm... actually thinking about it, the above may not work, since when the `--proxy-server` argument is passed the Chrome session will already have been established. I'll try and reproduce the issue and see if I can figure out what's happening.

**Comment by wahost070** [comment]
Any updates on this @wkeeling ? I am working on a project using the same logic where I am using undetected_chromedriver to bypass Cloudflare, and then passing this connection to Seleniumwire to handle reading the requests on the page, but I am getting an empty array when using the code in my previous message, including using your `--proxy-server` suggestion.
