### ISSUE TITLE
limit driver.requests size?

### ISSUE THREAD

**Issue by nium9** [wkeeling/selenium-wire#298]
so as you go more into a website the requests grow but it will come to a point where driver.requests will get exponitaly bigger so when going through the for loop of it it will then take longer is there way or advice to slice it so it wont get exponitaly bigger decressing the searching time for a particular request?

**Comment by wkeeling** [comment]
There's no way of specifying upper and lower bounds with the `driver.wait_for_request()` method. However, you could clear out the requests periodically with `del driver.requests` to prevent the list from growing too large. 

Another alternative would be to limit the requests that are captured using [driver.scopes](https://github.com/wkeeling/selenium-wire#limiting-request-capture) - e.g.

```python
driver.scopes = [
    '.*/some/path/to/request.*'
]

driver.get(...)

request = driver.wait_for_request( '.*/some/path/to/request.*')
```
