### ISSUE TITLE
Seleniumwire + undetected chrome driver v2 initial popup issue

### ISSUE THREAD

**Issue by Anandesh-Sharma** [wkeeling/selenium-wire#299]
```
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
chrome_options = ChromeOptions()
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-dev-shm-usage")
browser = Chrome(seleniumwire_options=options, options=chrome_options)
```
This gives me a pop-up again and again.
How can I fix this ?
![Screenshot from 2021-05-15 18-44-25](https://user-images.githubusercontent.com/30695364/118362633-de640a80-b5ad-11eb-9cfd-16fbec12cb0b.png)

**Comment by wkeeling** [comment]
The popup is happens because undetected-chromedriver v2 forces Chrome to start with a clean profile every time so the popup settings are never persisted. You should be able to fix by passing your own profile directory:

```python
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions

options = ChromeOptions()
options.add_argument('--user-data-dir=/tmp/myprofile')

driver = Chrome(options=options)
```

**Comment by Anandesh-Sharma** [comment]
Works like a charm. Thanks!
