### ISSUE TITLE
how to import CA certificate on to chrome browser

### ISSUE THREAD

**Issue by kingAli110** [wkeeling/selenium-wire#303]
Does anyone know where I am supposed to import the certificate? I know how to do it but am I supposed to do it on my local chrome browser or am i supposed to do it on the chrome browser opened by selenium. If I am supposed to do it on my local chrome browser I did it and it does not work.  And also the wizard asks me where am I supposed to store it. Do  I store it locally or let chrome automaticaly decide

**Comment by wkeeling** [comment]
It's possible that your local Chrome browser is using a different profile to the Chrome version started by Selenium and so the certificate is not being picked up. The certificate should be stored in the "Root Certificate Authorities" section, although this wording may vary depending on the OS you're using. Try starting Chrome using Selenium (add a sleep somewhere in your code to keep the browser open) and whilst the browser is open import the certificate.

**Comment by kingAli110** [comment]
I am using windows. how can i store it int the root certificate authorities section. as for doing it manually for each time i open chrome, that will be too time consuming. if it says not secure does that mean any data can be stolen, doesnt selenium wire encrypt data even though it says not secure

**Comment by kingAli110** [comment]
i tried using the sleep method and importing within that time but it still doesnt work. could u also provide the correct link for the downloiad of the certificate
