### ISSUE TITLE
[WinError 10048] - socket  

### ISSUE THREAD

**Issue by pi-eaterVZ** [wkeeling/selenium-wire#304]
Good day to you all , i apoligize if i am using the wrong forum to adress this since i dont think its an issue related to the wonderfull (really appreciate this package) Selenium-wire or its an issue cause of my lack of knowledge. I am not an advanced programmer. I keep getting these WinError 10048 - socket errors. I did some research but cant find a solution .

The problem occurs when i (repeately) iterate over the driver.requests (session.requests in my code) 
My code :
```
 def request_loader(self,end_counter = 0,scroll_element = None):
        response = []
        try:
            self.scroll(scroll_element) #function that scrolls down
            new_request_check = False 
            for request in self.session.requests: 
                try:
                    if request.response: 
                        if request.response.body in self.scraped_log: 
                        #scraped log is a list where i keep track of what request has already be handled
                            pass
                        else: 
                            end_counter = 1 
                            new_request_check = True                                       

                            try:
                                response_text = request.response.body.decode('utf-8')   
                                if "\n" in response_text: 
                                    response += response_text.split("\n")
                                else:
                                    response += [response_text]      

                            except (ValueError,KeyError) as e:
                                pass  
                    self.scraped_log.append(request.response.body)    #i handled this request so i add it in the log.                
                except:
                    pass  
               
            if new_request_check == False:                
                end_counter += 1
                print(f"no new requests found - breaking - {end_counter}") 

        except:
            end_counter += 1
            print("Error in request loader")
         

        print(f'finished iteration, end counter {end_counter}')   
        print(len(self.nodes))     
        return end_counter,response
```

My self.session  gets created in a function, relevant code:
```
options = Options()
profile = webdriver.FirefoxProfile()
profile.set_preference("media.autoplay.enabled", False)

 if self.headless:
      print("Headless Session")
      options.headless = True

 session = webdriver.Firefox(executable_path=GeckoDriverManager().install(),options=options,firefox_profile=profile)

```

This will give the winsocket error 50 % of the times. This code will scroll a page , and check if the request.body has a json , witch will be parsed with other function. If no new requests are found ( its a javascript loaded page ) it will stop after x iterations ( end_counter) 

If on the other hand i would completely load the page, and iterate over the requests  only once ,at the end , i wont get the socket error ...
I am probably doing something wrong here ? 

Kind regards, thank you for the effort for reading this and pointing me in the right direction

**Comment by wkeeling** [comment]
Sorry for the delay in replying. Are you able to share the full traceback you're getting?

**Comment by pi-eaterVZ** [comment]
Hey wkeeling ! thanks for youre time. I no longer have the errors described as above. Or at least they dont occur as frequent anymore. The only thing that got changed in the code is that i don't iterate that frequent over the driver.requests ( self.session.requuests) and that i dont store the body of all the request in a seperate list anymore.  There has also  been a firefox update since the error. 
Unfortunately i cant really point out what went wrong.

**Comment by wkeeling** [comment]
Thanks @pi-eaterVZ for the update. I'll close this for the time being but we can re-open if the issue starts to become a recurring problem.

**Comment by pi-eaterVZ** [comment]
Hey Wkeeling , this is the (now) occasionally socket error. 

Error collecting profiles [WinError 10048] Elk socketadres (protocol/netwerkadres/poort) kan normaal slechts één keer worden gebruikt - So far 2576 collected
Finished collecting profiles - So far 1290 collected
Emptied cache - nodes, edges, log, requests
[WinError 10048] Elk socketadres (protocol/netwerkadres/poort) kan normaal slechts één keer worden gebruikt
Closing Sessions <seleniumwire.webdriver.browser.Firefox (session="c057151c-ed9b-4b66-a12a-8b1b7cedca82")> - Bye
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54344)
Traceback (most recent call last):
  File "C:\Users\FGP\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\FGP\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\FGP\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\FGP\Desktop\DjangoScraper\env\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\FGP\Desktop\DjangoScraper\env\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\FGP\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] De software op uw hostcomputer heeft een verbinding verbroken

**Comment by wkeeling** [comment]
@pi-eaterVZ thanks for the traceback. I notice from looking at it that it references django. Are you using Selenium Wire in some larger Django webapp?
