### ISSUE TITLE
host is missing in headers

### ISSUE THREAD

**Issue by nrllh** [wkeeling/selenium-wire#305]
Hi,

the key `host` is missing in the header parameter. I can't see it in either requests or responses. In my case, I added it with the following code:

```
import urllib

header_key    = "host"
header_value = urllib.parse.urlparse(r.url).netloc 
header_pair   = header_key + ": " + header_value
```

Any thoughts why it's missing?

**Comment by wkeeling** [comment]
@nrllh can you share some code that exhibits the problem?

**Comment by nrllh** [comment]
I use the `r.headers `parameter and call it as in:

```
driver.get('https://example.com')
for r in driver.requests:
    print(r.headers)
```

**Comment by wkeeling** [comment]
This seems to occur when HTTP/2 is in use. Disabling HTTP/2 will resolve:

```python
driver = webdriver.Chrome(
    seleniumwire_options={'mitm_http2': False}
)
```

Needs some more investigation.

**Comment by wkeeling** [comment]
It seems that the `Host` header should not be used when a request is generated directly in HTTP/2. See https://en.wikipedia.org/wiki/List_of_HTTP_header_fields. This may explain why the header is not present for HTTP/2 requests.
