### ISSUE TITLE
Persistent Connections

### ISSUE THREAD

**Issue by paulcalabro** [wkeeling/selenium-wire#308]
It looks like the setting for persistent connections used to exist but may no longer exist. Can someone please confirm if this is no longer possible? If no, are there any workarounds?

**Comment by wkeeling** [comment]
Yes the connection keep alive was retired when the underlying proxy implementation was switched to mitmproxy. Mitmproxy takes care of connection handling itself. Are you needing it for a specific reason?

**Comment by paulcalabro** [comment]
Thanks for the quick response! Yeah, I'm looking to leverage it because a device I'm working with has logic based on whether a request is the very first request after a connection is established. There's different logic to handle subsequent requests within the same connection, so I need to reuse the same connection to get the desired outcome.

**Comment by wkeeling** [comment]
It may be worth trying version 3.0.6 of Selenium Wire in that case, which was the last version that allowed control over the connection keep-alive. As mentioned, the current version doesn't allow manually changing the connection properties as that's handled automatically.
