### ISSUE TITLE
Request.params remove decoding for PLUS SIGN ( + )

### ISSUE THREAD

**Issue by pxbarman** [wkeeling/selenium-wire#311]
I was trying to get POST request parameter using the method request.params, however, it seems that plus sign ( + ) in the parameter are converted into the dictionary with whitespaces.

for example:
username=test+user&password=123456
the request.params[username] output is : test user instead of test+user.

i fixed the issue by replacing the strings.
    payload = request.params["username"]
    payload = payload.replace(" ", "+")

**Comment by wkeeling** [comment]
Thanks for raising this.

A plus sign in a request represents a space character, so when the request parameters are decoded the plus gets turned back into a space. If you want a literal "+" to be present, then you should use %2B instead:

```
username=test%2Buser&password=123456
```
