### ISSUE TITLE
refreshing the page 

### ISSUE THREAD

**Issue by nium9** [wkeeling/selenium-wire#315]
not really an issues but more of a question?
when refreshing the page does all previous requests disappear similar to inspect element in chrome?
so if i call driver.requests after a refresh page would it only store what just occured in the new refresh or will store new refresh plus what it had prior?

**Comment by wkeeling** [comment]
`driver.requests` is scoped by webdriver instance. If you refresh the page using the same webdriver, then the new requests will be stored in `driver.requests` on top of what was there previously.

**Comment by nium9** [comment]
so if i like capture the index of when i refresh maybe i can slice from refresh point to new as a work around?

**Comment by nium9** [comment]
ah , thats good idea 
thank you 👍
