### ISSUE TITLE
No pages entries in JSON HAR captured file 

### ISSUE THREAD

**Issue by jbhfenris** [wkeeling/selenium-wire#318]
Hello,

I'm using selenium-wire to capture HAR data, it works perfectly and HAR files produced could be load in harviewer tool or Google HAR tool analysis without any problem.
However when I try to load my HAR files in pageXray, to obtain some consolidated metrics, an error occurs saying that my HAR structure doesn't contain a pages entry in the JSON.
Do you know why this issue occurs and if a fix could applied ?
Regards

**Comment by wkeeling** [comment]
Thanks for raising this. 

Can you just explain the steps to reproduce, including the URL to generate the HAR file for (does it affect any URL?), how to invoke pageXray, etc. I just want to make sure that I'm able to reproduce the issue exactly as you're seeing it.

**Comment by jbhfenris** [comment]
I'm currently using my own private website to generate and capture the HAR file (perhaps not so representative) then the file is save to disk. 

For pageXray (https://github.com/sitespeedio/pagexray), I just follow the basic installation and calling in the console: pagexray --pretty <har file>

The error is the following:
/usr/local/lib/node_modules/pagexray/lib/index.js:60
      (har.log.pages[0]._meta && har.log.pages[0]._meta.firstParty)
                    ^

TypeError: Cannot read property '0' of undefined

Looking at the json hierarchy of the HAR file, I'm not able to find a 'pages' key. 
I could add it manually before saving the capture HAR file but I would preferred to determine if it is not an issue or a specific use-case  on selenium-wire.

Regards

**Comment by robbiewareham** [comment]
Looking at the HAR 1.2 spec, "pages" is an optional 

http://www.softwareishard.com/blog/har-12-spec/#log

Looking at the selenium-wire code (https://github.com/wkeeling/selenium-wire/blob/cfa9a9e7f7c46605dd5d58afd1bf60b81e657e22/seleniumwire/har.py#L172-L189) it doesn't include "pages" but nor should it have to.

I would suggest that pageXray is incorrect is expecting "pages" to exist.

**Comment by wkeeling** [comment]
Thanks @jbhfenris and @robbiewareham 

It does indeed look as though the `pages` element is optional according to the (now deprecated) [spec](https://w3c.github.io/web-performance/specs/HAR/Overview.html#sec-object-types-pages).

@jbhfenris it would probably be worth raising this as an issue on the pageXray project. I'll close this issue for now.
