### ISSUE TITLE
Sorry, I need help, I cant see where to get in contact for help this is most likely not a bug

### ISSUE THREAD

**Issue by KenClemson** [wkeeling/selenium-wire#323]
Please help !
So my project is using selenium driver.
We use PageObject library

E.g if I click on a submit button in my UI using selenium driver how am I meant to then use seleniumwire webdriver to then get the request.

I have tried things like
driver = webdriver.Chrome()
I have tried many many things for hours and hours.

if I do webdriver.get('Myappurl')  then it just goes to a different instance of the app not the one driver goes too ?
if I try to replace driver for webdriver for clicks and stuff, then nothing gets clicked on.

I realy want to make this work !
Please help.

**Comment by wkeeling** [comment]
Hi, thanks for raising this issue.

Are you able to post a small amount of code that demonstrates the problem? Can you also share the link to the PageObject library.

**Comment by wkeeling** [comment]
@KenClemson are you still having issues or did you manage to get things to work?
