### ISSUE TITLE
Upstream socks5h proxy not resolving .onion addresses

### ISSUE THREAD

**Issue by mynameisfiber** [wkeeling/selenium-wire#324]
I am setting up an upstream tor socks5 proxy which works for clearweb addresses, however when I try accessing a .onion address the pysocks proxy can't resolve the domain.

My selenium-wire options are:

```
{
  'request_storage_base_dir': '/tmp/',
  'enable_har': True,
  'backend': 'default',
  'proxy': {
    'http': 'socks5h://127.0.0.1:55199',
    'https': 'socks5h://127.0.0.1:55199'
  }
}
```

And when I do a `driver.get('http://facebookcorewwwi.onion/')` the resulting page's `drive.page_source` is:

```
<html xmlns="http://www.w3.org/1999/xhtml"><head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException('Server connection to (\'facebookcorewwwi.onion\', 80) failed: Error connecting to "facebookcorewwwi.onion": [Errno -2] Name or service not known')</p>
            
        </body></html>
```

In general, the upstream proxy works well. If I try going to https://check.torproject.org/ I get confirmation that traffic is going through tor. In addition, if I manually connect to the socks5 proxy using `$ chromium --proxy-server="socks5://localhost:55199"` then I am able to go to .onion domains.

**Comment by mynameisfiber** [comment]
I'm trying to poke around and see what is going on. One strange thing I'm seeing is that `SocksServerConnection.makesocket` never gets called and it seems to be the only place where `.set_proxy` is called.

**Comment by mynameisfiber** [comment]
I've traced the problem back to `TCPClient.create_connection`. The issue is that we are running `socket.getaddrinfo` outside of the context of the proxy.

**Comment by wkeeling** [comment]
Thanks again for the PR!

**Comment by mynameisfiber** [comment]
@wkeeling my pleasure! thanks for `selenium-wire` :)
