### ISSUE TITLE
Problems with request body encodings

### ISSUE THREAD

**Issue by hacefresko** [wkeeling/selenium-wire#330]
Hello. I'm trying to log all POST request made by the browser but I'm having problems with some of them. 

When trying to access the body of some requests with request.body, I get a weird encoded output, instead of the classic key=value&... So for example, instead of having "authenticity_token=1234", I get
"0=a&1=u&2=t&3=h&4=e&5=n&6=t&7=i&8=c&9=i&10=t&11=y&12=_&13=t&14=o&15=k&16=e&17=n18=%3D&19=1&20=2&21=3&22=4"

**Comment by wkeeling** [comment]
Thanks for this and sorry for the delay in replying.

The body output above `0=a&1=u&...` is still in the key=value format, so is technically valid POST data encoded as `application/x-www-form-urlencoded`.

Are you sure you're looking at the correct POST request? If definitely the correct request, what does the network panel in the browser show for that request - in terms of the body?

**Comment by hacefresko** [comment]
Network panel shows `authenticity_token=1234` in the form source data. I spotted this issue on the login panel from github (github.com/session).

**Comment by alisoltanics** [comment]
I have the same problem.
Sometimes `request.response.body` returns `b'!\x9c\x00\x04{"token":"1gHq9ccRLs","expire_time":300}\x03'` and sometimes it returns something like this `b'\xa1\xa8\x01\x00 FnK\xfd\xf3\x0c\xd1\xbc\xa3\xd1i\xa2\x12*\x05@/\xb6\xb1\xcd\x07\xb8\x90r\xb0\xbc\xcb\xb7\xcb\x00\x04\xf95\xd5K\x1enu\x9f\xc3\xd5\x84 H\xc7,\x87\xab\xa8\xb6\xa1\xd9?'`

**Comment by wkeeling** [comment]
I've tried reproducing this with github.com/session and the following code:

```python
driver = webdriver.Chrome()
driver.get('https://github.com/session')
del driver.requests
login_field = driver.find_element_by_id('login_field')
password_field = driver.find_element_by_id('password_field')

login_field.send_keys('username')
password_field.send_keys('password')
button = driver.find_element_by_name('commit')
button.click()

request = driver.wait_for_request('https://github.com/session')

print(request.body)
```
The print statement produces:

```
b'commit=Sign+in&authenticity_token=64Pr1lWRYyyIPkFiVaVmUcVrROByhFXaQwLjY5vl4qkXNNNuGjqD73sEx9nuNpzed1OCaJRJb9fWDdWZ4DEPXQ%3D%3D&login=username&password=password&trusted_device=&webauthn-support=supported&webauthn-iuvpaa-support=unsupported&return_to=https%3A%2F%2Fgithub.com%2Flogin&allow_signup=&client_id=&integration=&required_field_93d8=&timestamp=1626113568693&timestamp_secret=efe4341589166af5ee8f5ec5f3fb504b9684d90ebff9ef63b90803b23274b90d'
```
So that doesn't appear to be encoded, but that could just be down to some difference in my environment.

**Comment by wkeeling** [comment]
@alisoltanics your example seems to be with the response body rather than with the request. Have you tried asking the server not to encode the response - e.g.
```python
options = {
    'disable_encoding': False
}
driver = webdriver.Chrome(seleniumwire_options=options)
```

**Comment by hacefresko** [comment]
Sorry, my bad, I was using one of these [methods](https://stackoverflow.com/questions/5660956/is-there-any-way-to-start-with-a-post-request-using-selenium) to perform a POST request, but I was passing a string instead of a dict so the post request was made in that way.

**Comment by wkeeling** [comment]
Thanks @hacefresko for the clarification. Are we good to close this now?

**Comment by hacefresko** [comment]
Yes, thanks
