### ISSUE TITLE
How to get request payload?

### ISSUE THREAD

**Issue by steeljardas** [wkeeling/selenium-wire#331]
How can we get the payload being used in a post request in the browser instead of only getting the data? is it possible?

I've tried print(request.params) but the result was {}

**Comment by wkeeling** [comment]
`request.body` will give you access to the payload. The `request.params` attribute will allow access to any parameters encoded in the body, provided the content type of the request is `application/x-www-form-urlencoded` - which it will be if it was posted by a regular browser form.

If you're having trouble with `request.params` you can retrieve the parameters manually from the request body like this:

```python
from urllib.parse import parse_qs
qs = self.body.decode('utf-8', errors='replace')
params = {name: val[0] if len(val) == 1 else val for name, val in parse_qs(qs, keep_blank_values=True).items()}
```
