### ISSUE TITLE
Blocked by Kaspersky

### ISSUE THREAD

**Issue by digitalblossom** [wkeeling/selenium-wire#332]
Normal Selenium works just fine for the same url (google) and same code. However when using Selenium Wire it triggers Kaspersky's web module with a certificate error, maybe because it thinks a bad actor is inspecting the requests.

The warning page translates to:

> One or more of the certificates on this website are invalid, so we cannot guarantee their authenticity. This happens if the owner of the website has not updated the certificate in time or if it is a fake website created by fraudsters. If you visit such a website, the risk of attack increases.

> Reason: This certificate or certificate chain was issued by an untrusted root certification authority

Edit: This happens both with Gecko and Chromium driver

**Comment by wkeeling** [comment]
Thanks for raising this. 

Have you tried [installing](https://pypi.org/project/selenium-wire/#certificates) Selenium Wire's root certificate as a trusted authority?

**Comment by digitalblossom** [comment]
> Have you tried [installing](https://pypi.org/project/selenium-wire/#certificates) Selenium Wire's root certificate as a trusted authority?

Thanks for the reply, I don't quite understand how this works, because the Selenium browser window only appears during the execution

**Comment by HMaker** [comment]
> > Have you tried [installing](https://pypi.org/project/selenium-wire/#certificates) Selenium Wire's root certificate as a trusted authority?
> 
> Thanks for the reply, I don't quite understand how this works, because the Selenium browser window only appears during the execution

It means add selenium-wire's SSL certificate to system's trusted SSL certificates so Kaspersky won't complain, follow this tutorial https://support.kaspersky.com/CyberTrace/1.0/en-US/174127.htm
