### ISSUE TITLE
No option to prevent saving of requests?

### ISSUE THREAD

**Issue by Waffleboy** [wkeeling/selenium-wire#339]
I noticed seleniumwire saves every request and response in folders in ```/home/(user)/.seleniumwire```

This takes up alot of space over time, and there does not seem to be an option to disable this saving. Is there another way to turn this off?

**Comment by wkeeling** [comment]
You can disable request capture with the `disable_capture` [option](https://github.com/wkeeling/selenium-wire#all-options):
```
options = {'disable_capture': True}

driver = webdriver.Chrome(
    seleniumwire_options=options
)
```
Alternatively you can periodically clear out requests as your script runs, by calling:

```
del driver.requests
```

Lastly, you can reduce the volume of requests that get stored by [scoping requests](https://github.com/wkeeling/selenium-wire#limiting-request-capture) by using `driver.scopes`. 

Hope that helps.

**Comment by wkeeling** [comment]
From v4.4.0 Selenium Wire now supports in-memory request storage. If this option is selected no requests will be stored on disk. You can also restrict the number of requests that are stored in memory. See [the docs](http://github.com/wkeeling/selenium-wire#request-storage) for more info.
