### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gupengism** [wkeeling/selenium-wire#34]
I got error 
Traceback (most recent call last):
  File "D:/PROJECTS/DEMO/Resources/Extension/test.py", line 1, in <module>
    from seleniumwire import webdriver
  File "C:\Python27\lib\site-packages\seleniumwire\webdriver\__init__.py", line 3, in <module>
    from .browser import Chrome, Edge, Firefox, Safari  # noqa
  File "C:\Python27\lib\site-packages\seleniumwire\webdriver\browser.py", line 56
    def __init__(self, *args, seleniumwire_options=None, **kwargs):
                                                 ^
SyntaxError: invalid syntax

When I try to run this sample script
from seleniumwire import webdriver

driver = webdriver.Firefox()

driver.get('https://mondial-assistance-teleconsultation-fr-dev.intranet.allianz-assistance.com/#/')

for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
            request.response.headers['Content-Type']
        )

Could you please suggest on this?
Nipon

**Comment by wkeeling** [comment]
@gupengism It looks as though you're using Python 2.7. Selenium Wire [is compatible with Python 3 only](https://github.com/wkeeling/selenium-wire#compatibilty) and won't work on Python 2. Perhaps you can upgrade?
