### ISSUE TITLE
Race condition in seleniumwire.webdriver initialisation

### ISSUE THREAD

**Issue by akharlamov** [wkeeling/selenium-wire#340]
It seems there is a race condition in selenium wire initialisation in version 4.3.1. See the test case:

```python
import logging
from typing import Any, Dict, Text

from seleniumwire import webdriver
from concurrent.futures import ThreadPoolExecutor
from selenium.webdriver.firefox import options as firefox_options
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By


def run(proxy_url: Text) -> None:
    logging.basicConfig(level=logging.INFO)
    try:
        options = firefox_options.Options()
        options.headless = False

        sw_options: Dict[Text, Any] = {}
        sw_options['proxy'] = {
            'http': proxy_url,
            'https': proxy_url,
        }

        browser = webdriver.Firefox(
            options=options,
            seleniumwire_options=sw_options)
        browser.set_page_load_timeout(15)
        browser.scopes = [
            "https://news.ycombinator.com/*"
        ]

        wait = WebDriverWait(browser, 15, poll_frequency=0.4)

        browser.get("https://news.ycombinator.com/")

        wait.until(
            EC.visibility_of_all_elements_located(
                (By.XPATH, "//*[@class='athing']")
            )
        )

        browser.quit()
        browser = None
    except BaseException as exc:
        print(exc)


def test_case(thread_count: int) -> None:
    threads = ThreadPoolExecutor(max_workers=thread_count)

    proxies = [
        'https://user:password@proxy1:8080', 
        'https://user:password@proxy2:8080', 
        'https://user:password@proxy3:8080', 
        'https://user:password@proxy4:8080', 
        'https://user:password@proxy5:8080', 
        'https://user:password@proxy6:8080', 
    ]

    threads.map(run, proxies)

    threads.shutdown()


if __name__ == '__main__':
    print("Running in single thread, should work fine")
    test_case(1)

    print("Running in 6 threads, should fail in one of multiple threads")
    test_case(6)
```

The test_case running on multiple threads will likely fail in one or more cases with a random error. See the list below for the most frequent (depends on the size of the site, delays, and phase of the moon).
```
There is no current event loop in thread 'ThreadPoolExecutor-1_2'.
Invalid server specification: https://194.31.181.39:12323https:
ERROR:seleniumwire.thirdparty.mitmproxy.server.protocol.http:Invalid proxy server credentials supplied
AttributeError: UpstreamAuth
```

seleniumwire 3.0.6 seems to work better.

**Comment by wkeeling** [comment]
Reproduced and confirmed. Investigating.

**Comment by akharlamov** [comment]
Actually, the problem appears in the case of a single thread also. But its frequency is much lower. 

I did some investigation. The problematic part seems to be connected with the fact mitmproxy is started in a separate thread, and the control thread does not wait until mitmproxy initializes. That allows modifications of proxy's configuration before the spawned thread started or properly initialised.

**Comment by wkeeling** [comment]
Many thanks for the update. I've also established that if the Selenium Wire instances run without a proxy configured - i.e. by commenting out:
```python
#sw_options['proxy'] = {
#    'http': proxy_url,
#    'https': proxy_url,
#}
```
then this seems to work without any problems. That sort of makes sense based on what you've said about the config being modified before the child thread is properly initialised. I'll continue investigating, but feels like we're getting closer :)

**Comment by wkeeling** [comment]
There's now a fix for proxy authorization failures when running multi-threaded in v4.3.3. If you have a chance to try it and let me know how it goes I'd appreciate it!

**Comment by HMaker** [comment]
> There's now a fix for proxy authorization failures when running multi-threaded in v4.3.3. If you have a chance to try it and let me know how it goes I'd appreciate it!

I am experiecing race conditions too on 10+ concurrent drivers with selenium-wire 4.3.3.

**Comment by wkeeling** [comment]
@HMaker thanks for the update. Are you using an upstream proxy? Also, what are the messages you're seeing?

**Comment by HMaker** [comment]
I am using selenium-wire for proxy authentication together with undetected-chromedriver v1.

**Comment by HMaker** [comment]
I am using selenium-wire for proxy authentication together with undetected-chromedriver v1.

**Comment by wkeeling** [comment]
Ok thanks. What are the error messages you're seeing when using 10+ concurrent drivers?

**Comment by HMaker** [comment]
@wkeeling no error message at all, it stays stuck, so some deadlock. I added a lock wrapping webdriver creation and it seems to solve this concurrency bug. I am using `seleniumwire.undetected_chromedriver.v2.Chrome`:
```python
import threading
from seleniumwire.undetected_chromedriver.v2 import Chrome

startup_lock = threading.Lock()

def run():
    with startup_lock:
        driver = Chrome()
    # driver.get()
    driver.quit()

threads = []
for _ in range(10):
    t = threading.Thread(target=run)
    t.daemon = True
    t.start()
    threads.append(t)

for t in threads:
    t.join()
```
My code does not interacts with any global state that may be touched by multiple threads, so I think it's not a bug in my application. It can be a bug in undetected_chromedriver side too.

**Comment by ismail-amouma** [comment]
I am still experiencing the same problem with Selenium seleniumwire 5.1.0. I have set up everything exactly as described in Akharlamov's first post, but I am using a current feature. The code doesn't raise any errors at first, but after a while, it crashes due to some errors related to multiproxy/http .
