### ISSUE TITLE
Proxies do not authenticate when used with ThreadPoolExecutor

### ISSUE THREAD

**Issue by kingAli110** [wkeeling/selenium-wire#341]
Hi,
My code uses ThreadPoolExecutor to open many browsers at the same time, each browser with a different proxy. I use selenium-wire for the proxies since they need to be authenticated. Anyways, everytime I open the browser simultaniously many of the browsers open do not authenticate and the pop up for no_proxy pops-up(The proxy 127.0.0.1:port requires username and password). The proxies are not an issue either as they all work individually. Do you know what may cause this? Here is the code:

```
def open(row, proxy_line):

    def http_proxy(i):
        prox = i.rsplit(":")
        return prox


    http = http_proxy(proxy_line)
    # proxy setup
    server = {
        'proxy': {
            'http': f"http://{http[2]}:{http[3]}@{http[0]}:{http[1]}".replace("\n", ""),
            'https': f"https://{http[2]}:{http[3]}@{http[0]}:{http[1]}".replace("\n", ""),
            'no_proxy': 'localhost,127.0.0.1',
        }
    }

    capabilities = DesiredCapabilities().CHROME
    capabilities["pageLoadStrategy"] = "none"



    print(time.time()-start)
    
    driver = webdriver.Chrome(desired_capabilities=capabilities, executable_path=r"C:\Users\user\Desktop\chromedriver.exe", seleniumwire_options=server)

    driver.get("http://www.google.com)

    time.sleep(100)

with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(open, [0,0,0,0,0,0,0,0,0,0,0], proxies)
    executor.shutdown(wait=True)



print(time.time() - start)
```

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in replying.

I'd like to try and reproduce the issue you're seeing in my local environment. In the code above, you pass something called `cop` and `proxies` to `executor.map()`. Are you able to share the code for those?

**Comment by kingAli110** [comment]
sorry, i edited the code to be more understandable and forgot to change `cop` to `open`. imma edit the code now. as for the proxies its just a txt file turned into a list of proxies which aint really relevant. so proxy line would be the actual proxy of a index, n from proxies

**Comment by wkeeling** [comment]
This seems to be the same issue as #340. Currently under investigation.

**Comment by wkeeling** [comment]
There's now a fix for proxy authorization failures when running multi-threaded in v4.3.3. If you have a chance to try it and let me know how it goes I'd appreciate it!

**Comment by kingAli110** [comment]
Thanks. I have been quite busy lately, but once I get down to it I will be
sure to let you know.

**Comment by HMaker** [comment]
I am using multithreaded selenium-wire with proxy authentication and it's working fine.

**Comment by wkeeling** [comment]
Thanks for confirming @HMaker
