### ISSUE TITLE
how can I set no proxy in using firefox

### ISSUE THREAD

**Issue by cwlinghk** [wkeeling/selenium-wire#345]
is that something like

profile = webdriver.FirefoxProfile()
profile.set_preference('network.proxy.Kind','Direct')
webdriver.Firefox(profile)

thanks

**Comment by wkeeling** [comment]
Thanks for raising this. 

To bypass an upstream proxy, you should use the `no_proxy` option in your seleniumwire_options:

```
driver = webdriver.Firefox(
    seleniumwire_options={
        'proxy': {
            'https': 'proxy_host:port',
            'no_proxy': 'hostname_to_bypass'
        }
    }
)
```

The value of the `no_proxy` option should be a comma separated list of hosts that you want to bypass the proxy.
