### ISSUE TITLE
PhantomJS Webdriver

### ISSUE THREAD

**Issue by utzlol** [wkeeling/selenium-wire#357]
How to run PhantomJS with the selenium-wire? I need lightweight and fast headless browser for my project

driver = webdriver.PhantomJS()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'PhantomJS'

**Comment by wkeeling** [comment]
I'm afraid Selenium Wire doesn't currently support PhantomJS. Have you considered running Chrome in headless mode instead?
