### ISSUE TITLE
OSError: [Errno 24]  Too many open files: '/root/.seleniumwire/storage-

### ISSUE THREAD

**Issue by mascai** [wkeeling/selenium-wire#359]
I am running selenium-wire application on my server and have this issue.
Details
1) My application is multithreading (5 threads)
2) MyClass with selenium-wire driver object is one thread
3) Error occurs after ~40 object creation
4) I call `driver.close()` in MyClass destructor

```
Error handling request
Traceback (most recent call last):
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/handler.py", line 118, in response
    self.proxy.storage.save_response(flow.request.id, response)
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/storage.py", line 97, in save_response
    self._save(response, request_dir, 'response')
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/storage.py", line 79, in _save
    with open(os.path.join(dirname, filename), 'wb') as out:
OSError: [Errno 24] Too many open files: '/root/.seleniumwire/storage-cc8ff6aa-7f09-4f7d-879f-09788a93d28a/request-2f31603b-4898-46c0-9075-21f79aa1e970/response'

```

`selenium-wire Version: 4.3.1`

**Comment by wkeeling** [comment]
Thanks for raising this issue. 

It looks as though your threading configuration is causing Selenium Wire to hit the maximum number of open files that your OS allows. It's probably worth raising that limit. This SO explains how you can do that: https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

**Comment by mascai** [comment]
Thant you for your response.

Could you please recommend how to not  open files   ` with open(os.path.join(dirname, filename), 'wb') as out:` ?
Because i don't need this files I use selenium-wire only for proxy loging.

**Comment by wkeeling** [comment]
In that case it may make more sense to use [in-memory storage](https://github.com/wkeeling/seleniumwire/#in-memory-storage) only. With that no files will be opened. You cam also restrict the number of requests stored.

**Comment by wkeeling** [comment]
Another alternative is to leave the storage as it is, but set `'disable_capture': True` in your Selenium Wire options.

**Comment by mascai** [comment]
@wkeeling  thanks a lot for the answers
But both attempts (`'disable_capture': True` and `'request_storage': 'memory'`)  didn't help.

Received this error
```
Error handling request
Traceback (most recent call last):
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/handler.py", line 59, in request
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/storage.py", line 69, in save_request
  File "/root/dev_facebook/facebook-subscribers-anton/venv/lib/python3.8/site-packages/seleniumwire/storage.py", line 79, in _save
OSError: [Errno 24] Too many open files: '/root/.seleniumwire/storage-577d980b-9678-4954-aa34-5d53ac699960/request-e341862a-7012-4b5d-bad1-8279a0fc96d8/request'

```

**Comment by wkeeling** [comment]
Thanks @mascai 

It looks like the config hasn't taken effect as the standard disk storage is still being used. Can you post the code you used to set the options?

**Comment by wkeeling** [comment]
Thanks @mascai 

It looks like the config hasn't taken effect as the standard disk storage is still being used. Can you post the code you used to set the options?

**Comment by wkeeling** [comment]
@mascai were you able to fix this?
