### ISSUE TITLE
seleniumwire.undetected_chromedriver.v2 CloudFlare problem (works without seleniumwire)

### ISSUE THREAD

**Issue by laurus-lx** [wkeeling/selenium-wire#363]
I'm trying to access a site that triggers CloudFlare block with regular WebDriver

It's working with `undetected_chromedriver.v2` as follows:

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get(url)
```

But accessing it via `seleniumwire.undetected_chromedriver.v2` triggers CloudFlare block, so something is wrong in seleniumwire to undetected_chromedriver binding

This code triggers CloudFlare block
```
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
options = ChromeOptions()
driver = Chrome(options=options)
driver.get(url)
```

Would much appreciate any ideas on how to troubleshoot!

**Comment by wkeeling** [comment]
Thanks for raising this. 

Yes CloudFlare is able to sniff the HTTPS handshake and from this knows that you are using Selenium Wire. This is a known issue that is currently under investigation. See #215

**Comment by wkeeling** [comment]
Tracking with #215
