### ISSUE TITLE
async problem with versions >4.3.2

### ISSUE THREAD

**Issue by stellarpatent** [wkeeling/selenium-wire#364]
After I upgraded to version >4.3.2 (i.e., 4.3.3 and 4.4.0) I get async errors in Django after I launch chrome with selenium-wire webdriver.  The exception I get in Django is “Django: SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async”.   

I'm making calls to the Django ORM.  The Django ORM works until I execute:
	from seleniumwire import webdriver
	driver = webdriver.Chrome(...

If I revert to selenium-wire 4.3.2, my Python code runs as expected.  But once I change to selenium-wire 4.3.3 and 4.4.0, I get the Django exception.    

I'm using: 
  Chrome 92.0.4515.131
  Django 3.2.6
  CentOS 7

I'm using the Django built in development server so there is only a single process running.  Also, I'm not planning on using this code in a real web server.      

Is there a way to stop the newer versions of selenium-wire from putting python in async mode?

**Comment by wkeeling** [comment]
Thanks for raising this. 

A similar issue has been raised with running Selenium Wire with Django test cases (see #358) and it looks like the issues are related. I'm currently away but I will look at fixing once I'm back.

**Comment by wkeeling** [comment]
Fixed in v4.4.1
