### ISSUE TITLE
selenium-wire won't work when python script is compiled with pyarmor

### ISSUE THREAD

**Issue by Dharmey747** [wkeeling/selenium-wire#368]
Hello,

I am currently working on one of my projects and I need seleniumwire in order to monitor requests. It seems to work perfectly while the script is running in .py and inside my IDE, but once I compile the script, I get an error and it won't start.

Error in question:
`cannot import name 'webdriver' from 'seleniumwire' (C:\Users\USER\AppData\Local\Temp\2\_MEI48042\seleniumwire\__init__.pyc)`

I am using hidden imports to pack my program, and I think I might be missing something that makes seleniumwire not work at all. Does anyone know the hidden import list required for seleniumwire (if there's one) ? I would love to use it.

**Comment by Dharmey747** [comment]
I have tried to put all of these dependencies in the hidden imports, but unfortunately the result is the same.

**Comment by wkeeling** [comment]
Can you show how you're using pyarmor to obfuscate your script and the dependencies? I'll see if I can reproduce.

**Comment by Dharmey747** [comment]
I'm using this command:

`pyarmor obfuscate --enable-suffix --obf-code 2 --advanced 2 --output dist/obf --package-runtime 0 main.py
pyinstaller --onefile --icon="icon.ico"  --hidden-import pytransform main.py`

**Comment by Dharmey747** [comment]
any updates?

**Comment by wkeeling** [comment]
Not yet. I have a bit of an issue backlog that I'm trying to work through, but I'll look at this as soon as I can.

**Comment by wkeeling** [comment]
Sorry for the delay in replying on this.

I've had a play around with pyarmor and pyinstaller and I've managed to get a test script to work. To begin with it was giving me the exact same error as you reported `cannot import name 'webdriver' from 'seleniumwire' ...` but I found I had to use the `--collect-all` option to pyinstaller to get things to work. 

To create the obfuscated script:
```bash
pyarmor obfuscate --enable-suffix --obf-code 2 --advanced 2 --output dist/obf --package-runtime 0 main.py
```
And then to create the binary with pyinstaller:

```bash
pyinstaller --onefile --collect-all seleniumwire main.py
```
My `main.py` looks like this:

```python
import logging
from seleniumwire import webdriver
logging.basicConfig(level=logging.INFO)

if __name__ == '__main__':
    driver = webdriver.Chrome()
    driver.get('https://www.wikipedia.org/')
    print(f'Captured {len(driver.requests)} requests')
    driver.quit()
```

**Comment by Dharmey747** [comment]
I have just tested this and it seems to work perfectly (even tho Pyinstaller was throwing a lot of errors for some reason, everything works fine). Thank you so much for your help!
