### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by quexx2** [wkeeling/selenium-wire#369]
When itterating over driver requests I get this error:
`_pickle.UnpicklingError: pickle data was truncated`
Sometimes it doesn't throw it, but most oftenly it does. It's really weird.
edit:
Alright so I figured that if you wrap it a try: except: block and just try again it works so thats a temporary fix for now

**Comment by wkeeling** [comment]
Thanks for raising this.

Are you able to share some code that demonstrates the problem? I appreciate it's random, but if you could still share some code - plus the version of Selenium Wire/OS you're using, that would help in reproducing. Thanks!

**Comment by quexx2** [comment]
alright. Here is some example code

```
seleniumwire_options = {
    'disable_encoding': True
    }

driver = webdriver.Chrome(seleniumwire_options=seleniumwire_options)

driver.get('https://google.com')

for request in driver.requests:
    print(request.body)
```

**Comment by wkeeling** [comment]
@quexx2 I'm looking into this in a little more detail and I suspect there's a race condition with persisting the requests and loading them with `driver.requests`. Are you able to share the traceback you see for the `_pickle.UnpicklingError` error?

As a temporary workaround, you can switch to [in-memory request storage](https://github.com/wkeeling/selenium-wire#in-memory-storage) which doesn't involve pickling:

```python
options = {
    'request_storage': 'memory'  # Store requests and responses in memory only
}
driver = webdriver.Chrome(seleniumwire_options=options)
```

**Comment by wkeeling** [comment]
Fixed in 4.5.2

**Comment by crane-denny** [comment]
I still see this problem from time to time in 4.5.6

**Comment by wkeeling** [comment]
@crane-denny do you have a traceback you can share?

**Comment by crane-denny** [comment]
Unfortunately there is none. 
It's silently failing and exiting with this error and without a traceback.
