### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED when script closes in seleniumwire and using TOR

### ISSUE THREAD

**Issue by shreesh1** [wkeeling/selenium-wire#372]
Maybe not a bug but a difference in selenium and selenium-wire  
#### Brief:
Let's say we a browse a site through selenium over TOR and the script as it gets completed closes itself the TOR proxy still runs in the browser, but as the same case running selenium-wire over TOR proxy as the script gets completed and it shuts itself the TOR proxy in the browser closes down and you can't interact further as PROXY fails.

#### How to reproduce the issue:
```python
from seleniumwire import webdriver
#from selenium import webdriver

import time
def wire():
    sw_options = {  # Ensure this is set to False
        'proxy': {
            'http': 'socks5://127.0.0.1:9050',
            'https': 'socks5://127.0.0.1:9050'
        }
    }
    chrome_options = webdriver.ChromeOptions()
#chrome_options.add_argument('--headless')

    browser = webdriver.Chrome(executable_path="./drivers/chromedriver",options=chrome_options,seleniumwire_options=sw_options)
    return browser

def notwire():
    PROXY = "socks5://127.0.0.1:9050"
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument('--proxy-server=%s' % PROXY)
    browser = webdriver.Chrome(executable_path="./drivers/chromedriver",options=chrome_options)
    return browser

if __name__ == "__main__":
    browser = wire()
    browser.get("https://dnsleaktest.com")
    browser.find_element_by_xpath("//input[@value='Standard test']").click()
```

Just switch between selenium-wire and selenium imports and wire and  notwire function respectively and the test will run smoothly in case of selenium but in case of selenium-wire the test won't run,  just open up the "CONSOLE" and there would be  ERR_PROXY_CONNECTION_FAILED as the TOR proxy have stopped

**Comment by wkeeling** [comment]
Thanks for raising this.

Just to clarify, are you saying that the line `browser.get("https://dnsleaktest.com")` does not work when you use Selenium Wire?

**Comment by shreesh1** [comment]
Nope, that works fine,  

Let's say you just execute this code.
```python
from seleniumwire import webdriver
sw_options = {
        'proxy': {
            'http': 'socks5://127.0.0.1:9050',
            'https': 'socks5://127.0.0.1:9050'
        }
}
browser = webdriver.Chrome(executable_path="./drivers/chromedriver",seleniumwire_options=sw_options)
browser.get("https://www.google.com")
```

The `page *www.google.com*  is loaded fine but you can't search anything through it` or let's say surf the internet. 

As the work for the script is already done, it had already terminated itself but browser is still there as we didn't add **browser.quit()** and now if you want to search anything in there you can't, cause `the TOR proxy for the browser has also shutdown with the script`.

Where else in the case of `selenium even after script has terminated, the TOR proxy still remains in the browser` and we can search through through google or let's say surf the internet.

**Comment by wkeeling** [comment]
Thanks for clarifying. 

Yes once the script ends, the proxy that Selenium Wire spins up in the background to capture requests will go away, which means the browser won't be usable because it will still be configured to use that proxy. 

This does catch people out from time to time. It may be that we can add some config option which when set, will keep the proxy thread running. I'll give it some thought.

**Comment by shreesh1** [comment]
Sure, Thanks a lot!

Though, for me the workaround is I just put the script to sleep through `time.sleep(secs)` so that script keeps running proxy still remains there.
