### ISSUE TITLE
Debugger Address Issue [urgent]

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [wkeeling/selenium-wire#385]
hello sir,

please sir i use undetected_chromedriver.v2 but when i use this line

options.add_experimental_option('debuggerAddress', 'localhost:9922')

 to connect it with exsiting browser it does not work please can you tell me the solution please 

this is the code that i use 

from selenium.webdriver.common.keys import Keys
import time
from time import sleep
import os
import undetected_chromedriver.v2 as uc
import random
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support import *
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import *
from selenium.webdriver import *
from selenium.webdriver.firefox.options import Options
from selenium.webdriver import Firefox
from selenium.webdriver import Chrome
import logging
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import pyautogui
from selenium.webdriver.support.ui import WebDriverWait as Wait
options = uc.ChromeOptions()
options.add_argument("--disable-notifications=True")
options.add_argument(' --origin-trial-disabled-features=SecurePaymentConfirmation')
options.add_experimental_option('debuggerAddress', 'localhost:9922')
driver = uc.Chrome(options=options)

with driver:
    driver.get('https://nowsecure.nl')

**Comment by wkeeling** [comment]
Thanks for raising this. When you use the `debuggerAddress` option, you have to manually tell Chrome about Selenium Wire so that it can send its requests to Selenium Wire for interception/capture.

There are already some issues that describe how to do that which hopefully can help:

- https://github.com/wkeeling/selenium-wire/issues/277
- https://github.com/wkeeling/selenium-wire/issues/201
