### ISSUE TITLE
Silence message "HTTP protocol error in client request: Server disconnected"

### ISSUE THREAD

**Issue by jordibonastrem** [wkeeling/selenium-wire#392]
how i can disable this log??:

```
127.0.0.1:53573: request
  -> HTTP protocol error in client request: Server disconnected
```

**Comment by wkeeling** [comment]
This message will now be suppressed by default and can be controlled by the `suppress_connection_errors` [config option](https://github.com/wkeeling/selenium-wire#all-options). Available in the next release.
