### ISSUE TITLE
Fingerprint wont change and proxy detection 

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#393]
https://prnt.sc/1rqoasz
https://prnt.sc/1rqof0g

can we fix this issue? 
The first one detects that I use proxy 
the second one the fingerprint won't to change even I use fake user agent
I don't know if its a major issue or its normal

**Comment by skndrvoip** [comment]
also login to google with seleniumwire and undetected chrome only works if I enable the incognito chrome mode so is that normal?

**Comment by skndrvoip** [comment]
also proxy work if i only activate the incognito mode

**Comment by ericgonzalez94018** [comment]
same thing

**Comment by HMaker** [comment]
That's a browser thing, the goal of `seleniumwire` is to add support for request and response interception and proxy authentication to standard selenium. However integration with [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) is supported throught `seleniumwire.undetected_chromedriver.v2` imports.
