### ISSUE TITLE
Problem with version installed with pip

### ISSUE THREAD

**Issue by hacefresko** [wkeeling/selenium-wire#395]
Hi there!

I was trying to use the `decode` function from seleniumwire/utils.py in my program to decode brotli encoded responses, however it wasn't working. I investigated a bit why and I found that my seleniumwire version downloaded with pip didn't include that fix. 

I reinstalled pip with `python -m pip install --upgrade pip` and tried to download selenium-wire again with `pip install selenium-wire`, but the `decode` function is still the same:

```
def decode(data: bytes, encoding: str) -> bytes:
    """Attempt to decode data based on the supplied encoding.

    If decoding fails, the data original data is returned.

    Args:
        data: The encoded data.
        encoding: The encoding type.
    Returns: The decoded data or the original data if it could
        not be decoded.
    """
    if encoding != 'identity':
        try:
            if encoding in ('gzip', 'x-gzip'):
                io = BytesIO(data)
                with gzip.GzipFile(fileobj=io) as f:
                    data = f.read()
            elif encoding == 'deflate':
                try:
                    data = zlib.decompress(data)
                except zlib.error:
                    data = zlib.decompress(data, -zlib.MAX_WBITS)
            else:
                log.debug("Unknown encoding: %s", encoding)
        except (OSError, EOFError, zlib.error) as e:
            # Log a message and return the data untouched
            log.debug('Error decoding data: %s', str(e))
    return data
```

I don't know if there is a problem with my pip or seleniumwire installation or if it's a problem from the repository, so I'm writting this to let you all know about it.

Thanks a lot :)

**Comment by wkeeling** [comment]
Thanks @hacefresko for the issue.

The `decode` function shown above is what is present in the [latest release](https://github.com/wkeeling/selenium-wire/blob/2df267ce823f4ff67b1b07a49bfcb66a692cfeb0/seleniumwire/utils.py#L172) v4.5.2.
What issue are you seeing with it?

The function has been changed in `master` but that code has yet to be released.

**Comment by hacefresko** [comment]
Oh my bad, that was the problem. So I just need to wait until the new `decode` function is included in the release.

Thanks :)
