### ISSUE TITLE
getting stuck in code

### ISSUE THREAD

**Issue by Mobeen22-creator** [wkeeling/selenium-wire#405]
I am facing 1 issue. Browser get stuck on taking screenshot or driver.current_url . Its wired issue. Can anyone help me with this?

**Comment by Mobeen22-creator** [comment]
For example :
print(self.driver.current_url)

It stuck on this line and will never move.

**Comment by wkeeling** [comment]
Headless/non-headless is independent of Selenium Wire. What happens if you use headless with pure Selenium (no Selenium Wire)?

**Comment by Mobeen22-creator** [comment]
I am making google account. Using selenium, getting detected . Selenium_wire works fine in non-headless. But headless mode, creating issues.

**Comment by wkeeling** [comment]
Headless mode can be [detected by websites](https://stackoverflow.com/a/55365094). Have you tried using [undetected chromedriver](https://github.com/wkeeling/selenium-wire/#bot-detection)

**Comment by Mobeen22-creator** [comment]
Issue in seleniumwire.undetected_chromedriver.v2 . 
V1 version working fine. I don't why v2 version getting stuck and taking along time on loading browser.

**Comment by wkeeling** [comment]
Ok thanks for the update. Let's track this issue in #400. I'll investigate and update on that issue.

**Comment by skndrvoip** [comment]
@Mobeen22-creator I'm looking to contact you how ?

**Comment by Mobeen22-creator** [comment]
Discord Wick#0088

**Comment by Mobeen22-creator** [comment]
> @Mobeen22-creator I'm looking to contact you how ?

Discord Wick#88

**Comment by skndrvoip** [comment]
error user add me "Skndr#8042" without ""
