### ISSUE TITLE
proxy_options

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#407]
what is all proxy option available to add to proxy 
I'm thinking that i have problem of leak bandwidth on my script loop when request many proxy in 1 script

**Comment by wkeeling** [comment]
Thanks for the issue and sorry for the delay in responding.

Can you provide some more detail regarding this issue, as I'm not sure I understand your question "what is all proxy option available to add to proxy".

**Comment by skndrvoip** [comment]
proxyoptions = {
        'disable_capture': True,
        'mitm_http2': False,
        'verify_ssl': False,
        'connection_keep_alive': False,
        'connection_timeout': None,
        'max_threads': 3,
        'request_storage': 'memory',
        'suppress_connection_errors': True
        }

**Comment by wkeeling** [comment]
You can omit `'connection_keep_alive': False,` and `'connection_timeout': None,` and `'max_threads': 3,` as these are no longer used in the current version.

What problem are you seeing when you run your code?

**Comment by skndrvoip** [comment]
nothing just need performance stable for my threads
