### ISSUE TITLE
prevent huge data in TEMP from seleniumwire

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#408]
i have a huge data saved in TEMP folder .selenium-wire

thanks

**Comment by wkeeling** [comment]
Selenium Wire saves captured requests in temp. It will periodically clear them out itself or you can do it manually in your code with `del requests`. To restrict what gets stored see "Limiting Request Capture" in the README. You can also switch to memory only storage if using the disk is a problem - see "In-Memory storage" in the README.
