### ISSUE TITLE
Empty requests for Remote driver

### ISSUE THREAD

**Issue by Medniy2000** [wkeeling/selenium-wire#410]
I have code something like this:

```
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()

chrome_options.add_argument('disable-infobars')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--ignore-certificate-errors')
capabilities = {
    "browserName": "chrome",
    "selenoid:options": {
        "enableVNC": True
    }
}
capabilities.update(chrome_options.to_capabilities())

driver = webdriver.Remote(
    command_executor='http://<remote_ip>:4444/wd/hub',
    desired_capabilities=capabilities,
    seleniumwire_options={
        'auto_config': False,
        'addr': '0.0.0.0'
    }
)
```
The connection is ok, browser control works too, but when I want to get the list of requests it is empty:

```
`driver.get('https://google.com')
print(driver.requests)
# []
```

For ChromeDriver for example it works fine!
My remote driver was implemented with using Selenoid.

**Comment by wkeeling** [comment]
Thanks for raising this.

For this to work, the remote instance of Chrome has to be configured to point back to the machine that runs Selenium Wire (i.e. the script). Is the machine running the script accessible by the remote machine running Chrome?

**Comment by Medniy2000** [comment]
> Thanks for raising this.
> 
> For this to work, the remote instance of Chrome has to be configured to point back to the machine that runs Selenium Wire (i.e. the script). Is the machine running the script accessible by the remote machine running Chrome?
