### ISSUE TITLE
if page not load using bad proxy 

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#416]
`                #Get Proxy
                mylogs.info(f'Getting New IP')
                driver.proxy = get_random_proxy(proxies)
                while True:
                    driver.execute_script("window.open('https://api.ipify.org?format=json')")
                    driver.switch_to.window(driver.window_handles[-1])
                    json_response = json.loads(driver.find_element_by_tag_name('body').text)   
                    if json_response == 0:
                        mylogs.error(f'Proxy not working retrying...')
                        driver.close()
                        driver.switch_to.window(driver.window_handles[0])
                        continue
                    else:
                        proxy_ip = json_response['ip']
                        mylogs.info(f'Your new IP is: {proxy_ip}')
                        driver.close()
                        driver.switch_to.window(driver.window_handles[0])
                        break`

can you help me to figure this problem

`because if json_response == 0:` 

not help me and if the page not open i got crash

i nead if i get bad gateway or page not reachable make return and get new proxy until get the new IP

**Comment by wkeeling** [comment]
If the response is not returning valid JSON, then `json.loads()` will raise an exception - it won't be `0`. So try wrapping the `json.loads()` call in a try/except - for example:

```python
# Get Proxy
mylogs.info(f'Getting New IP')
driver.proxy = get_random_proxy(proxies)
while True:
    driver.execute_script("window.open('https://api.ipify.org?format=json')")
    driver.switch_to.window(driver.window_handles[-1])

    try:
        json_response = json.loads(driver.find_element_by_tag_name('body').text)
    except ValueError:
        mylogs.error(f'Proxy not working retrying...')
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        continue

    proxy_ip = json_response['ip']
    mylogs.info(f'Your new IP is: {proxy_ip}')
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    break
```

**Comment by wkeeling** [comment]
You should be able to do something like this:

```python
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

body = WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.TAG_NAME, "body")))
json_response = json.loads(body.text)
```
That will wait up to 30 seconds for the body to load.

**Comment by wkeeling** [comment]
Thanks for asking, but it's fine - I do it for the love of it 😁
