### ISSUE TITLE
header request accept language

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#419]
```
def interceptor(request):
    request.headers['Accept-Language'] = 'gd-GB,en-GB;q=0.9,cy-GB;q=0.8'
driver.request_interceptor = interceptor
time.sleep(10)
driver.get('https://httpbin.org/headers')
```

try this and result nothing change 

`{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-GB,en;q=0.9", 
    "Host": "httpbin.org", 
    "Sec-Ch-Ua": "\"Chromium\";v=\"94\", \"Google Chrome\";v=\"94\", \";Not A Brand\";v=\"99\"", 
    "Sec-Ch-Ua-Mobile": "?0", 
    "Sec-Ch-Ua-Platform": "\"Windows\"", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.25 Safari/537.36 Vivaldi/4.2", 
    "X-Amzn-Trace-Id": "Root=1-615f0aa9-67ddb94338a5de6707066348"
  }
}`

**Comment by wkeeling** [comment]
I didn't use any specific argument to Chrome. I don't believe setting the user-agent should change the accept-language header, although I think the user-agent can contain a language too.
