### ISSUE TITLE
change proxy on same driver.get

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#421]
is there way to change proxy inside the driver.get(url)
between click request in same page ?

try but all the time take the last driver.proxy before main driver.get(url)
only get the new proxy data if i get new URL driver 
the ip show me its change in terminal but no effect until get new URL 
i have make local server proxy to confirm that all the data come from 1 proxy until i kill the open threads from previous proxy
 then i get the new data of the new proxy inside the driver 

so in other mean is there option to release the previous proxy data after get the new proxy or before ??

**Comment by mikroelektro** [comment]
I think it is some kind of a bug.
Try the following
Change the proxy
Do any driver operation like find element
wait for 40 to 50 seconds.
Then you are connected with the new proxy

**Comment by wkeeling** [comment]
A bug relating to dynamic switching of the proxy was fixed in #518 (more info in #377 )
