### ISSUE TITLE
Error when closing selenium wire session

### ISSUE THREAD

**Issue by KhushC-03** [wkeeling/selenium-wire#431]
usually, after the first chrome window has opened and closed successfully I get this issue when the next window is opened. the window opens and closes like normal but this error occurs.
![image](https://user-images.githubusercontent.com/68359616/138761945-101015cb-84a1-4d84-ac78-565199f0e2b4.png)

**Comment by KhushC-03** [comment]
Hi, I still get this exact error even when specifying my own path. the error does not break my code but does look ugly. Is there any way to hide it? I've tried logging levels but they seem to make the program crash.

**Comment by wkeeling** [comment]
You're probably best to raise that as an issue with undetected_chromedriver and see whether they can help.
