### ISSUE TITLE
Chrome closing without driver.quit()

### ISSUE THREAD

**Issue by Issayev** [wkeeling/selenium-wire#435]
I faced a problem trying my chrome-selenium test when launched it on other pc. 
When I import webdriver from seleniumwire, create a chrome driver with local driver file and simply try to get google page, the browser just closes after driver.get() command. If I use any of chrome/firefox webdriver from selenium library or firefox from seleniumwire, browser doesn't close before driver.quit().The problem occurs only with chrome driver from seleniumwire. 

I used simple test like this
```
from selenium import webdriver


chrome_driver_path = "/home/.selenium_drivers/chromedriver_linux64/chromedriver_95.0.4638.54"
driver = webdriver.Chrome(executable_path=chrome_driver_path)
driver.get("https://www.google.com")
```

Also there isn't such problem when test it on other pc. Could you, please,  tell me what the trouble might be in. Thank you in advance.

**Comment by wkeeling** [comment]
Thanks for raising this. It looks like something is causing the browser to crash out. Are there any messages in your terminal after Chrome dies? Also, you could try increasing the Chromedriver log level, e.g.
```python
driver = webdriver.Chrome(
    executable_path=chrome_driver_path,
    service_args=["--verbose", "--log-path=/home/.selenium_drivers/chromedriver_linux64/chromedriver.log"]
)
```
after doing that, check the content of `/home/.selenium_drivers/chromedriver_linux64/chromedriver.log` for any clues.
