### ISSUE TITLE
Help with proxy bypass

### ISSUE THREAD

**Issue by cptx032** [wkeeling/selenium-wire#439]
Hi!

I'm using selenium-wire to use a authenticated proxy with Chrome, and now I want to bypass some URLs, but the bypassing that I want its not based in the host only, I want to bypass a URL based in simples rules as `endswith` or `contains`. **I dont want to block a request**, I want to bypass my authenticated proxy.

I've found that I can override the bypass behavoir doing a monkey patch in the following way:

```python
old_no_proxy_handler: Callable = http.HttpLayer.should_bypass_upstream_proxy
def custom_no_proxy(self, request: Request) -> bool:
    result: bool = old_no_proxy_handler(self, request)
    if result:
        return True
    # fixme > ...
    return True

http.HttpLayer.should_bypass_upstream_proxy = custom_no_proxy
```

The problem with this is that `request.path` is always an empty string, so I have only the `host` attribute filled. How I can this properly?

I'm using `selenium-wire==4.5.3` (because https://github.com/wkeeling/selenium-wire/issues/438)

**Comment by cptx032** [comment]
I've found a solution that for a while is working for me:

```python
def __init__(self, *args, **kwargs):
    self.no_proxy_contains = kwargs.pop("no_proxy_contains", [])
    self.no_proxy_endswith = kwargs.pop("no_proxy_endswith", [])
    super(...)
    self.request_interceptor = self._request_interceptor

def _request_interceptor(self, request) -> None:
    fake: bool = False
    for url_piece in self.no_proxy_endswith:
        if request.path.endswith(url_piece):
            fake = True
            break
    if not fake:
        for url_piece in self.no_proxy_contains:
            if url_piece in request.path:
                fake = True
                break
    if not fake:
        return

    logger.debug(f"FAKING {request.url}")
    method_method: Callable = requests.get
    if request.method == "POST":
        method_method = requests.post
    response: Optional[Response] = None
    try:
        response = method_method(request.url, headers=request.headers)
    except Exception as ex:
        logger.error(f"Error when faking {request.url}: {ex}")
    if response:
        request.create_response(
            status_code=response.status_code,
            headers=[(k, v) for k, v in response.headers.items()],
            body=response.content
        )
```

Where I can set in the constructor:

```python
no_proxy_endswith=[".js", ".css", ".ico", ".svg", ".woff", ".woff2"],
no_proxy_contains=["/auth/content/", "/auth/bundles/"],
```

The summary is that I'm doing a manual request with the `requests` library, that obviously, is not using the proxy and cancelling the request made by the mitmproxy.

**Comment by wkeeling** [comment]
Thanks for raising this and for providing a workaround. 

The reason why the monkey-patched function doesn't receive a `path` is that the function only gets called when Selenium Wire (well mitmproxy behind the scenes) first establishes a connection with the upstream proxy using a HTTP `CONNECT` request. The `CONNECT` request uses a host with no path. Subsequent `GET` and `POST` requests (which contain paths) are then sent over the connection, but the function is not interrogated again since the connection is now in place.

**Comment by cptx032** [comment]
> The reason why the monkey-patched function doesn't receive a `path` is that the function only gets called when Selenium Wire (well mitmproxy behind the scenes) first establishes a connection with the upstream proxy using a HTTP `CONNECT` request. The `CONNECT` request uses a host with no path. Subsequent `GET` and `POST` requests (which contain paths) are then sent over the connection, but the function is not interrogated again since the connection is now in place.

:open_mouth: this explain the behaviors that I was observing, thanks for the explanation!!
