### ISSUE TITLE
Authenticated Socks5 proxy with Firefox is not working

### ISSUE THREAD

**Issue by airled** [wkeeling/selenium-wire#446]
Seems like authed socks5 is not working with Firefox driver. Code:
```python
from seleniumwire import webdriver

options = {
    'proxy': {
        'http': 'socks5://login:pass@91.247.*.*:port',
        'https': 'socks5://login:pass@91.247.*.*:port',
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Firefox(seleniumwire_options=options)
driver.get('https://www.myip.com/')

```
It opens myip.com that shows me my real ip:
![screen-2021-11-15-15-43-03](https://user-images.githubusercontent.com/10863999/141758948-b2a8fd68-1702-4f79-b21e-c57482a4c9a9.jpg)

**Comment by wkeeling** [comment]
Thanks for raising this.

What version of Selenium Wire, Selenium and geckodriver are you using?

**Comment by airled** [comment]
Sorry for wasting your time. At first, I installed `selenium wire` with pip without version specification. Then I noticed that its version 3.0.0. So I reinstalled it to version `4.5.5` and now proxy works. My bad, so sorry and thank you for help.
