### ISSUE TITLE
Not Secure when using undetected_chromedriver.v2

### ISSUE THREAD

**Issue by xploader** [wkeeling/selenium-wire#448]
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions

options = ChromeOptions()

driver = Chrome(options=options)

driver.get("http://www.google.com")

![image](https://user-images.githubusercontent.com/79651939/142586182-5799a533-4cc8-43ff-902a-afd9c0a0fb6b.png)

Connection is not secure when using undetected_chromedriver.v2.

Any idea how to fix it? Thank you

**Comment by wkeeling** [comment]
You'll need to [import Selenium Wire's root certificate](https://github.com/wkeeling/selenium-wire#certificates) into Chrome to get rid of the "not secure" message. Search for "certificates" in Chrome's settings and then look for the "Authorities" tab. You'll see an "Import" button here.

![import_cert_diaglog](https://user-images.githubusercontent.com/1295116/142587627-ca6d7979-7df4-4612-96b5-bcca1a5302d7.png)

Alternatively if you're running Linux (or MacOS) you can install the certificate on the command line with:

```bash
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "Selenium Wire" -i /path/to/ca.crt
```

**Comment by xploader** [comment]
Thank you
