### ISSUE TITLE
patch request failed to sent to server

### ISSUE THREAD

**Issue by Qianmin-Yan** [wkeeling/selenium-wire#455]
![image](https://user-images.githubusercontent.com/74294550/143210971-33b01ca0-a186-42d3-9b40-bd8499333c0a.png)
![image](https://user-images.githubusercontent.com/74294550/143211353-5e4f3417-999a-4ce3-95ca-9aea77191ae5.png)

The patch request failed to send out while the get and post can send normally and get the correct response from the server, please help to look into this issue, my test case is blocked by this issue.

**Comment by wkeeling** [comment]
Thanks for raising this issue.

Are you able to provide a small code example that demonstrates the problem with the patch request?

**Comment by Qianmin-Yan** [comment]
Hi, I am afraid it's not convenient to do so, the code is for our product automation testing.
could you try it from your side, if it's able to be reproduced, if not, I will find another way to share the code with you.
Thanks to your reply

**Comment by wkeeling** [comment]
OK what is the exact error you're getting back from the patch request? Are you seeing a 500 status with error message? Any info would be useful as the screenshots above don't seem to show. Also, can you give me an idea of what the patch request is sending to the server - I'm assuming it's JSON? Can you share an example of the JSON?

**Comment by Qianmin-Yan** [comment]
There is no error status code returned, as the screenshot shows, it shows failed instead of status code, looks like the request failed sent to the server. and failed error msg says net:error_http2_protocol error.
The request body is normal JSON
![image](https://user-images.githubusercontent.com/74294550/143405812-bdedef0b-2197-4bcd-8418-1e6801d72d51.png)

**Comment by wkeeling** [comment]
OK thanks. So we need to understand whether there is a general issue with PATCH requests, or whether it is just an issue with your particular PATCH request.

I will look at creating a simple test case that sends a PATCH request to Selenium Wire using some Javascript. It may take me a little time to do that but hopefully I should have an answer over the next few days or so.

**Comment by Qianmin-Yan** [comment]
Thanks for your help, i am using python, not sure if will be the same as Java. I think it's better to try it out with python

**Comment by wkeeling** [comment]
I have set up a local test case that makes a PATCH request using Selenium Wire to the endpoint `https://httpbin.org/patch`, but the PATCH request goes through successfully and I am able to read the response that comes back. This is my test case:

**patchjson.html**
```html
<html>
    <head>
        <title>Make JSON PATCH Request</title>
    </head>
    <body>
        <button id="submit" onclick="sendJson()">Submit</button>
    </body>
    <script>
        function sendJson() {
            let xhr = new XMLHttpRequest();
            xhr.open("PATCH", "https://httpbin.org/patch", true);
            xhr.setRequestHeader("Content-Type", "application/json");
            let data = JSON.stringify(
                { "hello": "world", "spam": "eggs" }
            );
            xhr.send(data);
        }
    </script>
</html
```

**Code**

```python
url = 'file:///tmp/patchjson.html'
options = webdriver.ChromeOptions()
options.add_argument('--disable-web-security')
driver = webdriver.Chrome(options=options)
driver.get(url)
button = driver.find_element_by_id('submit')
button.click()

request = driver.wait_for_request('/patch')
resp_body = json.loads(request.response.body.decode('utf-8'))

assert resp_body['json'] == {'hello': 'world', 'spam': 'eggs'}

driver.quit()
```

One thing you can try: since the error you're seeing seems to be HTTP2 related, you could try and disable HTTP2 to see if that makes any difference:

```python
driver = webdriver.Chrome(
    seleniumwire_options={'mitm_http2': False}  # Disable HTTP2
)
```
As there doesn't seem to be a general problem with PATCH requests I'm going to close this issue for now, but feel free to update if you have any further info that could be useful.
