### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by Bllacky** [wkeeling/selenium-wire#46]
I tried to set up a connection using these instructions:

options = {
    'proxy': {
        'http': 'http://username:password@host:port',
        'https': 'https://username:password@host:port',
        'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
    }
}
driver = webdriver.Firefox(seleniumwire_options=options, )

My proxy does not need authentication.
At the end I wrote driver=webdriver.Firefox(seleniumwire_options=set_seleniumwire_options,firefox_options=options, firefox_profile=profile)

The end result is that whatever is read through the crawler using the proxy settings gets 500, Request Time Out.

Not sure if I am missing something.

**Comment by wkeeling** [comment]
If your proxy doesn't need authentication, you don't actually need to specify the literal `username:password` in the config. You should be able to use:

```
set_seleniumwire_options = {
    'proxy': {
        'http': 'http://host:port',
        'https': 'https://host:port',
        'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
    }
}

driver=webdriver.Firefox(seleniumwire_options=set_seleniumwire_options, firefox_options=options, firefox_profile=profile)
```
where `host:port` is the host and port of your proxy.

If you still see a 500 error after that, try turning your logger up to DEBUG and capture what comes out. Selenium Wire will suppress connection errors by default, so it may also be a good idea to turn that off with ` 'suppress_connection_errors': False` - e.g.
```

set_seleniumwire_options = {
    'proxy': {
        'http': 'http://host:port',
        'https': 'https://host:port',
        'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
    },
    'suppress_connection_errors': False  # Show connection errors
}
```

**Comment by wkeeling** [comment]
@Bllacky out of curiosity, is your proxy or target site using a self-signed certificate?

**Comment by Bllacky** [comment]
> 
> 
> @Bllacky out of curiosity, is your proxy or target site using a self-signed certificate?

The target site definitely does not use a self-signed cert, but the proxy I think it does.

**Comment by wkeeling** [comment]
OK thanks. This issue may be caused by a SSL certificate verification issue. If you're able to upgrade to v1.0.6 you can try setting the config option `verify_ssl` to `False` - for example:

```
options = {
    'verify_ssl': False,  # Don't verify self signed certificate
    'proxy': {
        'http': 'http://host:port',
        'https': 'https://host:port',
        'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
    },
    'suppress_connection_errors': False  # Show connection errors
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

**Comment by Bllacky** [comment]
Decided to implement a different solution. Never got this to work with a proxy.

**Comment by rsalimans47** [comment]
@Bllacky what solution did you implement in the end? I'm experiencing the same problem.

**Comment by linrongbin16** [comment]
Hi, after setting proxy options in `seleniumwire_options`, do I still need to set **the same proxy options** in `desired_capabilities["proxy"]` ?

BTW, I'm using selenium 4.x, chromedriver 96.x

**Comment by wkeeling** [comment]
You don’t need to set the proxy options in the ‘desired_capabilities’. Doing that will prevent Selenium Wire from working correctly.

**Comment by linrongbin16** [comment]
> You don’t need to set the proxy options in the ‘desired_capabilities’. Only ‘seleniumwire_options’ should be used for the proxy.

thanks for your reply
