### ISSUE TITLE
How to disable requests, before they're triggered?

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#462]
I'm using the interceptor function, on your ReadMe, but it still allows some requests to sometimes pass through bytes before they're actually blocked. I'm trying to achieve a request block, such as DevTools from Firefox or Chrome allows it, where requests are instantly blocked every time, before being able to pass through bytes.

**Comment by wkeeling** [comment]
Thanks for raising this.

Are you able to provide a small code example that demonstrates the problem?

**Comment by Avnsx** [comment]
> Thanks for raising this.
> 
> Are you able to provide a small code example that demonstrates the problem?

```python
import seleniumwire.undetected_chromedriver as uc
from seleniumwire import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--auto-open-devtools-for-tabs --no-first-run --no-service-autorun --password-store=basic') #--blink-settings=imagesEnabled=false 
chrome_options.headless = False
seleniumwire_options = {'proxy': {'https': 'socks4://91.126.138.135:5678',}} 
driver = uc.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options)

def interceptor(request):
    if request.path.endswith(('ister/', '02fad8.css', '5137.js','rname','ister',)):print(request.path)
    else:request.abort()
driver.request_interceptor = interceptor

driver.get('https://myurl.com')
```
shortened output:
```
/account/register/
/register.bcf7192ca2e5ad02fad8.css
/register.3ac7eaa92c158daa5137.js
```

Selenium-Wire:
![selenium-wire](https://i.imgur.com/TdSVY4p.png)
Firefox DevTools
![Firefox DevTools](https://i.imgur.com/QFsCnMM.png)

My reason for needing a feature like this, is because I'm trying to reduce the files that are loaded to a absolute minimum, because I'm using proxies, which are slow.

**Comment by wkeeling** [comment]
Thanks. From looking at the above, it seems that Selenium Wire is aborting the correct requests? Are you asking whether Selenium Wire can prevent the requests from being sent from the browser to begin with?

**Comment by Avnsx** [comment]
> Thanks. From looking at the above, it seems that Selenium Wire is aborting the correct requests? Are you asking whether Selenium Wire can prevent the requests from being sent from the browser to begin with?

Yes, just as DevTools can.

**Comment by wkeeling** [comment]
Selenium Wire doesn't have the ability to do this currently. It sits between the browser and the target site and intercepts the requests after the browser sends them, but it has no direct influence over the sending of those requests. That said, when a request is aborted by Selenium Wire (like in your example above), that request will not travel any further - and therefore won't pass through any proxy server you have configured.

**Comment by Avnsx** [comment]
> Selenium Wire doesn't have the ability to do this currently. It sits between the browser and the target site and intercepts the requests after the browser sends them, but it has no direct influence over the sending of those requests. That said, when a request is aborted by Selenium Wire (like in your example above), that request will not travel any further - and therefore won't pass through any proxy server you have configured.

I'm just using uc v1 with execute_cdp_cmd now, which allows me to achieve intended functionality. Maybe you should look into it and try to improve your interception functionality, as I see it absolutely meaningless in its current state.

Here's my solution with uc v1:
```python
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ['*png','*woff2','*woff','*jpg','https://www.apple.com/ac/globalnav/7/en_US/styles/ac-globalnav.built.css']})
driver.execute_cdp_cmd('Network.enable', {})
driver.get('https://apple.com/')
```
Network.setBlockedURLs is a experimental, but very usefull when for example using with slow proxies to reduce page load time, function in chromedriver, documented here: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs

above code is from: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/387

Anyways, regardless thanks for taking your time to respond 👍
