### ISSUE TITLE
Microsoft Edge Options

### ISSUE THREAD

**Issue by utzlol** [wkeeling/selenium-wire#466]
How to use the webdriver.EdgeOptions()? Is it available?

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for not coming back sooner. Unfortunately there's no support for `EdgeOptions` in Selenium Wire currently. Selenium Wire officially supports Firefox and Chrome, but given that Edge is now based on Chromium it may make sense to introduce support for Edge.
