### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by arivp** [wkeeling/selenium-wire#470]
Hi! i am having this problem with all my proxies that are user:password, when the instance starts it works great but when i try to go to another page or even refresh the same page it appears ERR_PROXY_CONNECTION_FAILED on all of my proxies.

i am using multiprocessing + seleniumwire. please help thank you

**Comment by arivp** [comment]
Okay i just found the "solution" for now, using time.sleep()

**Comment by wkeeling** [comment]
Yes if the browser window is left open and the driver itself ends, then the browser will give proxy errors when you try and use it, because it will no longer be able to talk to Selenium Wire. Using `time.sleep()` or `input()` to pause the driver and keep it alive is a reasonable approach.
