### ISSUE TITLE
How to get request parent

### ISSUE THREAD

**Issue by nrllh** [wkeeling/selenium-wire#471]
I have the following case:

1. Selenium visits foo.com 
2. foo.com includes an iframe bar.com and in this iframe there are new requests
3. in the iframe bar.com there are also new requests.

I wonder if I can assign each request I catch their frame parent. Is that at the moment possible?

**Comment by wkeeling** [comment]
I'm not fully sure I understand the exact problem, but would you be able to use an interceptor to set a header on iframe requests that references the URL of the iframe's parent? e.g. an interceptor for bar.com that sets a header on each bar.com request that points at foo.com e.g. `X-Parent-URL: http://something.foo.com`

**Comment by nrllh** [comment]
I'm trying to make a request tree when I visit a webpage. I'm not sure if I can assign each request correctly to its parent frame with that method. Thus, in my case, I also need to know which requests were made from which parent (iframe or main page).

**Comment by wkeeling** [comment]
Do the child requests have a `referer` header that references the parent request? If so, that might enable you build the tree? Otherwise I’m not aware of any other way to do it. Selenium Wire itself doesn’t have knowledge of how the requests themselves are made.

**Comment by nrllh** [comment]
No, not all requests have a `referrer` parameter. But if I understand your suggestion correctly I will also not be able to create a full tree, right? Because I will only find the first frame requests but not requests made in frames?

**Comment by wkeeling** [comment]
I was assuming that each nested iframe request would have a `referer` that points to it's immediate parent - the parent being either another iframe or the originating page itself. But it sounds like that's not the case.

**Comment by nrllh** [comment]
@wkeeling I think I found a way - check [here](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/index.html#network-monitor-request-details-stack-trace-tab).

It can be accessed via Browser APIs, but I don't know if Selenium provides such API. Probably yes, because OpenWPM uses it as well.
