### ISSUE TITLE
selenium-wire missing request

### ISSUE THREAD

**Issue by ahmedmani** [wkeeling/selenium-wire#472]
i was testing this on amazon in order to login there is 3 requests on the same host the problem is theres only 2 requests showing up the last request made was missing  from driver.requests but when printing the url on the request __init__ method the url shows up fine 
>for request in driver.requests:
>    print("url=" + request.url)

i fixed this by making another unnecessary get request than the missing request shows up normaly

**Comment by wkeeling** [comment]
Are you sure you're waiting long enough, as it's possible that the third request hasn't fully returned when you use `driver.requests`?

One way to ensure that all the requests are present is to use `driver.wait_for_request()`, e.g.

```
driver.get(...)  # Load the page

# Wait for request3
request = driver.wait_for_request('request3_path')
```
