### ISSUE TITLE
Dynamic proxy does not take effect

### ISSUE THREAD

**Issue by JLX120** [wkeeling/selenium-wire#474]
![image](https://user-images.githubusercontent.com/65143776/147525827-95ef446b-d905-44c9-8476-9559e4a413f0.png)
![image](https://user-images.githubusercontent.com/65143776/147525868-e859e90f-e359-4057-81b3-c32614067050.png)
What's the problem,Thank you

**Comment by aijiesd520** [comment]
probably its error about wall

**Comment by wkeeling** [comment]
It's impossible to tell what the problem is based on the information you've provided. Does the terminal/console show any error messages?

**Comment by JLX120** [comment]
> 无法判断问题出在哪里。终端/控制台是

![image](https://user-images.githubusercontent.com/65143776/147553080-ce670b36-af7f-45b0-a3a3-9ce47f5c3cad.png)
This is all my code, but I don't know why it doesn't implement dynamic proxy

**Comment by JLX120** [comment]
> 可能是关于墙的错误

I can't access Google with other VPNs com

**Comment by wkeeling** [comment]
Do the proxy settings work if you enter them directly into the browser and run the browser manually without Selenium Wire?

**Comment by JLX120** [comment]
> 如果您将代理设置直接输入浏览器并在没有 Selenium Wire 的情况下手动运行浏览器，代理设置是否有效？

I use Google's proxy switchyomega plug-in to add a dynamic proxy and set the account password to access Google Com website, I thought of changing the tunnel from domain name to IP. The result is like this. I don't know why
![image](https://user-images.githubusercontent.com/65143776/147576532-1ce4726e-d50c-4e9d-9097-31ff47d67be8.png)

**Comment by wkeeling** [comment]
@JLX120 is this still an issue for you?
