### ISSUE TITLE
how to hide chromedriver console in python?

### ISSUE THREAD

**Issue by aijiesd520** [wkeeling/selenium-wire#477]
i try to use headless mode 
But a lot of messages about chromedriver are printed in the console, I want to know how to hide them

**Comment by wkeeling** [comment]
Thanks for raising this issue. Can you share some code that demonstrates the problem including the options you’re passing.

**Comment by aijiesd520** [comment]
There is no demonstration, I think you should understand my needs. When I use the headless mode, I hope not to print any chromedriver information in the console. I want to know how to set it up.

**Comment by wkeeling** [comment]
ChromeDriver specific issue, unrelated to Selenium Wire.
