### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by JLX120** [wkeeling/selenium-wire#479]
Hello, after I configured the Socks5 agent, there was an SSL error. After looking for it for a long time, I don't know what the reason is. Can you help me see what the problem is
![image](https://user-images.githubusercontent.com/65143776/147845032-a02bfff4-ef7b-48b3-a8bc-2f12f3d3a49e.png)
![image](https://user-images.githubusercontent.com/65143776/147845028-c568233b-3325-4b09-989f-c9f8ad942ff1.png)

**Comment by JLX120** [comment]
The agency problem has bothered me for many days. I don't know how to solve it. If you know, I thank you very much

**Comment by wkeeling** [comment]
Have you tried using `socks5h` as the scheme - e.g.

```python
options = {
    'proxy': {
        'https': 'socks5h://...'
    }
}
```

**Comment by JLX120** [comment]
Thank you very much for your answer. The problem that has bothered me for a long time has been solved. I'm just curious why I can access successfully with h after Socks5, and I can't access successfully without h. can I know why?
![image](https://user-images.githubusercontent.com/65143776/147850615-38cb7bca-91e0-4c6d-a4c6-1d88d870488b.png)

![image](https://user-images.githubusercontent.com/65143776/147850565-445fd7fd-3467-4a0d-b885-df3059cda30a.png)
![image](https://user-images.githubusercontent.com/65143776/147850682-a52c5425-1e84-44cc-bce0-1d18579f4cb2.png)

**Comment by wkeeling** [comment]
Glad it's working for you now.

Yes so the `h` makes the DNS lookup happen through the socks proxy. Without the `h` the DNS lookup is performed by the host machine itself. I'm not entirely sure why it would fail when DNS is performed by the host machine, unless DNS is being blocked perhaps?
