### ISSUE TITLE
How to disable proxy ?

### ISSUE THREAD

**Issue by eeeeeeeeeee555** [wkeeling/selenium-wire#484]
Hi,
I am using this one to disable proxy but it doesn't work. My connection is still using the previous  proxy. Can anybody know the solution ?
```
            new_proxy = {

            }
            driver.proxy = new_proxy
```

**Comment by wkeeling** [comment]
Thanks for raising this.

Yes it does appear that there is no way to unset a proxy once it has been set. I will look at fixing this ASAP.
