### ISSUE TITLE
Headless not working.

### ISSUE THREAD

**Issue by tomekozlowski** [wkeeling/selenium-wire#495]
options = {
                        'headless': True,
                       'proxy': {
                            'http': f'socks5://{pass1}:{pass2}@{key}:{value}',
                            'https': f'socks5://{pass1}:{pass2}@{key}:{value}',
                            'no_proxy': 'localhost,127.0.0.1',
                        },
                        'detach': True,
                        'window-size': '1920x1080',
                        'prefs': {
                            'headless': True,
                            'credentials_enable_service': False,
                            'profile': {
                                'headless': True
                                'password_manager_enabled': False,
                                'default_content_setting_values.notifications': 2,
                    }}}
                    driver = webdriver.Chrome(seleniumwire_options=options)

I've tried adding it everywhere, to no avail, any solutions?

**Comment by wkeeling** [comment]
Thanks for raising this. 

The headless option is a Chrome option not a Selenium Wire option - so you need to pass it via that route, e.g.

```python
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')

driver = webdriver.Chrome(
    options=chrome_options,
    seleniumwire_options=options
)

```
Many of the other options that you are passing (e.g. window size, detach, prefs) are also Chrome options and not Selenium Wire options so should be passed via the same route.

Some examples are [here](https://stackoverflow.com/questions/15165593/set-chrome-prefs-with-python-binding-for-selenium-in-chromedriver), [here](https://www.programcreek.com/python/example/100025/selenium.webdriver.ChromeOptions) and a comprehensive list of all Chrome options [here](https://peter.sh/experiments/chromium-command-line-switches/). You can find the Selenium Wire specific options [here](https://github.com/wkeeling/selenium-wire#all-options).

**Comment by tomekozlowski** [comment]
Thanks, ur a chad, I didn't know I could split and import my normal selenium options, alongside with seleniumwires' by using this. 
`driver = webdriver.Chrome(options=chrome_options, seleniumwire_options=options)`
This solved the issue. Big thanks!
