### ISSUE TITLE
gpu_init.cc(457)] Passthrough is not supported

### ISSUE THREAD

**Issue by mastrolube** [wkeeling/selenium-wire#496]
Hi there, I've got a few of these errors (Chrome):

    [18284:2032:0129/192658.133:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is

The problem is that it never exits from the loop, even if there is a timeout in loading with set_page_load_timeout
```
driver.set_page_load_timeout(load_timeout_value)
try:
    driver.get(site)
except TimeoutException:
    pass
```
These are a few of the sites where that has happened:

> https://www.guardian.ng
> https://www.lindaikejisblog.com
> https://bet365.com

The only way to fix that is to go in headless mode.
Any clue of what's the problem?
Thanks!

**Comment by wkeeling** [comment]
This is unrelated to Selenium Wire. Appears to be an [issue in ChromeDriver](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled).
