### ISSUE TITLE
add_extension doesn't work with undetected_chromedriver

### ISSUE THREAD

**Issue by notmoaiad** [wkeeling/selenium-wire#498]
I'm trying to add a chrome extension to selenium-wire undetected_chromedriver But it doesn't seem to work.
I tried using just selenium-wire webdriver and it **works fine**.
Test code:
```
from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions

op = ChromeOptions()
op.add_extension("/home/moaiad/Downloads/extension_1_0_0_0.crx")

driver = Chrome(options=op)
driver.get("https://www.google.com/")

```
- Operating system: Pop-os 20 (ubuntu based)
- selenium-wire version: 4.6.0
- pip version 19.3.1

**Comment by notmoaiad** [comment]
> @notmoaiad try using op.add_argument("--load-extension=/home/moaiad/Downloads/extension_1_0_0_0.crx")

`add_argument` needs an extension source code as an argument, not a crx file.
So I need to download the source code from an online crx viewer, then pass its path.
Also I think `add_extension` doesn't work at all so I'll keep the issue open until.

**Comment by pawanpaudel93** [comment]
@notmoaiad Download the source code of the extension and extract it to a folder and use this option. You can find the source code in the github releases of the extension or can download the source code with some website available or download crx and convert to zip and extract and use it here. You just have to do some google if source code downloader is needed.

`op.add_argument("--load-extension=/home/moaiad/Downloads/extension_1_0_0_0")`

**Comment by notmoaiad** [comment]
@PuppyLover101 

Hey, yeah you can just separate the paths with a `,` 
like this: `op.add_argument(f'--load-extension=extension_path1, extension_path2')`

**Comment by wkeeling** [comment]
@notmoaiad are you able to confirm whether the issue with `add_extension()` works with pure undetected_chromedriver (no seleniumwire) - e.g.

```python
import undetected_chromedriver as uc   # No seleniumwire
driver = uc.Chrome()

op = uc.ChromeOptions()
op.add_extension("/home/moaiad/Downloads/extension_1_0_0_0.crx")

driver = uc.Chrome(options=op)
driver.get("https://www.google.com/")
```

**Comment by notmoaiad** [comment]
@wkeeling
I tried the example that you sent, and It didn't work.
So it seems like its from pure undetected_chromedriver.

**Comment by wkeeling** [comment]
Thanks for confirming @notmoaiad .

Maybe worth raising as an issue with undetected_chromedriver in that case. I'll close this one for now.
