### ISSUE TITLE
Cant find a folder lmao

### ISSUE THREAD

**Issue by Vinyzu** [wkeeling/selenium-wire#499]
So i have the exact same issue as this:
https://github.com/wkeeling/selenium-wire/issues/262
And the solution given was to delete the ".seleniumwire" folder. However, i could find a folder like this bruh.

**Comment by wkeeling** [comment]
You'll find the `.seleniumwire` hidden folder in `/tmp` on Linux and `C:\Users\<username>\AppData\Local\Temp` on Windows. More info [here](https://github.com/wkeeling/selenium-wire#request-storage).
