### ISSUE TITLE
conflict with Scrapy

### ISSUE THREAD

**Issue by zczczc2018** [wkeeling/selenium-wire#506]
## resume_spider_1  |     scrapy 2.5.1 depends on h2<4.0 and >=3.0
Hi wkeeling，I recently used selenium-wire and scrapy in debian. And I found a conflict in pip installation. I tried to lower the Scrapy version but I got a twisted erorr.

_ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)_

So I tried to lower the selenium-wire version. But I got an error again.
Here is my eorrr:

**File "/usr/local/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py", line 180, in __init__  
resume_spider_1  |     addr=seleniumwire_options.pop('addr'),  
resume_spider_1  | KeyError: 'addr'**

And here is my code:

```
        chrome_option = Options()
        chrome_option.add_argument('--headless')
        chrome_option.add_argument('--no-sandbox')
        chrome_option.add_argument('--lang=zh-CN')
        chrome_option.add_argument('blink-settings=imagesEnabled=false')
        ug = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
        chrome_option.add_argument("--disable-dev-shm-usage")
        chrome_option.add_argument(f'user-agent={ug}')
        chrome_option.add_experimental_option('excludeSwitches',
                                              ['enable-logging'])

        driver = Remote(
        command_executor="http://192.168.2.122:4445/wd/hub",
        desired_capabilities=DesiredCapabilities.CHROME,
        options=chrome_option)
```

Looking forward to your help😉

**Comment by wkeeling** [comment]
The latest versions of Selenium Wire 4.6.4 and Scrapy 2.6.1 seem to install without any issues. Will close this issue for now.
