### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED after clicking any link in the webpage.

### ISSUE THREAD

**Issue by kychanbp** [wkeeling/selenium-wire#51]
I am trying to get the json response from a webpage which needs login.

It works for the first page. I can get the http response. But once webdriver clicked on a link, and tried to go to another page, the page will load but non of the links in the newly loaded page work.

If you click on any of the link, the browser will say: ERR_PROXY_CONNECTION_FAILED.

I have tried to switch to selenium. No such problem exists. Of course, I cannot get the json files as desired.

**Comment by kychanbp** [comment]
I put a input() statement before each click and download steps. The browser will not give me the error.

**Comment by wkeeling** [comment]
@kychanbp thanks for raising this.

Are you able to turn logging to DEBUG in your test and see what comes out on the console? 

```
import logging
logging.basicConfig(level=logging.DEBUG)
```
If you're using Selenium Wire version 1.0.4, you will also need to disable suppression of errors with:

```
options = {
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

In addition, could you also post the code you're using to create the webdriver, and let me know what platform you're using - Linux/Windows/MacOS?

**Comment by paulfsheridan** [comment]
@kychanbp Did you manage to resolve this issue yourself? I'm experiencing the same issues.

**Comment by paulfsheridan** [comment]
@wkeeling I'm experiencing identical issues to @kychanbp - I've enabled logging and shared the code for creating the webdriver. I'm using MacOS, along with my own Proxy. 

Webdriver code:
```
options = {
'suppress_connection_errors': False,
'connection_timeout': 15,
'proxy': {
    'http': 'http://xxx@yyy',
    'https': 'xxx@yyy'
    }
}

self.browser = webdriver.Chrome("~/chromedriver", seleniumwire_options=options)
````
Logs:
```
DEBUG:urllib3.connectionpool:http://127.0.0.1:63258 "POST /session/f9900abca342694cfd1d9e458f87ae50/execute/sync HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:63258/session/f9900abca342694cfd1d9e458f87ae50/element {"using": "css selector", "value": "[id=\"g-recaptcha-response\"]"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:63258 "POST /session/f9900abca342694cfd1d9e458f87ae50/element HTTP/1.1" 200 88
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:63258/session/f9900abca342694cfd1d9e458f87ae50/element/4b1a2a02-67fc-4578-bb4d-06ab6d8568c4/element {"using": "xpath", "value": "./ancestor-or-self::form", "id": "4b1a2a02-67fc-4578-bb4d-06ab6d8568c4"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:63258 "POST /session/f9900abca342694cfd1d9e458f87ae50/element/4b1a2a02-67fc-4578-bb4d-06ab6d8568c4/element HTTP/1.1" 200 88
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:63258/session/f9900abca342694cfd1d9e458f87ae50/execute/sync {"script": "var e = arguments[0].ownerDocument.createEvent('Event');e.initEvent('submit', true, true);if (arguments[0].dispatchEvent(e)) { arguments[0].submit() }", "args": [{"ELEMENT": "1491428f-ab89-4ec3-8538-4f7b54c95296", "element-6066-11e4-a52e-4f735466cecf": "1491428f-ab89-4ec3-8538-4f7b54c95296"}]}
DEBUG:seleniumwire.proxy.handler:www.funda.nl:443 200
DEBUG:urllib3.connectionpool:http://127.0.0.1:63258 "POST /session/f9900abca342694cfd1d9e458f87ae50/execute/sync HTTP/1.1" 200 14
```

**Comment by yuhuan0311** [comment]
I have the same question now,sad

**Comment by Julian-Code14** [comment]
I have the same problem on Mac OS.

`Error making request
Traceback (most recent call last):
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
    super().connect()
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Users/julian/.pyenv/versions/3.7.0/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused`

If I open a new tab afterwards in the Chrome(driver) window and try to access google.com or anything else I get an ERR_PROXY_CONNECTION_FAILED

**Comment by wkeeling** [comment]
This is likely happening because once Selenium Wire completes, it will shutdown it's internal proxy server, but the browser instance will still be configured with the proxy settings. If you try and use the browser, it won't be able to connect to the proxy and will display ERR_PROXY_CONNECTION_FAILED. The workaround is to stop Selenium Wire from shutting down - which can be achieved with a `time.sleep()` or using an `input()` like the OP discovered.
