### ISSUE TITLE
No response data for images in .har file

### ISSUE THREAD

**Issue by misterajc** [wkeeling/selenium-wire#510]
I'm using selenium-wire with headless chrome to create .har files, and loading them into Chrome (developer tools) for analysis. When I look at a .jpeg or .gif request, I get the message "This request has no response data available". Maybe this is to reduce the size of .har files? In any case, it would be good if there was an option to turn these on.

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in replying.

Do you have any example sites that demonstrate this issue? I've tried a few - e.g. `https://www.cnn.com/` but the .gif and .jpeg images seem to display correctly after loading the .har into Chrome developer tools.

I'm using ChromeDriver 99.0.4844.51 and Selenium Wire 4.6.3
