### ISSUE TITLE
Local proxy requires username / password

### ISSUE THREAD

**Issue by vivri** [wkeeling/selenium-wire#511]
**Issue**
When using an authenticated HTTPS proxy, the local selenium-wire proxy is requesting username/password to proceed. This can be observed in graphic and headless (via a log message) modes. It's observable in Firefox and in Chrome.

**Expectation**
I'd like to be able to use the proxy without having to manually authenticate via a dialog (Also, I'm not sure which creds work there, as my proxy creds don't authenticate/authorize the localhost proxy.)

**Screenshot**
![image](https://user-images.githubusercontent.com/68236/154701907-8530f924-378d-44b3-a39d-e60c6402eec3.png)

**Lib versions:**
```
selenium-wire==4.6.0
undetected_chromedriver==3.0.0
```

**Comment by SeriyVol4ishe** [comment]
@vivri can you show how do you set proxy settings? because I use proxies with authentication and don't have any problems like this.

**Comment by alimp5** [comment]
@SeriyVol4ishe 
can you share a sample code ?
how did you configure proxy settings in codes ?
