### ISSUE TITLE
Failed to access driver.requests when using undetected-chromedriver

### ISSUE THREAD

**Issue by eytannnaim** [wkeeling/selenium-wire#517]
Trying to use selenium-wire with undetected-chromedriver doesn't work.
When trying to initialize the driver like described in https://github.com/wkeeling/selenium-wire#bot-detection I get
`Exception has occurred: AttributeError
'Chrome' object has no attribute 'requests'
`

I also found a similar issue in [stackoverflow.](https://stackoverflow.com/questions/71267628/get-xhr-requests-using-selenium-wire-and-undetected-chromedriver)

The code runs on windows and my packages versions are:

> seleniumwire.__version__: 
4.6.0
undetected_chromedriver.__version__:
3.1.3

Any help would be appreciated.

**Comment by eytannnaim** [comment]
I have managed to overcome this and I think the reference in your [doc](https://github.com/wkeeling/selenium-wire#bot-detection) is wrong. When using your reference it looks like I got an undetected chrome without any "wire" class wrapping it.

I have managed to get an expected driver when I ran the below code:

>  seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
if __name__ == '__main__':
    chrome_options = ChromeOptions()
    driver = Chrome(options=chrome_options)
    driver.get("https://www.anti-bot-site.com")
    r = driver.requests

If you believe I'm right and your doc is indeed not accurate, please let me know and I'll submit a pull request.

**Comment by wkeeling** [comment]
Thanks for raising this.

The instructions as specified by the doc don't cause a problem for me. The following works:

```python
import seleniumwire.undetected_chromedriver as uc

chrome_options = uc.ChromeOptions()
driver = uc.Chrome(options=chrome_options)
driver.get('https://www.wikipedia.org/')

print(driver.requests)
```

It's worth noting that `seleniumwire.undetected_chromedriver.v2 import Chrome` just points back to the same `Chrome` class as referenced above by `uc.Chrome`. So it shouldn't make any difference which is used.

Are you able to post the code that's causing the problem including all the imports you're using?

**Comment by eytannnaim** [comment]
It works!
It was indeed the version issue. After upgrading to 4.6.2 the issue disappeared.

Thanks
