### ISSUE TITLE
is there way to read network response 

### ISSUE THREAD

**Issue by skndrvoip** [wkeeling/selenium-wire#520]
im looking to read network response status and print it to know the status after press button the problem that its only show in network tap and not show in body to know the status of button action

**Comment by wkeeling** [comment]
You can read the status of captured requests with `request.response.status_code` - is that what you mean?

**Comment by skndrvoip** [comment]
i don't know how to know the request it's click button after i click if and check the network tap i see the status of this action if it's successful or its failure so i need a method to print this status on log without go to to network tap and monitor the response after button click

**Comment by skndrvoip** [comment]
![4DFE454B-7634-44B9-8BFD-820B27181C14](https://user-images.githubusercontent.com/23005748/159140184-3eea9644-2c6c-4c96-987a-f9a7cdf20db0.jpeg)
![3B25C56C-9172-4EFB-A53F-7FFA8385CD34](https://user-images.githubusercontent.com/23005748/159140187-ceff429b-1194-4439-b2a7-ed553d54157d.jpeg)
this is the data that i want print in log ro know the response from this click button

**Comment by wkeeling** [comment]
You can probably use a response interceptor to print that to the log. It doesn't look as though the response data is fully formed JSON so you'd need to print the whole body rather than trying to parse it. e.g.

```python

def interceptor(req, res):
    if 'sendidv' in req.path:
        print(res.body)

driver.response_interceptor = interceptor
```

**Comment by skndrvoip** [comment]
![image](https://user-images.githubusercontent.com/23005748/159162269-47f7de02-8fdc-4cfe-b567-d0b09f3cf4d8.png)
![image](https://user-images.githubusercontent.com/23005748/159162320-0154d077-e0ae-410a-83ec-b9dad2fb1226.png)
i did but tnothing print in log any help ?

**Comment by skndrvoip** [comment]
![image](https://user-images.githubusercontent.com/23005748/159163083-dc083be9-b8bc-4dc5-98f0-928c923a9a59.png)
![image](https://user-images.githubusercontent.com/23005748/159163100-9023ee05-d6c7-45f2-8cbe-e5dd5c22815f.png)
this is the request and response from netwropk

**Comment by wkeeling** [comment]
Can you confirm that anything is printing, e.g.

```python
def interceptor(req, res):
    mylogs.info("Response body is %s ", res.body.decode('utf-8'))
```

**Comment by skndrvoip** [comment]
nothing print

**Comment by wkeeling** [comment]
Can you change the `mylogs.info()` to `print()`

**Comment by skndrvoip** [comment]
found the problem its conflect with one of my extentioin if i disable the extention its work

**Comment by skndrvoip** [comment]
![image](https://user-images.githubusercontent.com/23005748/159185707-051f4494-3c30-47ae-86a2-e03a0a41685f.png)
i got like this when print any advice ? how to encode im use 
print(res.body)
and 
print(res.body.decode('utf-8'))
