### ISSUE TITLE
Dont capture HTTPS requests if '--user-data-dir' is defined

### ISSUE THREAD

**Issue by skilletfun** [wkeeling/selenium-wire#522]
I try to parse some sites with auth, so I provided `--user-data-dir` option for using remembered accounts in Default Chrome Profile. 

But in this case HTTPS requests dont capture. In `driver.requests` only google-ads and some other trash. 
And warning 'unsafe' don't display.

If I don't provide this option everything is ok.

So how to capture all requests and provide '--user-data-dir'? 

Example

```
from seleniumwire import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("--user-data-dir=C:/Users/User/AppData/Local/Chromium/User Data")

driver = webdriver.Chrome(chrome_options=options)

driver.get('https://youtube.com')

print(driver.requests)`  # [ https://safebrowsing.googleapis.com/ ], only one link!
```

System: Windows x64 LTSC, Python3.9.6, selenium-wire 4.6.3, selenium 4.1.3

**Comment by wkeeling** [comment]
There may be some settings in your default profile folder that are interfering with Chrome's proxy settings (Selenium Wire uses the proxy settings to capture traffic). Can you point `--user-data-dir` to a different location, e.g. a brand new folder?

**Comment by skilletfun** [comment]
> There may be some settings in your default profile folder that are interfering with Chrome's proxy settings
I just try to use myself example above but on other system (Linux Mint). And everything is ok. 
Very strange. 
Now I cant to check some my guesses because have no access to computer with problem.

My guess: Is it possibe that some my extensions block selenium-wire? 
I have proxy extensions, Ad-Block, etc. I think I should to disable them all.
But can I disable them and use Default account at the same time?

**Comment by wkeeling** [comment]
Yes those extensions could be the issue. Probably worth blocking them one by one to find out which one causes the issue.
