### ISSUE TITLE
Certification error

### ISSUE THREAD

**Issue by haider11234** [wkeeling/selenium-wire#524]
I'm using Linux server and Seleniumwire on it The ca is correctly installed in google on Windows and working great but when i installed in google Linux it still gave not secure in browser

**Comment by wkeeling** [comment]
You can try installing the certificate on Linux using this command:
```bash
certutil -d sql:$HOME/.pki/nssdb -A -t TC -n "Selenium Wire" -i /path/to/ca.crt
```
Change `/path/to/ca.crt` to point to your certificate.

If you get an error about `certutil` not being found, you can first install with:
```
apt install libnss3-tools
```
