### ISSUE TITLE
seleniumwire not working with undetected_chromedriver

### ISSUE THREAD

**Issue by joshung** [wkeeling/selenium-wire#533]
When I using undetected_chromedriver alone. It's working so good

```
import undetected_chromedriver as uc
def main():
    driver = uc.Chrome()
    driver.get('https://nowsecure.nl')
    print(driver.title)
if __name__ == '__main__':
    main()

```

But this one not working

```
from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
def main():
    chrome_options = ChromeOptions()
    driver = Chrome(
        options=chrome_options,
    )
    driver.get('https://nowsecure.nl')
if __name__ == '__main__':
    main()
```

My selenium version is 4.6.3

**Comment by wkeeling** [comment]
What's not working for you? When I run your second example above I can see the nowsecure.nl site, albeit with a recaptcha. Is the recapcha the problem?

**Comment by joshung** [comment]
sorry, I did not say clearly.

With "undetected_chromedriver" it's shoud not trigger anti-bot services. the first one is not trigger any recaptcha, but with "seleniumwire.undetected_chromedriver" the recaptcha is appear

**Comment by wkeeling** [comment]
Yes CloudFlare is able to detect Selenium Wire through HTTPS fingerprinting and then triggers the recaptcha. There's currently no solution for this. The issue is being tracked [here](https://nowsecure.nl)
