### ISSUE TITLE
Only one element in driver.requests when using extension, that connects proxy.

### ISSUE THREAD

**Issue by Tialo** [wkeeling/selenium-wire#536]
I need to collect all requests after going to site and I need to do it using proxy. For second problem I used this solution https://stackoverflow.com/a/55582859/14076943. And after I do couple driver.get(link) I won't get any updates on driver.requests. So it is always one element in list. But when I don't add extension everything works fine, and I have around 100 requests.

**Comment by wkeeling** [comment]
Selenium Wire uses the browser's proxy settings to redirect traffic for interception and capture. That means that if you override the settings by using an extension, then traffic won't be captured. 

If you want to use a proxy, you'll need to use Selenium Wire's own [proxy configuration](https://github.com/wkeeling/selenium-wire#proxies) to set it. Hope that helps.
