### ISSUE TITLE
Using selenium-wire with specific VPN 

### ISSUE THREAD

**Issue by vladyslavstetsenko** [wkeeling/selenium-wire#539]
Hello friends, 
For my current project, I use VPN SonicWall Mobile connect. To connect via VPN the name, host, username and password should be set to the client. Server is finished with vpn port ":4433"
<img width="463" alt="image" src="https://user-images.githubusercontent.com/34839911/167268260-3e94ad50-daeb-4830-9862-c514154e3aee.png">
While trying to connect my project service using selenium-wire by "driver.get" I got  error ERR_PROXY_CONNECTION_FAILED
"Site cannot be reached" and "No InternetThere is something wrong with the proxy server or the address is incorrect."
Despite this, the error doesn't appear in case of accessing public websites such as google or YouTube. 
Could you please suggest the way how to connect selenium-wire via VPN service and to access project website? 
I will be grateful for any help.

**Comment by vladyslavstetsenko** [comment]
***Also pfx certificate is used for project website. But it doesn't look like as the issue root cause.

**Comment by wkeeling** [comment]
Sorry for the delay. Are you still experiencing a problem with this? If so, can you share the code you're using and any config options you're passing?
