### ISSUE TITLE
SSL Handshake Error when using Selenium Wire

### ISSUE THREAD

**Issue by mdp18** [wkeeling/selenium-wire#543]
Hi All,
I'm attempting to open a webpage at ea.com/register using HTTP proxies with selenium-wire.

This is the error I get:
`TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')`

Is there any known workaround for this?

**Comment by wkeeling** [comment]
I've not seen this error before. What platform are you using - Linux/Mac or Windows? 

Can you share the version of OpenSSL and pyOpenSSL that you're using? You can get that with:
```
openssl version
```
and
```
pip show pyopenssl
```

**Comment by lusi1990** [comment]
pip show pyopenssl  输出如下:

```
Name: pyOpenSSL
Version: 22.0.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: The pyOpenSSL developers
Author-email: cryptography-dev@python.org
License: Apache License, Version 2.0
Location: c:\users\lusi\pycharmprojects\crawl_knife\venv\lib\site-packages
Requires: cryptography
Required-by: selenium-wire
```

**Comment by wkeeling** [comment]
This seems to be a compatibility issue with newer versions of OpenSSL and servers that don't support secure renegotiation. The SO thread above goes into more details and suggested solutions.
