### ISSUE TITLE
selenium-wire and undetected chromedriver: I thought it was solved?

### ISSUE THREAD

**Issue by Dotolox** [wkeeling/selenium-wire#546]
I get the same error, that normally appears when importing undetected_chromedriver directly and not thru selenium-wire. However, I think that I imported uc the correct way, so why do I still get this error? I use version 4.6.3.
Code:
```
import seleniumwire.undetected_chromedriver.v2 as uc
import time

chrome_options = uc.ChromeOptions()
seleniumwire_options = {}
driver = uc.Chrome(
    options=chrome_options,
    seleniumwire_options=seleniumwire_options
)
driver.get('https://...')
while True:
    time.sleep(3)
```

Error:
```
Traceback (most recent call last):
  File "***", line 6, in <module>
    driver = uc.Chrome(
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\undetected_chromedriver\__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'seleniumwire_options'
```

**Comment by wkeeling** [comment]
I can't reproduce this with the latest version of Selenium Wire and the latest version of undetected_chromedriver. Can you double-check that your imports are ordered correctly - e.g. ensure that you are not overwriting `import seleniumwire.undetected_chromedriver.v2 as uc` with a later direct import of `undetected_chromedriver`. Alternatively, it may be worth using a clean virtualenv and see whether you can reproduce the issue there.
