### ISSUE TITLE
Socks5 proxy is not working / being used

### ISSUE THREAD

**Issue by Lance0210** [wkeeling/selenium-wire#556]
When running the code I dont get any errors but the proxy is not being used instead my regular ip.
I use a socks5 Proxy do I have to use an http/https ? 

from seleniumwire.undetected_chromedriver as uc

proxy = '127.0.0.1:5000'
uc_options = uc.ChromeOptions()
uc_options.add_argument('--proxy-server=socks5://'+proxy)

driver = uc.Chrome(
    options = uc_options
)

I also tried using the seleniumwire_options to add the proxy but didnt work either

**Comment by wkeeling** [comment]
For an upstream proxy you must use the configuration format:
```python
options = {
    'proxy': {
        'http': 'socks5://127.0.0.1:5000',
        'https': 'socks5://127.0.0.1:5000',
    }
}
driver = webdriver.Chrome(seleniumwire_options=options)
```

Have you tried manually configuring the SOCKS proxy in Chrome's settings? Worth trying that first and then browsing to a site manually (no Selenium Wire) just to prove SOCKS _is_ changing the IP without Selenium Wire.

**Comment by Lance0210** [comment]
I used the wrong format, thanks for solving my issue
