### ISSUE TITLE
Change SOCKS proxy dynamically not working 

### ISSUE THREAD

**Issue by vladsuxunun** [wkeeling/selenium-wire#557]

**Comment by wkeeling** [comment]
Can you share some more info please, e.g. some code that exhibits the problem.

**Comment by vladsuxunun** [comment]
import imp
from webbrowser import Chrome
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options as chromeOptions
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from seleniumwire import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
import random
import requests
import pickle
#driver = webdriver.Chrome()


options = {
        'proxy': {
        'https': 'socks5://######@waw.socks.ipvanish.com:1080',
        
    } 
    }

options1 = {
        
    
    }


chrome_options = chromeOptions()
driver = webdriver.Chrome(ChromeDriverManager().install(),seleniumwire_options=options)
driver.get("https://api.myip.com/")
time.sleep(2)
driver.proxy = {
    'https': 'socks5://####@mad.socks.ipvanish.com:1080',
}
time.sleep(10)
print("prpxy")
driver.get("https://api.myip.com/")
time.sleep(3)
driver.backend = {
    'https': 'socks5://####@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
driver.proxy = {
    'https': 'socks5://###@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
time.sleep(240)
print("save")

**Comment by vladsuxunun** [comment]
the proxy is set, but after another proxy is set, it does not give an error, but it is not set

**Comment by wkeeling** [comment]
Ok thanks. Just to confirm, what version of Selenium Wire are you using?

**Comment by vladsuxunun** [comment]
selenium==4.1.2
selenium-wire==4.6.4

**Comment by wkeeling** [comment]
I've not been able to reproduce this. The proxy changes as expected after setting with `driver.proxy`.

I notice in your code above you have a typo - it's using `driver.backend` not `driver.proxy` which may explain why the proxy does not seem to change.

```python
driver.backend = {  # This won't work
    'https': 'socks5://####@mad.socks.ipvanish.com:1080',
}
```

**Comment by vladsuxunun** [comment]
import imp
from webbrowser import Chrome
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options as chromeOptions
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from seleniumwire import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
import random
import requests
import pickle
#driver = webdriver.Chrome()


options = {
        'proxy': {
        'https': 'socks5://b82KLnO9:9N87Qc0gUve@waw.socks.ipvanish.com:1080',
        
    } 
    }

chrome_options = chromeOptions()
driver = webdriver.Chrome(ChromeDriverManager().install(),seleniumwire_options=options)
service_args = ['--proxy=waw.socks.ipvanish.com:1080', '--proxy-type=socks5', '--proxy-auth=b82KLnO9:9N87Qc0gUve']
driver.get("https://api.myip.com/")
time.sleep(4)
driver.proxy = {
    'https': 'socks5://b82KLnO9:9N87Qc0gUve@mad.socks.ipvanish.com:1080',
}
time.sleep(10)
print("prpxy")
driver.get("https://api.myip.com/")
time.sleep(45)
driver.proxy = {
    'https': 'socks5://b82KLnO9:9N87Qc0gUve@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
driver.proxy = {
    'https': 'socks5://b82KLnO9:9N87Qc0gUve@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
time.sleep(240)
print("save")

**Comment by vladsuxunun** [comment]
I changed to proxy, but the IP change does not happen
