### ISSUE TITLE
I changed to proxy, but the IP change does not happen

### ISSUE THREAD

**Issue by vladsuxunun** [wkeeling/selenium-wire#565]
I changed to proxy, but the IP change does not happen

_Originally posted by @vladsuxunun in https://github.com/wkeeling/selenium-wire/issues/557#issuecomment-1159778132_

**Comment by vladsuxunun** [comment]
import imp
from webbrowser import Chrome
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options as chromeOptions
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from seleniumwire import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
import random
import requests
import pickle
#driver = webdriver.Chrome()


options = {
        'proxy': {
        'https': 'socks5://#######@waw.socks.ipvanish.com:1080',
        
    } 
    }

chrome_options = chromeOptions()
driver = webdriver.Chrome(ChromeDriverManager().install(),seleniumwire_options=options)
service_args = ['--proxy=waw.socks.ipvanish.com:1080', '--proxy-type=socks5', '--proxy-auth=#######']
driver.get("https://api.myip.com/")
time.sleep(4)
driver.proxy = {
    'https': 'socks5://######@mad.socks.ipvanish.com:1080',
}
time.sleep(10)
print("prpxy")
driver.get("https://api.myip.com/")
time.sleep(45)
driver.proxy = {
    'https': 'socks5://###########@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
driver.proxy = {
    'https': 'socks5://######@mad.socks.ipvanish.com:1080',
}
time.sleep(3)
driver.get("https://api.myip.com/")
time.sleep(240)
print("save")

**Comment by wkeeling** [comment]
OK I can see the problem. The socks proxy will only change when the address (host/port) of the proxy changes in `driver.proxy`. But it looks as though the address is always set to `mad.socks.ipvanish.com:1080`.
