### ISSUE TITLE
source code string cannot contain null bytes Error on Mac

### ISSUE THREAD

**Issue by tfbecker** [wkeeling/selenium-wire#567]
Selenium Wire is working flawlessly on my Windows machine however when i try to open an object on mac (vscode) i get the following error: 

target_requests is a list object of requests that I filtered
target_requests[0].response.body #opening the first one -> this is still fine
eval(target_requests[0].response.body) # this throws an error on mac

**Comment by wkeeling** [comment]
It looks like the response body contains a null byte which is causing `eval()` to raise the error. It's possible that the response body is being encoded differently when the request is made on a Mac vs Windows. You could try converting the body to a string before passing it to `eval()` - e.g.
```python
eval(str(target_requests[0].response.body))
```

**Comment by tfbecker** [comment]
I tried this but this, unfortunately, does not solve the problem for me.
It is also easy to reproduce.
# Go to the Google home page
driver.get('https://www.google.com')

# Access requests via the `requests` attribute
eval(str(driver.requests[0].response.body))


On mac it returns: b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff\x8aVJO\xccL\xd4\xcb\xd1K\xd4+R\xd2\x89\x8e\x8d\x05\x00\x00\x00\xff\xff\x03\x00\x94gy\xef\x11\x00\x00\x00'

On windows it returns a string:
b'["gaia.l.a.r",[]]'

**Comment by tfbecker** [comment]
Can anyone reproduce this issue ? It would be amazing to also use this library on mac :)

**Comment by tfbecker** [comment]
Solved it by using older versions:
#selenium==4.1.0
#selenium-wire==4.3.0
#cryptography==38.0.0
#pyOpenSSL==22.0.0
