### ISSUE TITLE
The best way to abort loading URL

### ISSUE THREAD

**Issue by momadvisor** [wkeeling/selenium-wire#571]
I should abort loading specific URLs. To filter specific URLs, I think I can take advantage of 'request_interceptor'. But I don't know what is the efficient and best way to abort loading URL with  'request_interceptor'?

-----------------
EDIT

I found abort() method of Request.

**Comment by wkeeling** [comment]
Yes using `request.abort()` from inside a request interceptor is the best way to abort loading.
