### ISSUE TITLE
How to change user agent in selenium wire options ?

### ISSUE THREAD

**Issue by thesalah1212** [wkeeling/selenium-wire#581]
I tried this one 
options = {
'proxy': {
    'http': f'http://{proxy_user}:{proxy_pass}@{host}:{port}',
    },
'user-agent':randomuseragent
}

then I test using 

driver.execute_script("return navigator.userAgent;")

the user agent don't changed same always

**Comment by wkeeling** [comment]
You will have to use a request interceptor if you want to change the user agent. 

```
def request_interceptor(req):
    del req.headers["user-agent"]
    req.headers["user-agent"] = "randomuseragent"

driver.request_interceptor = request_interceptor
```
