### ISSUE TITLE
header contains specific word

### ISSUE THREAD

**Issue by uzvaio** [wkeeling/selenium-wire#582]
hello and thanks for this amazing work.
i want to get some response from network requests which contains specific word.
i dont know how to filter the response.

word is playlist.m3u8

thanks.

**Comment by wkeeling** [comment]
Try using a response interceptor, e.g.

```
def response_interceptor(req, res):
    if b'playlist.m3u8' in res.body:
        print(f'Found request: {req.url}')

driver.response_interceptor = response_interceptor
```

That assumes that the word you're looking for is somewhere in the response body.
