### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by 1rone** [wkeeling/selenium-wire#586]
Hello, when I am trying to driver.get('https://www.inmobi.com/'), the website is not opening. I receive next error in browser: ERR_HTTP2_PROTOCOL_ERROR.

I tried to install certificates, but it wasn't help

**Comment by wkeeling** [comment]
Can you try switching off HTTP2:
```python
sw_options = {
    'mitm_http2': False
}

driver = webdriver.Chrome(
    seleniumwire_options = sw_options
)
```

**Comment by 1rone** [comment]
Yes, it worked!
Thank you very much!
