### ISSUE TITLE
Clear driver.requests list after visiting a webpage

### ISSUE THREAD

**Issue by extratrees** [wkeeling/selenium-wire#590]
Hello,
First of all kudos for this great library. This is not a true issue rather than a question.
I was wondering if there was the possibility of clearing the `requests `attribute of the `webdriver` before visiting a new page, as I would like to avoid stopping and restarting a new driver for each web page.

**Comment by wkeeling** [comment]
Have you tried `del driver.requests`? E.g

```python
driver.get(...)  # visit a page 

del driver.requests  # clear requests 

driver.get(...)  # visit a new page
```

**Comment by hedonistrh** [comment]
Thanks @wkeeling, that was not my _issue_ but I needed that information as well. That is working very well and. 🙏🏼 

_Ps. Thanks for great library. 💯_

**Comment by maxp-hover** [comment]
Hi, I would request / recommend adding a way for this `del driver.requests` call to be atomic, e.g. in this example:

```
driver.get(...)  # visit a page 
del driver.requests  # clear requests 
driver.get(...)  # visit a new page
```

It seems to be possible that driver.requests still gets populated by the first page after the `del driver.requests` call.

Ideally, we could be guaranteed that the second `driver.get` call would start with an empty `driver.requests`, so we could know exactly which requests were associated with that page.
