### ISSUE TITLE
ImportError: cannot import name 'EdgeOptions' from 'selenium.webdriver' 

### ISSUE THREAD

**Issue by Meango** [wkeeling/selenium-wire#605]
I use selenimu-wire on my m1 macbook pro with python 3.10.4, but I can't import the package.
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/42886894/195016513-00fd9cbc-0dde-49b7-b70f-3a5946b24a42.png">

**Comment by wkeeling** [comment]
Thanks for raising this. What version of selenium are you running?

**Comment by dcnadler** [comment]
I get the same error with selenium==3.141.0
Looks like EdgeOptions is not available in selenium < 4.0

**Comment by Meango** [comment]
> Thanks for raising this. What version of selenium are you running?

My environments are as follow:
Python 3.10.4
selenium              3.141.0
selenium-wire         5.0.0

**Comment by Meango** [comment]
> 
My environments are as follow:

**Comment by Meango** [comment]
> 
My environments are as follow:
Python 3.10.4
selenium              3.141.0
selenium-wire         5.0.0

**Comment by Meango** [comment]
> Thanks for raising this. What version of selenium are you running?

My environments are as follow:
Python 3.10.4
selenium              3.141.0
selenium-wire         5.0.0

**Comment by wkeeling** [comment]
Selenium Wire has now been updated (v5.1.0) to ensure Selenium>=4.0.0 is installed.

**Comment by Meango** [comment]
> 

Thanks!

**Comment by Meango** [comment]
> Selenium Wire has now been updated (v5.1.0) to ensure Selenium>=4.0.0 is installed.

Thanks!
