### ISSUE TITLE
"no_proxy" has no effect

### ISSUE THREAD

**Issue by zax2002** [wkeeling/selenium-wire#615]
I'm trying to make selenium connect to a specific host bypassing proxy

```python
from seleniumwire import webdriver

proxy = "socks5://test:8080"

seleniumwireOptions = {
    "proxy": {
        "http": proxy,
        "https": proxy,
        "no_proxy": "api.ipify.org"
    },
}

driver = webdriver.Chrome(seleniumwire_options=seleniumwireOptions)

driver.get("http://api.ipify.org")

input()
```
![image](https://user-images.githubusercontent.com/25406324/199244096-133a8d70-4528-4fcb-af90-80d72571197f.png)

As a result, I get this. Seleniumwire backend is trying to connect to my proxy despite "no_proxy"
I also tried with a real working proxy, in this case, the site returns the ip of the proxy
What am i doing wrong, please help

**Comment by zax2002** [comment]
5.1.0

**Comment by wkeeling** [comment]
Thanks. I can reproduce. This seems to be a bug which will need investigating. We've had issues with the `no_proxy` setting in the past which have been fixed so this may be a regression or something new. I'll post when I've got further info.

**Comment by wkeeling** [comment]
This has been fixed. Available in the next release.
