### ISSUE TITLE
Logging Configuration

### ISSUE THREAD

**Issue by shr00mie** [wkeeling/selenium-wire#62]
First of all, thanks for fixing the signal issue. Allowed me to move forward with a project i was working on.

With that out of the way, and also because i don't want you sitting on your laurels for too long :wink:...i got a _flavor_ to ask:

For the love of all that is holy, please allow for some sort of syslog output configuration without having to modify your source. I mean i can get in there and rip it out manually, but i'd really rather not mess with your beautiful work. As it stands, by default, logging output from selenium-wire is...if i had to ballpark...like 95% of my syslog output and it's making me want to stick chopsticks in my eyeballs when i'm trying to troubleshoot stuff.

love you long time. :heart:

edit: spitballing - maybe like a singleton logging class? something you can init with a log level and filter?

```python
from seleniumwire import Logging
log = Logging(level = [None, 'INFO', 'DEBUG'], filter = 'GET')
```

it's also entirely possible i'm missing something, but i guess my main point is i'd like to be able to configure the logging level of selenium-wire independently of whatever program it may be running under.

**Comment by wkeeling** [comment]
Thanks @shr00mie . Yes Selenium Wire can be noisy in terms of logging although it depends on what log level you're using. Selenium Wire uses Python's standard logging module so you can set the logging level just for Selenium Wire itself, independently of the rest your app. You can turn the logging right down, e.g, to ERROR level, like this:
```
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('seleniumwire')
logger.setLevel(logging.ERROR)
```

The above assumes you're using the `logging.basicConfig()` mechanism to configure logging for your app, but you can apply the same principle if you're using other mechanisms - e.g. if you're using a config file or dictionary configuration (e.g. Django logging config).

**Comment by shr00mie** [comment]
today i learned things...

```python
selenium_logger = logging.getLogger('seleniumwire')
selenium_logger.setLevel(logging.ERROR)
```

carry on.
