### ISSUE TITLE
Is it possible to pass extra arguments (other than the request itself) to the request interceptor?

### ISSUE THREAD

**Issue by jordibonastrem** [wkeeling/selenium-wire#629]

**Comment by wkeeling** [comment]
What sort of arguments are you looking to pass?

**Comment by jordibonastrem** [comment]
I would need to pass strings.

**Comment by wkeeling** [comment]
Would you be looking to vary the string arguments on a per-request basis, or would the value of the arguments remain the same across multiple requests?

**Comment by jordibonastrem** [comment]
remain the same across multiple requests

**Comment by wkeeling** [comment]
You can set the arguments globally and just refer to them in your interceptor:

```python
a = "some string"
b = "another string"

def intercept(req):
    print(a, b, req)

driver.request_interceptor = interceptor
```
Alternatively you could wrap the interceptor in a closure and capture the variables that way, e.g.
```python
def wrapper(a, b):
    def intercept(req):
        print(a, b, req)
    return intercept

driver.request_interceptor = wrapper("some string", "another string")
```

**Comment by jordibonastrem** [comment]
Okai thx it works !, another question, im using residential proxies for some tasks to prevent geolocation cap. so my question is, can i change the proxy in the interceptor so i can just use the proxy for the request that i want, instead of wasting mb for other requests, i know i can change proxies doing the proxy = {}, but it would be more precise if i could just use the proxy on a specific request , is that possible, thx for the support wkeling!!

**Comment by wkeeling** [comment]
Unfortunately there's no way to change the proxy within an interceptor at the current time. To prevent unnecessary requests going through the proxy, you would either have to block them in the interceptor using `req.abort()` but this would obviously kill them which may or may not be ok depending upon your use case. The other option would be to bypass Selenium Wire completely for those requests by using [`exclude_hosts`](https://github.com/wkeeling/selenium-wire#limiting-request-capture) but that would only work if the requests were on a different domain.

**Comment by jordibonastrem** [comment]
Okai, thx anyways wkeeling!
