### ISSUE TITLE
sock5 protocol in seleniumwire_options

### ISSUE THREAD

**Issue by ZhaoHuizheng** [wkeeling/selenium-wire#67]
Hi wkeeling,

Thanks for your brilliant project.

I tried to let Selenium-wire to connect via Socks5 protocol with my configurations, but I could not figure out how to set so in the seleniumwire_options.

I tried several patterns, but all of them responded with 502 Bad Bateway.

With normal selenium, I can do so with the following command lines.
    options = Options()
    options.add_argument("--proxy-server=socks5://127.0.0.1:9150")
    driver = webdriver.Chrome(chrome_options=options, executable_path=chrome_path)

 but i want to see all the streams of requests hence i need to set an equivalant option in this brilliant seleniumwire.
Could you please let me know how to write selenium-wire options with the same configurations.

**Comment by wkeeling** [comment]
@ZhaoHuizheng  thanks for raising this.

I'm afraid Selenium Wire doesn't currently support socks5 proxy configuration. We've had a couple of requests for this now so I wonder whether it is something we should implement.

**Comment by ZhaoHuizheng** [comment]
Hi @wkeeling, thanks for respond kindly.

Thanks for making it clear that so far there is no way to use socks5 proxy in selenium-wire. I am happy to read that you are wondering if it is something to implement, and I would be super happy if you would do that kind implementation. Anyway, thanks for this brilliant project, I am very happy to see the all the streams of requests in selenium browsing with selenium-wire.

**Comment by Okidoki72** [comment]
Hi wkeeling, I would be also very interested in a socks5 proxy configuration!

**Comment by jeanmonet** [comment]
Same here, looking for Socks5 proxy support

**Comment by tommy2049** [comment]
Hello, would love a Socks5 implementation

**Comment by 1trackprojects1** [comment]
Yes please a socks5 implementation would be great

**Comment by wkeeling** [comment]
Selenium Wire (v1.0.12) now supports SOCKS based proxies. Get the new version with:

    pip install selenium-wire --upgrade

You can specify your SOCKS proxy in the same way as you would a regular HTTP proxy, but use the `socks5` scheme:

```
options = {
    'proxy': {
        'http': 'socks5://user:pass@192.168.10.100:8888',
        'https': 'socks5://user:pass@192.168.10.100:8889',
        'no_proxy': 'localhost,127.0.0.1'
    }
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

More info in [the docs](https://github.com/wkeeling/selenium-wire#socks). 

I've done my own testing but if you run into any issues, please let me know!
