### ISSUE TITLE
Not secure (unvalid certificate)

### ISSUE THREAD

**Issue by Mouad-scriptz** [wkeeling/selenium-wire#696]
Code to reproduce:
```py
import seleniumwire.undetected_chromedriver.v2 as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get("https://abrahamjuliot.github.io/creepjs/")
    input()
    r = driver.requests
```
Screenshot:
![image](https://github.com/wkeeling/selenium-wire/assets/102869034/272e906f-e036-4f78-87e5-a580c49803a1)

Issue:
So whenever I use selenium-wire's undetected chromedriver module it always gets blocked because of a invalid certificate, I already spent like 4 hours looking for a solution but there is none, any help is appreciated.

**Comment by A4Abhiraj** [comment]
https://github.com/wkeeling/selenium-wire/issues/120#issuecomment-1631275832
