### ISSUE TITLE
Proxy  is broken when used with following proxy option

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#70]
"proxy": { "no_proxy": "localhost" }

Error: ```python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 279, in __init__
   _, proxy_username, proxy_password, proxy_host = proxy_config.get('https')
TypeError: 'NoneType' object is not iterable```

**Comment by wkeeling** [comment]
This is fixed in version 2.0.0
