### ISSUE TITLE
mqtt requests not working

### ISSUE THREAD

**Issue by veerabio** [wkeeling/selenium-wire#71]
![image](https://user-images.githubusercontent.com/29557253/65377508-e9905700-dc61-11e9-95c4-636c38ca8b88.png)

Is there a way to make selenium-wire not handle the web socket traffic.

**Comment by wkeeling** [comment]
Have you tried excluding the web socket requests using [scopes](https://github.com/wkeeling/selenium-wire#scoping-request-capture)?

**Comment by veerabio** [comment]
thanks for replying. I tried using scopes but it didn't work. I will check again.

**Comment by wkeeling** [comment]
OK thanks. A couple of other questions: is your site using http or https? Also, are you using an upstream proxy?

**Comment by veerabio** [comment]
the site is using https. no upstream proxy.
i am using the following for seleniumwire_options
```
seleniumwire_options={
                "suppress_connection_errors": False,
                "scopes": ["ourdomain.com/api"]
            }
```
i think the scopes need to be set here
https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/proxy/server.py#L28

i did make that change locally but did not help. I will investigate a little more.

**Comment by veerabio** [comment]
I was able to set the --proxy-bypass-list option on chrome webdriver and i am able to bypass the proxy.
`chrome_options.add_argument("--proxy-bypass-list=*.amazonaws.com;*.mixpanel.com")`

**Comment by wkeeling** [comment]
Websockets are now properly supported from v4.1.0 onwards.
