### ISSUE TITLE
How can I change the ca cert?

### ISSUE THREAD

**Issue by artree-story** [wkeeling/selenium-wire#75]
When I build a exe object. I got an error: cert file is not correct. and chromedriver tips: it's not safe. please help me

**Comment by wkeeling** [comment]
The only way to change the `ca.crt` file currently would be to switch the file once you have installed Selenium Wire. The `ca.crt` file lives here:

```
<python install or venv>/lib/pythonXXX/site-packages/seleniumwire/proxy/ca.crt
```

Try switching the file in that location and then re-running your test.

We could perhaps allow the root certificate to be overridden via a config option in a future release to make this easier.

**Comment by artree-story** [comment]
Thanks for reply and your work.  When I open in chrome with some website, I will got the `Not secure` message and Cetificate is invalid even I add the `ca.crt` to the root certificate in chrome settings. Chrome is latest, 78.0.3904.70.

**Comment by artree-story** [comment]
```
DevTools listening on ws://127.0.0.1:56677/devtools/browser/9c7c7894-3ac4-4935-bd71-2d3f0508dda6
[3440:13980:1029/224848.180:ERROR:ssl_client_socket_impl.cc(969)] handshake failed; returned -1, SSL error code 1, net_error -100
```
And I got the error when I open the exe obj.

**Comment by wkeeling** [comment]
There was a problem with the root certificate not using the most up to date digest (SHA256) which has now been fixed. Upgrading Selenium Wire should hopefully resolve this issue for you. If you continue to have a problem after upgrading, feel free to open a new issue.

**Comment by P-Leo10** [comment]
Hi, i have the same problem. How can i change the `ca.crt` to resolve my problem? @wkeeling

**Comment by wkeeling** [comment]
@P-Leo10 are you using the latest version of Selenium Wire? You can download the `ca.crt` certificate here: https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt

Save the file and install it as a certificate authority in the Certificates area in your browser's settings.
