### ISSUE TITLE
web application login is not working with selenium wire

### ISSUE THREAD

**Issue by prasannakaja** [wkeeling/selenium-wire#76]
Web application login is failing with valid credentials using selenium-wire whereas the same is working with selenium webdriver.

**Comment by wkeeling** [comment]
When you say the login is failing, what response do you receive? Is there any specific information coming through in the logs? You may need to turn logging up to DEBUG and [suppress connection errors](https://github.com/wkeeling/selenium-wire#other-options) with:

```
options = {
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

**Comment by prasannakaja** [comment]
@wkeeling , Sorry for the partial information. Actually i tried by suppressing connection errors. I find nothing in debug logs as well.

 when i try to login, giving me invalid credentails error. But actually credentials are correct. Infact the same is working using selenium webdriver and failing in selenium-wire weddriver.
Any clue about this??

Here I attached debug logs printed on the console.
[sw_logs.txt](https://github.com/wkeeling/selenium-wire/files/3869023/sw_logs.txt)

**Comment by wkeeling** [comment]
Thank you @prasannakaja . I can't seem to see anything particularly interesting in the logs.

A few questions:

- Are you using a self-signed certificate?
- Are you using an upstream proxy server?
- Does the username/password that is failing contain non-ascii characters?

**Comment by prasannakaja** [comment]
> Thank you @prasannakaja . I can't seem to see anything particularly interesting in the logs.
> 
> A few questions:
> 
> * Are you using a self-signed certificate?
> * Are you using an upstream proxy server?
> * Does the username/password that is failing contain non-ascii characters?

**Comment by prasannakaja** [comment]
> > * Are you using a self-signed certificate?
Yes. But im skipping ssl validation by giving below options. Infact after skipping ssl validation only web page loaded. Till then web page itself is not loaded.
options = {
    'verify_ssl': False,
    'suppress_connection_errors': False,
    'disable_encoding': True
}
> > * Are you using an upstream proxy server?
No proxy.
> > * Does the username/password that is failing contain non-ascii characters?
No non-ascii characters. text i used is "welcome"

**Comment by prasannakaja** [comment]
Closed by mistake. Issue not resolved. So reopening it again

**Comment by bulentozk** [comment]
I have the exact same issue. Not possible to login the website with selenium-wire.

**Comment by wkeeling** [comment]
Thanks @bulentozk . Are you able to share the URL of the site you're trying to login to, or is it not public?

**Comment by wkeeling** [comment]
It may be worth trying the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends) if you get a chance. That may help narrow down the issue.
