### ISSUE TITLE
How to use multiple proxy authentication 

### ISSUE THREAD

**Issue by taimursaeed** [wkeeling/selenium-wire#77]
I want to scrap website each time with different proxy , is there a way to change the proxy option for same driver object or i need to create new object for each new proxy?

**Comment by wkeeling** [comment]
The proxy configuration is set per driver instance, so yes I'm afraid you'll need to create a new driver object for each set of proxy configuration.

**Comment by taimursaeed** [comment]
@wkeeling Yes i had to create new instance for new configuration
