### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by skzaproxy** [wkeeling/selenium-wire#81]
I provided proxy as:
options = {
    'verify_ssl': False,  # Don't verify self signed certificate
    'proxy': {
        'http': 'http://myhost:8080',
        'https': 'http://myhost:8080',
        'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
    },
    'suppress_connection_errors': False  # Show connection errors
}
driver = webdriver.Firefox(seleniumwire_options=options)

Output:
Firefox launches the URL and when I check proxy is again set to "127.0.0.1" and some random port number.

Expected output:
http(s) Proxy in firefox browser should be set to: host as "myhost" and port as "8080"

**Comment by wkeeling** [comment]
Selenium Wire works by injecting it's own proxy into the browser which it uses to capture requests and responses. That proxy runs on 127.0.0.1 and uses any available port number. This proxy server is always set and this is the proxy that will be visible in Firefox's settings.

When you specify your own proxy using `seleniumwire_options`, these settings are used internally by Selenium Wire which it uses to forward requests on to. The settings are thus not visible in Firefox.

I hope that makes things clearer.

**Comment by skzaproxy** [comment]
Thanks for your response.
From your response I understand, selenium-wire runs and listens on
127.0.0.1 and any available port.
For products that are behind proxy, selenium-wire accepts the proxy
settings using "seleniumwire_options" and uses it internally. If this is
the case then the product under test should be accessible.
In my case, if I access the products that are behind a proxy, they are
accessible only when I set the proxy in chrome and firefox. but when I set
proxy using "selenium-wire" options I get following as a response:

[image: image.png]

Thanks in advance for your taking the time to respond

Regards
Supriya

**Comment by wkeeling** [comment]
Thanks. The image didn't come through - are you able to paste the text?

I notice that for your `https` proxy setting, that the URL you're using is `http`:

```
'https': 'http://myhost:8080',
```

Is that correct?

**Comment by skzaproxy** [comment]
Hi,

my proxy is something like:
myhost: xxx-yyyy.xx.yyyyyy.net
port: 8080

Error that I get is:
Error code: 502 (invalid response from another server/proxy)


Regards
Supriya

**Comment by wkeeling** [comment]
@skzaproxy did you manage to resolve this issue?
