### ISSUE TITLE
driver.header_overrides do not set request header in browser properly

### ISSUE THREAD

**Issue by Roskolnikov** [wkeeling/selenium-wire#82]
So i got this short code in selenium-wire:
```
from seleniumwire import webdriver  # Import from seleniumwire
from pprint import pprint
# Create a new instance of the Firefox driver
driver = webdriver.Firefox()

print("---Modify headers---")
driver.header_overrides = {
    'XYZ1': 'ABC1',
    'XYZ2': 'ABC2'
}

#driver._client.set_header_overrides(
#    headers={
#        'User-Agent': 'Mozilla/5.0 (test)',
#        'XYZ1': 'ABC1',
#        'XYZ2': 'ABC2'
#    })
print("---Open with modifed headers---")
driver.get('https://www.wikipedia.org/')
for request in driver.requests:
    if request.response:
        print(request.path, request.response.status_code)
        pprint(dict(request.headers))
```

and script return for example this piece of logs:
![image](https://user-images.githubusercontent.com/58191979/69579872-ae98ff80-0fd3-11ea-95ed-f206c3efbbc4.png)
As you can see my field & values are added at end of header. However in Firefox GUI when I inspect headers (during debug) there's no my changes at all.
![image](https://user-images.githubusercontent.com/58191979/69580041-09325b80-0fd4-11ea-9c5c-3ecb9c601951.png)

I'm using newest selenium-wire and Firefox 70.0.1

**Comment by wkeeling** [comment]
The custom headers are injected into the request by Selenium Wire _after_ the browser sends them. This means that you won't see the headers the Firefox console.
