### ISSUE TITLE
Problem with seleniumwire.quit() method

### ISSUE THREAD

**Issue by joaomedeiros95** [wkeeling/selenium-wire#88]
Hey guys,

I'm working with selenium-wire and I had a strange bug.

I have some threads that get a Selenium Chrome Driver to work with, when I do my first `quit()` all the next calls to `WebDriverWait(driver, 10).until(...)` will fail with a timeout. If a don't call the `quit()` method everything works forever.

I made a small test that reproduces the problem:

```
from selenium.webdriver import DesiredCapabilities
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions
from seleniumwire import webdriver  # Import from seleniumwire
from selenium.webdriver.chrome.options import Options

for _ in range(2):
    driver = None
    try:
        chromium_file = "/Applications/Chromium.app/Contents/MacOS/Chromium"
        if chromium_file:
            chrome_options = Options()
            chrome_options.add_argument("--headless")
            chrome_options.add_argument("--no-sandbox")
            chrome_options.add_argument("--disable-gpu")
            chrome_options.add_argument("--disable-features=NetworkService")

            chrome_options.binary_location = chromium_file

            capabilities = DesiredCapabilities.CHROME

            driver = webdriver.Chrome(chrome_options=chrome_options,
                                      desired_capabilities=capabilities)

        # Go to the Google home page
        driver.get('https://www.google.com')

        WebDriverWait(driver, 10).until(
            expected_conditions.presence_of_element_located((By.ID, 'doc-info')))

        # Access requests via the `requests` attribute
        for request in driver.requests:
            if request.response:
                print(
                    request.path,
                    request.response.status_code,
                    request.response.headers['Content-Type']
                )
    finally:
        if driver:
            driver.quit()
```

**Versions of the dependencies:**
- selenium 3.141.0        
- selenium-wire 1.0.10

**Running on:** MacOS Catalina 10.15.2

Do you guys have any idea of what is going on?

**Comment by wkeeling** [comment]
Selenium Wire overrides `driver.quit()` in order to shutdown it's embedded proxy server. After the first thread calls `driver.quit()`, any subsequent requests will fail (timeout) because the proxy server is no longer accepting connections.

Rather than using `driver.quit()` can you try `driver.close()`? This will close the browser window without shutting down the embedded proxy server.

**Comment by joaomedeiros95** [comment]
@wkeeling the strange thing is if I don't instantiate Options() every time that I create the web driver everything works as expected, even if I call quit() in the end.

**Comment by wkeeling** [comment]
Thanks @joaomedeiros95. I'm not entirely sure I understand the reason for that, but good that it's now working for you.
