### ISSUE TITLE
Selenium-wire cache folder take all my disk space

### ISSUE THREAD

**Issue by tdautreme** [wkeeling/selenium-wire#89]
The cache folder take all my disk space. I have to remove it with my script often.
Can you solve this ?

**Comment by wkeeling** [comment]
Are you calling `webdriver.quit()` at the end of your test? This method will shutdown Selenium Wire and clear the request cache.

**Comment by tdautreme** [comment]
I can't because I use selenium with a PC with no enough memory then the bot program crash because firefox crash and then I have an another program which restart the bot program :/

**Comment by wkeeling** [comment]
The `webdriver.quit()` method will ensure that the request capture folder is cleared out when the test finishes. However, you can also [filter out requests](https://github.com/wkeeling/selenium-wire#scoping-request-capture) that you're not interested in whilst Selenium is running. Filtered  requests will not be captured and thus won't take up disk space.

Another alternative is to filter out all requests that use a particular HTTP method, using the `ignore_http_methods` [option](https://github.com/wkeeling/selenium-wire#other-options). However, that may not be practical.

**Comment by CircuitSacul** [comment]
You should use `try` and `finally`. Doing this will allow you to run code even if it crashes. Here is an example:
```python
from seleniumwire import webdriver

driver = webdriver.Chrome()

try:
    driver.get("https://github.com")
finally:
    driver.quit() #This runs even if the code under try crashes
```

**Comment by wkeeling** [comment]
@tdautreme did you manage to solve the disk space issue with the suggestions regarding `driver.quit()`?

**Comment by tdautreme** [comment]
@wkeeling Yes I remove the cache folder when firefox crash, and then the program restart
