### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by pedrosalesmiranda** [wkeeling/selenium-wire#92]
Sorry to use issues feel free to redirect me to proper channel to ask this kind of questions.

Is it possible with the current selenium-wire to get the **query string** of a request?

For example:
https://translate.google.com/translate_tts?**ie=UTF-8&q=mesa&tl=es&total=1&idx=0&textlen=9&tk=238110.333510&client=webapp**

Would be great any ideas or clues on this.

Cheers
Pedro M.

**Comment by wkeeling** [comment]
Sorry for the delay in getting back to you.

Selenium Wire doesn't have a dedicated method to retrieve the query string currently. However, it's fairly straightforward to parse it from the `request.path`. For example:

```
from urllib import parse

for request in driver.requests:
    query_string = parse.urlsplit(request.path).query
    print(query_string)
```
We should perhaps look at adding a convenience method to the `request` object to retrieve the query string. I'll open a separate issue to address that.

Many thanks!

**Comment by pedrosalesmiranda** [comment]
Thanks a lot that solved my problem. I think that would be interesting
feature. But also I was not aware that request.path also contained the
query I was really convinced i tried that before, need to sleep more :)
