### ISSUE TITLE
Chrome driver.requests not printing requests

### ISSUE THREAD

**Issue by agarneata** [wkeeling/selenium-wire#93]
When running the following code with the Chrome webdriver, nothing prints out, but it works fine with the firefox webdriver.  Is there a reason why it wouldn't be showing for Chrome?  I am using the latest versions of seleniumwire, selenium, and python 3.

from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.remote_connection import RemoteConnection

RemoteConnection.set_timeout(30)
driver = webdriver.Chrome()

driver.get(url)
driver.find_element(By.ID, "SOME_ID").click()
for request in driver.requests:
	print(request.path)

**Comment by wkeeling** [comment]
The code looks fine as far as I can tell. It's possible that the line `driver.find_element(By.ID, "SOME_ID").click()` maybe causing an issue though (e.g. if `SOME_ID` wasn't found). 

Can you rerun without that line? E.g. 

```
from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.remote_connection import RemoteConnection

RemoteConnection.set_timeout(30)
driver = webdriver.Chrome()

driver.get(url)
#driver.find_element(By.ID, "SOME_ID").click()
for request in driver.requests:
print(request.path)
```

**Comment by agarneata** [comment]
I re-ran it without the SOME_ID line and got the same result, no paths were printed.

**Comment by agarneata** [comment]
@wkeeling were you able to look into this further?  I am still not seeing paths printed when running the script with the Chrome driver.

**Comment by wkeeling** [comment]
Sorry for the delay. I suspect something is falling over and you're not seeing the traceback because logging isn't enabled. Could you try enabling logging, and also enabling connection logging, e.g. -

```
# Enable logging
import logging
logging.basicConfig(level=logging.DEBUG)

from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.remote_connection import RemoteConnection

RemoteConnection.set_timeout(30)

# Enable connection logging
options = {
    'suppress_connection_errors': False  # Show full tracebacks for any connection errors
}

driver = webdriver.Chrome(seleniumwire_options=options)  # Pass the options to the driver

driver.get(url)
driver.find_element(By.ID, "SOME_ID").click()
for request in driver.requests:
print(request.path)
```

After doing that try re-running your test and see what comes out in the console.

**Comment by agarneata** [comment]
Here is what i get in the console with logging enabled and still no path output:

INFO:seleniumwire.proxy.client:Created proxy listening on 127.0.0.1:18710
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:18711/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:18710", "sslProxy": "127.0.0.1:18710", "noProxy": ""}, "acceptInsecureCerts": true}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:18710", "sslProxy": "127.0.0.1:18710", "noProxy": ""}, "acceptInsecureCerts": true}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:18711

DevTools listening on ws://127.0.0.1:18722/devtools/browser/ed9cd1db-9fdb-4670-a3c5-c5eeb30a6d92
DEBUG:urllib3.connectionpool:http://127.0.0.1:18711 "POST /session HTTP/1.1" 200 776
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:18711/session/1e1ad67da85171b67e4e8a4f2c65c6e6/url {"url": "https://github.com"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:18711 "POST /session/1e1ad67da85171b67e4e8a4f2c65c6e6/url HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:seleniumwire.proxy.handler:http://seleniumwire/requests 200
INFO:seleniumwire.proxy.client:Destroying proxy
DEBUG:seleniumwire.proxy.storage:Cleaning up C:\Users\agarnezi\.seleniumwire\storage-fa2039f5-34f9-4505-9a55-2c34440eb746
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://127.0.0.1:18711/session/1e1ad67da85171b67e4e8a4f2c65c6e6 {}
DEBUG:urllib3.connectionpool:http://127.0.0.1:18711 "DELETE /session/1e1ad67da85171b67e4e8a4f2c65c6e6 HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by agarneata** [comment]
@wkeeling did the debug info help?  I am still seeing this issue where chrome doesn't print the paths with request.path

**Comment by wkeeling** [comment]
I don't seem to see any log messages about capturing requests which I'd expect to see. I can see you're trying to navigate to `https://github.com`.

What version of Chrome on Windows are you using? I'll see if I can reproduce.

**Comment by agarneata** [comment]
Here is the version: Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by wkeeling** [comment]
Thanks. My version of Chrome was slightly behind, so I upgraded it to the latest 81.0.4044.129 but I wasn't able to reproduce the issue.

I suspect the issue you're seeing could be specific to your environment. Could you try running the test again, but with options to tell Chrome to use a clean profile and start igcognito mode.

```
from selenium.webdriver.chrome.options import Options

...

chrome_options = Options()
chrome_options.add_argument('--user-data-dir=/dev/null')  # Start with a clean profile
chrome_options.add_argument('--incognito')

driver = webdriver.Chrome(
    seleniumwire_options=options, 
    chrome_options=chrome_options
)
```

**Comment by mattroconnor** [comment]
I am having a similar issue Chrome driver.requests is missing the requests I'm actually sending when using a proxy server extension. Should I open a new ticket, update this one, or is this a known "feature"?

**Comment by agarneata** [comment]
I attempted this in my Linux environment and it worked but still not able to get this to work in on my Windows host.

**Comment by wkeeling** [comment]
@mattroconnor Thanks for the comment. When you say "proxy server extension" is that an external extension that you've installed into Chrome?

**Comment by wkeeling** [comment]
@agarneata is Chrome on your Windows host using a proxy server (check in Chrome settings > Advanced > System > Proxy Settings)

**Comment by mattroconnor** [comment]
@wkeeling So when I use the proxy setup via seleniumwire docs (https://pypi.org/project/selenium-wire/#proxies) I almost immediately get banned by any website using detection methods, almost as if the fact that a proxy is being used is clearly exposed to the end destination.

As a result, I connect to a proxy using an external extension installed into Chrome correct. Yet when using this option for some reason requests I send do not show in driver.requests. For example "driver.get(abc)"seleniumwire requests doesn't seem to 'see' the abc request, though other requests made indirectly, such as google analytics api calls triggered by abc website, do show...

**Comment by agarneata** [comment]
@wkeeling Yes, my windows host is using a proxy server

**Comment by wkeeling** [comment]
Thanks @mattroconnor I guess the Chrome proxy extension may be interfering with the proxy that Selenium Wire tries to inject into the browser when you run it. 

I'd be interested to get to the bottom of the issue with external websites banning you. Do you see a particular error here - e.g. a privacy error, or certificate authority error? Are you able to post some example text?

**Comment by wkeeling** [comment]
Thanks @agarneata I'll see if I can reproduce in Windows by setting up a proxy server first and then running Selenium Wire.

**Comment by mattroconnor** [comment]
@wkeeling Thanks, let me know if you prefer I open a separate issue. Here is a sample snippet and screenshot.

`from seleniumwire import webdriver

wire_options = {
    'proxy': {
        'http': '<redacted>', 
        'https': '<redacted>',
        'no_proxy': 'localhost,127.0.0.1' # excludes
    }
}

options = webdriver.ChromeOptions()

prefs = {
    "profile.managed_default_content_settings.images":1,
    "profile.default_content_setting_values.notifications":2,
    "profile.managed_default_content_settings.stylesheets":2,
    "profile.managed_default_content_settings.cookies":1,
    "profile.managed_default_content_settings.javascript":1,
    "profile.managed_default_content_settings.plugins":2,
    "profile.managed_default_content_settings.popups":2,
    "profile.managed_default_content_settings.geolocation":2,
    "profile.managed_default_content_settings.media_stream":2

}
options.add_experimental_option("prefs",prefs)

# Various settings to decrease detection
options.add_argument("--incognito")
options.add_argument("start-maximized")
options.add_argument('--disable-infobars')
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--disable-blink-features")
options.add_argument("--disable-blink-features=AutomationControlled")

chrome = webdriver.Chrome(executable_path=<path>,seleniumwire_options=wire_options,chrome_options=options)

# Gets immediately banned on refresh or second attempt
# Same exact code above using selenium (not seleniumwire) on same proxy IPs does not get detected
chrome.get("http://www.whoscored.com/")`
![second_request](https://user-images.githubusercontent.com/12855201/83197935-57075800-a10c-11ea-8599-4151cce1b3f6.JPG)
![first_request_network](https://user-images.githubusercontent.com/12855201/83197936-579fee80-a10c-11ea-8703-ebd895d0cee9.JPG)
![first_request](https://user-images.githubusercontent.com/12855201/83197938-579fee80-a10c-11ea-8180-542bce25dc52.JPG)

**Comment by wkeeling** [comment]
@agarneata I tried reproducing but no joy unfortunately. I configured Chrome with a proxy server first, and then ran Selenium Wire. The requests continued to print out ok. 

I'm thinking there must be something specific to your Windows environment that's affecting Chrome. I'd be interested to know whether setting this option makes any difference:

```
chrome_options = Options()
chrome_options.add_argument('--user-data-dir=/dev/null')  # Start with a clean profile

driver = webdriver.Chrome(
    chrome_options=chrome_options
)
```

**Comment by agarneata** [comment]
@wkeeling I tried the script with that option but the requests still did not print out.  I'm not sure what other differences in my windows environment could be causing this.

**Comment by wkeeling** [comment]
@agarneata do you still have this issue in your Windows environment with Chrome?

**Comment by agarneata** [comment]
@wkeeling i am still having this issue in my Windows environment with Chrome, I updated my chrome driver and selenium-wire to the latest versions as well.

DEBUG:seleniumwire.proxy.handler:http://seleniumwire/initialise 200
INFO:seleniumwire.proxy.client:Created proxy listening on 127.0.0.1:8239
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:8241/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:8239", "sslProxy": "127.0.0.1:8239", "noProxy": ""}, "acceptInsecureCerts": true, "goog:chromeOptions": {"extensions": [], "args": ["--user-data-dir=/dev/null", "--incognito", "--no-sandbox"]}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:8239", "sslProxy": "127.0.0.1:8239", "noProxy": ""}, "acceptInsecureCerts": true, "goog:chromeOptions": {"extensions": [], "args": ["--user-data-dir=/dev/null", "--incognito", "--no-sandbox"]}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8241

DevTools listening on ws://127.0.0.1:8247/devtools/browser/1a94a79b-505f-4b55-abb0-ffe112bea086
DEBUG:urllib3.connectionpool:http://127.0.0.1:8241 "POST /session HTTP/1.1" 200 748
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:8241/session/70c7f42d9f5af5f21a0370b68a654eea/url {"url": "https://github.com"}
[25080:25084:0812/163529.308:ERROR:device_event_log_impl.cc(208)] [16:35:29.307] Bluetooth: bluetooth_adapter_winrt.cc:1205 Getting Radio failed. Chrome will be unable to change the power state by itself.
[25080:25084:0812/163529.359:ERROR:device_event_log_impl.cc(208)] [16:35:29.359] Bluetooth: bluetooth_adapter_winrt.cc:1298 OnPoweredRadiosEnumerated(), Number of Powered Radios: 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8241 "POST /session/70c7f42d9f5af5f21a0370b68a654eea/url HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:seleniumwire.proxy.handler:http://seleniumwire/requests 200
INFO:seleniumwire.proxy.client:Destroying proxy
DEBUG:seleniumwire.proxy.storage:Cleaning up C:\Users\*********\.seleniumwire\storage-fe1fd4ea-9128-46ff-88f4-8ac685433051
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://127.0.0.1:8241/session/70c7f42d9f5af5f21a0370b68a654eea {}
DEBUG:urllib3.connectionpool:http://127.0.0.1:8241 "DELETE /session/70c7f42d9f5af5f21a0370b68a654eea HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by wkeeling** [comment]
Thanks @agarneata 

I can only think that something in your Windows environment is telling Chrome to ignore Selenium Wire's proxy (Selenium Wire's proxy config is listed in your output above: `"httpProxy": "127.0.0.1:8239", "sslProxy": "127.0.0.1:8239"`). Have you tried temporarily disabling your Windows system proxy to see if that makes any difference?

**Comment by agarneata** [comment]
@wkeeling I disabled my windows system proxy but it didn't make a difference

**Comment by wkeeling** [comment]
@agarneata thanks. One other thing to try, is to run Selenium Wire in stand alone mode, and manually configure Chrome to talk to it. That may give us some additional clues.

You can run in stand alone mode with:

```
python -m seleniumwire standaloneproxy 12345
```
Then in Chrome, go to the proxy settings and set up a manual proxy for `localhost` on port `12345`.

Once done, try going to a web page in Chrome. You should see "capturing" messages come through in the console if it is working.

**Comment by agarneata** [comment]
@wkeeling when running Selenium Wire in stand alone mode and updating my proxy settings,, I am able to see Chrome talk to the it while browsing Github.com, here are a few lines:
Capturing request: https://github.githubassets.com/assets/environment-bootstrap-0b18da31.js
Capturing response: https://github.githubassets.com/images/search-key-slash.svg 200 OK
https://github.githubassets.com/images/search-key-slash.svg 200
Capturing response: https://github.githubassets.com/images/modules/site/home/team.svg 200 OK
github.githubassets.com:443 200
Capturing response: https://github.githubassets.com/assets/frameworks-8c550109d58e0353afdf1a37a05301c2.css 200 OK
Capturing response: https://github.githubassets.com/assets/site-7ea9d9b5acaa80b0a67107f15e9e4e1f.css 200 OK
https://github.githubassets.com/images/modules/site/home/team.svg 200
Capturing request: https://github.githubassets.com/assets/vendor-78374193.js
Capturing response: https://github.githubassets.com/assets/github-36f60e1fc11f3e85242ffa676dd886fe.css 200 OK

**Comment by wkeeling** [comment]
@agarneata that's good as it indicates that there's nothing fundamentally wrong with the underlying core of Selenium Wire. It seems that the issue you see when running a script is down to the browser refusing to accept the proxy settings that Selenium Wire transparently sends it. I can only think there is some security policy causing this restriction. Chrome uses the underlying system's (Windows) proxy settings, unlike Firefox which uses it's own.

**Comment by agarneata** [comment]
@wkeeling got it, thanks for the help, i'll look into that then

**Comment by spinlud** [comment]
I had a similar issue under MacOS (unable to capture requests).
I found the problem was this chrome option: `--proxy-bypass-list=*`. Removing it should enable requests capture again, at least in my case. Hope this helps

**Comment by agarneata** [comment]
@spinlud how did you remove the --proxy-bypass-list=* option?

**Comment by spinlud** [comment]
@agarneata I was passing it as an option to the Chrome driver:

```python
chrome_options.add_argument('--proxy-bypass-list=*')
```

**Comment by agarneata** [comment]
@spinlud I tried both with and without that argument and still no luck, it's probably something on my Windows environment as it's working fine on my Linux system.
