### ISSUE TITLE
How can I import my firefox cert to selenium-wire?

### ISSUE THREAD

**Issue by stll-wo** [wkeeling/selenium-wire#97]
Is it possible, and how?

**Comment by wkeeling** [comment]
If you're looking to get rid of the "insecure connection" warning in the browser address bar, then what you actually need to do is to import Selenium Wire's certificate into Firefox.

To install the certificate, you first need to extract it from Selenium Wire by running:

```
 python -m seleniumwire extractcert
```

(or download it [here](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/proxy/ca.crt))

That will produce a file called `ca.crt` in the current working directory. You then need to go into Firefox's preferences, navigate to "Privacy and Security" > "Certificates", click "View Certificates" and then click "Import". Select the `ca.crt` file and ensure you check all the boxes regarding permissions. Then re-run your test.
